import Types "../types/exams";
import List "mo:core/List";

module {
  public func seedV6(
    versions : List.List<Types.ExamVersion>,
    questions : List.List<Types.Question>
  ) : () {

    versions.add({ id = "ptcb-v6"; examId = "ptcb"; versionName = "Practice Test 6"; totalQuestions = 90; scoredQuestions = 80; timeLimitMinutes = 110 });

    // Medications (36)
    questions.add({ id = "ptcb-v6-q1"; versionId = "ptcb-v6"; text = "What is the brand name of escitalopram?"; options = ["Zoloft", "Prozac", "Lexapro", "Celexa"]; correctOptionIndex = 2; explanation = "Escitalopram (Lexapro) is an SSRI used for depression and generalized anxiety disorder. Celexa = citalopram, Prozac = fluoxetine, Zoloft = sertraline."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q2"; versionId = "ptcb-v6"; text = "Rosuvastatin differs from simvastatin in that rosuvastatin:"; options = ["Is primarily metabolized by CYP3A4", "Has fewer drug interactions through CYP3A4 and can be given at any time of day", "Must be taken at bedtime only", "Is a fibrate, not a statin"]; correctOptionIndex = 1; explanation = "Rosuvastatin is minimally metabolized by CYP3A4 (unlike simvastatin/atorvastatin), reducing interactions with CYP3A4 inhibitors (e.g., clarithromycin). It can be taken at any time of day."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q3"; versionId = "ptcb-v6"; text = "Quetiapine (Seroquel) belongs to which drug class?"; options = ["SSRI antidepressant", "Atypical antipsychotic", "Mood stabilizer (lithium class)", "First-generation antipsychotic"]; correctOptionIndex = 1; explanation = "Quetiapine (Seroquel) is an atypical (second-generation) antipsychotic used for schizophrenia, bipolar disorder, and as adjunctive therapy for depression."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q4"; versionId = "ptcb-v6"; text = "Which of the following opioid analgesics is 100 times more potent than morphine?"; options = ["Codeine", "Hydrocodone", "Fentanyl", "Tramadol"]; correctOptionIndex = 2; explanation = "Fentanyl is approximately 100 times more potent than morphine on a milligram basis. This extreme potency makes accidental exposure particularly dangerous."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q5"; versionId = "ptcb-v6"; text = "What is the brand name of gabapentin?"; options = ["Lyrica", "Neurontin", "Lamictal", "Topamax"]; correctOptionIndex = 1; explanation = "Gabapentin (Neurontin) is used for neuropathic pain, partial seizures, and restless legs syndrome. Lyrica = pregabalin; Lamictal = lamotrigine; Topamax = topiramate."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q6"; versionId = "ptcb-v6"; text = "Clopidogrel (Plavix) inhibits platelet aggregation by:"; options = ["Blocking COX-1 and COX-2", "Irreversibly blocking the P2Y12 ADP receptor on platelets", "Inhibiting factor Xa", "Blocking the GPIIb/IIIa receptor"]; correctOptionIndex = 1; explanation = "Clopidogrel irreversibly blocks the P2Y12 ADP receptor, preventing ADP-induced platelet aggregation. Its antiplatelet effect persists for the lifespan of the platelet (7-10 days)."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q7"; versionId = "ptcb-v6"; text = "Which drug is used for smoking cessation and carries a black box warning for neuropsychiatric side effects?"; options = ["Bupropion only", "Varenicline (Chantix)", "Nicotine replacement only", "Naltrexone"]; correctOptionIndex = 1; explanation = "Varenicline (Chantix) is a partial nicotinic receptor agonist for smoking cessation. It formerly had a black box warning for neuropsychiatric adverse events (hostility, depression, suicidal ideation), though this was later revised."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q8"; versionId = "ptcb-v6"; text = "Amlodipine (Norvasc) is a dihydropyridine CCB. This means it primarily:"; options = ["Slows heart rate and reduces AV conduction", "Causes peripheral vasodilation with minimal cardiac depressant effect", "Blocks beta receptors in the heart", "Inhibits ACE in the lungs"]; correctOptionIndex = 1; explanation = "Dihydropyridine CCBs (amlodipine, nifedipine) act predominantly on vascular smooth muscle causing vasodilation, with little cardiac rate/conduction effect. Non-dihydropyridines (diltiazem, verapamil) have more cardiac effects."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q9"; versionId = "ptcb-v6"; text = "Which of the following antibiotics is used to treat community-acquired pneumonia (CAP) in outpatients?"; options = ["Vancomycin IV", "Azithromycin or doxycycline (atypical coverage)", "Metronidazole", "Nitrofurantoin"]; correctOptionIndex = 1; explanation = "Azithromycin or doxycycline are recommended for outpatient CAP treatment due to coverage of atypical pathogens (Mycoplasma, Chlamydophila). Amoxicillin is an alternative for typical bacterial CAP."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q10"; versionId = "ptcb-v6"; text = "Which medication class is used to treat attention deficit hyperactivity disorder (ADHD) and is a Schedule II stimulant?"; options = ["Benzodiazepines", "Amphetamine salts (Adderall)", "SSRIs", "Antipsychotics"]; correctOptionIndex = 1; explanation = "Amphetamine mixed salts (Adderall) and methylphenidate (Ritalin) are Schedule II CNS stimulants first-line for ADHD. They increase dopamine and norepinephrine in the prefrontal cortex."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q11"; versionId = "ptcb-v6"; text = "Trimethoprim-sulfamethoxazole (TMP-SMX, Bactrim) is commonly used to treat:"; options = ["Streptococcal pharyngitis", "Uncomplicated UTIs and MRSA skin infections", "Clostridioides difficile colitis", "Anaerobic infections"]; correctOptionIndex = 1; explanation = "TMP-SMX (Bactrim) is first-line for uncomplicated UTIs (if susceptible) and commonly used for community-acquired MRSA soft tissue infections. It is not appropriate for strep throat or C. diff."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q12"; versionId = "ptcb-v6"; text = "A patient has a penicillin allergy with a history of anaphylaxis. Which antibiotic should be AVOIDED?"; options = ["Azithromycin", "Imipenem (a carbapenem)", "Doxycycline", "Clindamycin"]; correctOptionIndex = 1; explanation = "Carbapenems (imipenem, meropenem) share structural similarity with penicillins (both are beta-lactams) and carry a risk of cross-reactivity in patients with severe penicillin allergy. Use with extreme caution or avoid."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q13"; versionId = "ptcb-v6"; text = "What is the mechanism of action of sulfonylureas such as glipizide?"; options = ["Inhibit hepatic glucose production", "Stimulate pancreatic beta cells to release insulin (regardless of blood glucose)", "Block SGLT-2 in the renal tubule", "Activate PPAR-gamma receptors"]; correctOptionIndex = 1; explanation = "Sulfonylureas (glipizide, glyburide, glimepiride) stimulate insulin secretion from pancreatic beta cells independent of blood glucose levels, which is why they can cause hypoglycemia."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q14"; versionId = "ptcb-v6"; text = "Which of the following medications is an inhaled long-acting muscarinic antagonist (LAMA) used for COPD?"; options = ["Albuterol (Ventolin)", "Tiotropium (Spiriva)", "Fluticasone (Flovent)", "Montelukast (Singulair)"]; correctOptionIndex = 1; explanation = "Tiotropium (Spiriva) is a LAMA bronchodilator used for COPD maintenance. It blocks muscarinic receptors in the airways, reducing bronchoconstriction and secretions."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q15"; versionId = "ptcb-v6"; text = "Ondansetron (Zofran) is used for:"; options = ["Pain management", "Nausea and vomiting (including chemotherapy-induced)", "Anxiety", "GERD"]; correctOptionIndex = 1; explanation = "Ondansetron (Zofran) is a 5-HT3 receptor antagonist antiemetic used for prevention and treatment of nausea/vomiting from chemotherapy, radiation, and surgery."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q16"; versionId = "ptcb-v6"; text = "Which drug interaction can cause serotonin syndrome when tramadol is combined with?"; options = ["Lisinopril", "SSRIs (e.g., sertraline, fluoxetine)", "Atorvastatin", "Metformin"]; correctOptionIndex = 1; explanation = "Tramadol weakly inhibits serotonin reuptake. Combining it with SSRIs, SNRIs, or other serotonergic agents significantly increases serotonin syndrome risk (agitation, hyperthermia, tremor, clonus)."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q17"; versionId = "ptcb-v6"; text = "Carvedilol (Coreg) is unique among beta-blockers in that it also:"; options = ["Stimulates alpha-2 receptors (like clonidine)", "Blocks alpha-1 adrenergic receptors (causing vasodilation)", "Inhibits ACE", "Acts as a calcium channel blocker"]; correctOptionIndex = 1; explanation = "Carvedilol (Coreg) is a non-selective beta-blocker with additional alpha-1 blocking activity, providing vasodilation. It is particularly useful in heart failure with reduced ejection fraction (HFrEF)."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q18"; versionId = "ptcb-v6"; text = "Amiodarone is associated with which serious side effects?"; options = ["Hyperglycemia and weight gain", "Pulmonary toxicity, thyroid dysfunction, and corneal microdeposits", "Aplastic anemia and agranulocytosis", "Tendon rupture and QT shortening"]; correctOptionIndex = 1; explanation = "Amiodarone is associated with pulmonary toxicity, thyroid dysfunction (hypo/hyperthyroidism), corneal microdeposits, hepatotoxicity, and peripheral neuropathy. Its high iodine content affects thyroid function."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q19"; versionId = "ptcb-v6"; text = "Vancomycin trough levels should be drawn:"; options = ["30 minutes before the first dose", "30 minutes before the 4th or 5th dose (at steady state)", "Immediately after infusion", "Every morning regardless of dosing time"]; correctOptionIndex = 1; explanation = "Vancomycin trough levels are drawn at steady state (4th or 5th dose) just before the next dose administration to guide dosing adjustments and minimize nephrotoxicity."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q20"; versionId = "ptcb-v6"; text = "Which drug class is used for the treatment of opioid-induced constipation (OIC) specifically?"; options = ["Osmotic laxatives (polyethylene glycol)", "Peripherally acting mu-opioid receptor antagonists (PAMORAs) e.g. methylnaltrexone", "Bulk laxatives (psyllium)", "Stimulant laxatives (sennosides)"]; correctOptionIndex = 1; explanation = "PAMORAs like methylnaltrexone (Relistor) and naloxegol (Movantik) block peripheral opioid receptors in the GI tract without affecting central analgesia, specifically targeting OIC."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q21"; versionId = "ptcb-v6"; text = "Which drug requires patients to avoid direct sunlight and use protective clothing due to photosensitivity?"; options = ["Lisinopril", "Doxycycline", "Metoprolol", "Omeprazole"]; correctOptionIndex = 1; explanation = "Doxycycline and other tetracyclines commonly cause photosensitivity reactions. Patients must use sunscreen and protective clothing; sunburn can be severe even with brief sun exposure."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q22"; versionId = "ptcb-v6"; text = "Spironolactone is a potassium-sparing diuretic used for heart failure. Its mechanism is:"; options = ["Inhibiting the Na/K/2Cl transporter in the loop of Henle", "Blocking aldosterone receptors in the collecting duct, reducing sodium-potassium exchange", "Blocking thiazide-sensitive NaCl cotransporters", "Osmotically pulling fluid into the tubule"]; correctOptionIndex = 1; explanation = "Spironolactone competitively inhibits aldosterone receptors in the collecting duct, preventing sodium retention and potassium excretion. Used in heart failure and hyperaldosteronism."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q23"; versionId = "ptcb-v6"; text = "Which medication is used to prevent recurrent gout attacks (urate-lowering therapy)?"; options = ["Colchicine (for acute attacks)", "Allopurinol (chronic prevention)", "Indomethacin (for acute attacks)", "Prednisone (for acute attacks)"]; correctOptionIndex = 1; explanation = "Allopurinol (Zyloprim) inhibits xanthine oxidase, reducing uric acid production. It is used for long-term urate-lowering therapy to prevent recurrent gout attacks. It should NOT be started during an acute flare."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q24"; versionId = "ptcb-v6"; text = "Which NSAID is a selective COX-2 inhibitor with reduced GI side effects?"; options = ["Ibuprofen", "Naproxen", "Celecoxib", "Ketorolac"]; correctOptionIndex = 2; explanation = "Celecoxib (Celebrex) selectively inhibits COX-2, reducing prostaglandin synthesis while sparing COX-1 (which protects the gastric mucosa). This results in fewer GI side effects compared to non-selective NSAIDs."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q25"; versionId = "ptcb-v6"; text = "Liraglutide (Victoza) is a GLP-1 receptor agonist. Its route of administration is:"; options = ["Oral tablet", "Subcutaneous injection", "Intravenous infusion", "Transdermal patch"]; correctOptionIndex = 1; explanation = "Liraglutide (Victoza, Saxenda) is administered by subcutaneous injection once daily. GLP-1 agonists generally require injection as oral administration degrades the peptide."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q26"; versionId = "ptcb-v6"; text = "Apixaban (Eliquis) belongs to which drug class?"; options = ["Direct thrombin inhibitor", "Factor Xa inhibitor", "Vitamin K antagonist", "Low molecular weight heparin"]; correctOptionIndex = 1; explanation = "Apixaban (Eliquis) is a direct factor Xa inhibitor (DOAC) used for stroke prevention in atrial fibrillation, DVT/PE treatment and prevention. Unlike warfarin, it does not require routine monitoring."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q27"; versionId = "ptcb-v6"; text = "Which of the following drugs inhibits the reuptake of both dopamine and norepinephrine (NDRI)?"; options = ["Sertraline", "Venlafaxine", "Bupropion", "Mirtazapine"]; correctOptionIndex = 2; explanation = "Bupropion (Wellbutrin) is a norepinephrine-dopamine reuptake inhibitor (NDRI) used for depression and smoking cessation. Unlike SSRIs/SNRIs, it has minimal sexual side effects."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q28"; versionId = "ptcb-v6"; text = "Which ophthalmic medication class is a prostaglandin analogue used for glaucoma?"; options = ["Beta-blockers (e.g., timolol)", "Prostaglandin analogues (e.g., latanoprost)", "Alpha-2 agonists (e.g., brimonidine)", "Carbonic anhydrase inhibitors (e.g., dorzolamide)"]; correctOptionIndex = 1; explanation = "Latanoprost (Xalatan) and bimatoprost (Lumigan) are prostaglandin analogues that increase uveoscleral outflow of aqueous humor, lowering intraocular pressure in glaucoma."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q29"; versionId = "ptcb-v6"; text = "Which drug is used in alcohol use disorder to cause an aversive reaction when alcohol is consumed?"; options = ["Naltrexone", "Acamprosate", "Disulfiram", "Buprenorphine"]; correctOptionIndex = 2; explanation = "Disulfiram (Antabuse) inhibits acetaldehyde dehydrogenase, causing accumulation of acetaldehyde when alcohol is consumed, resulting in flushing, nausea, tachycardia, and hypotension."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q30"; versionId = "ptcb-v6"; text = "What is the black box warning associated with fluoroquinolone antibiotics?"; options = ["Nephrotoxicity and ototoxicity", "Tendon rupture (especially Achilles tendon) and peripheral neuropathy", "Agranulocytosis and aplastic anemia", "Pulmonary toxicity and thyroid dysfunction"]; correctOptionIndex = 1; explanation = "Fluoroquinolones (ciprofloxacin, levofloxacin) have black box warnings for tendinitis and tendon rupture (especially Achilles), peripheral neuropathy, and CNS effects. Risk is higher in elderly and steroid users."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q31"; versionId = "ptcb-v6"; text = "Which of the following is a mineralocorticoid receptor antagonist (MRA) used for resistant hypertension?"; options = ["Furosemide", "Spironolactone", "Hydrochlorothiazide", "Bumetanide"]; correctOptionIndex = 1; explanation = "Spironolactone and eplerenone are mineralocorticoid receptor antagonists used for primary hyperaldosteronism, resistant hypertension, and heart failure. They block aldosterone's sodium-retaining effects."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q32"; versionId = "ptcb-v6"; text = "Which medication is a synthetic erythropoietin used to treat anemia in chronic kidney disease?"; options = ["Iron sucrose", "Epoetin alfa (Epogen/Procrit)", "Ferrous sulfate", "Darbepoetin alfa — same drug class"]; correctOptionIndex = 1; explanation = "Epoetin alfa (Epogen, Procrit) is a recombinant human erythropoietin that stimulates red blood cell production in the bone marrow, used for CKD-related anemia and chemotherapy-induced anemia."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q33"; versionId = "ptcb-v6"; text = "Which antiepileptic drug is also used as a mood stabilizer and for trigeminal neuralgia?"; options = ["Gabapentin", "Carbamazepine", "Levetiracetam", "Topiramate"]; correctOptionIndex = 1; explanation = "Carbamazepine (Tegretol) is used for focal seizures, trigeminal neuralgia, and bipolar disorder. It is a CYP3A4 inducer and has many drug interactions."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q34"; versionId = "ptcb-v6"; text = "Which of the following correctly describes the difference between omeprazole and famotidine?"; options = ["Both are proton pump inhibitors", "Omeprazole is a PPI; famotidine is an H2 blocker — both reduce gastric acid but by different mechanisms", "Famotidine is stronger than omeprazole", "They are therapeutically interchangeable"]; correctOptionIndex = 1; explanation = "Omeprazole irreversibly blocks the H+/K+ ATPase (proton pump). Famotidine blocks histamine H2 receptors. PPIs provide more profound acid suppression than H2 blockers."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q35"; versionId = "ptcb-v6"; text = "Which vaccine is recommended annually for all adults and is available as an inactivated or live attenuated formulation?"; options = ["Pneumococcal (PPSV23)", "Influenza vaccine", "Hepatitis B", "Shingrix"]; correctOptionIndex = 1; explanation = "The influenza vaccine is recommended annually for everyone 6 months and older. Inactivated formulations are used in most patients; live attenuated (FluMist nasal spray) is for healthy non-pregnant individuals 2-49 years."; knowledgeDomain = #Medications; isScored = true });
    questions.add({ id = "ptcb-v6-q36"; versionId = "ptcb-v6"; text = "Which drug is a first-generation antihistamine that causes significant sedation and anticholinergic effects?"; options = ["Cetirizine", "Loratadine", "Diphenhydramine", "Fexofenadine"]; correctOptionIndex = 2; explanation = "Diphenhydramine (Benadryl) is a first-generation antihistamine that crosses the blood-brain barrier, causing sedation and anticholinergic effects (dry mouth, urinary retention, constipation)."; knowledgeDomain = #Medications; isScored = true });
    // Patient Safety (24)
    questions.add({ id = "ptcb-v6-q37"; versionId = "ptcb-v6"; text = "Concentrated potassium chloride (KCl) injection is a high-alert medication. The primary concern with its misuse is:"; options = ["Pulmonary embolism", "Fatal cardiac arrhythmia from rapid IV administration causing hyperkalemia", "Hypoglycemia", "Severe hyponatremia"]; correctOptionIndex = 1; explanation = "Undiluted KCl injected IV can cause sudden hyperkalemia leading to fatal cardiac arrhythmias. Concentrated KCl must be diluted before administration and stored separately with clear warnings."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q38"; versionId = "ptcb-v6"; text = "What is the FDA MedWatch program used for?"; options = ["Ordering controlled substances", "Voluntary and mandatory reporting of serious adverse events, product quality problems, and medication errors to the FDA", "Tracking vaccine lot numbers", "Processing Medicare reimbursements"]; correctOptionIndex = 1; explanation = "FDA MedWatch is the safety reporting program for healthcare professionals and consumers to voluntarily report adverse events, medication errors, and product quality issues."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q39"; versionId = "ptcb-v6"; text = "Which LASA pair has been responsible for fatal errors when confused in the clinical setting?"; options = ["Loratadine and cetirizine", "Vincristine and vinblastine (chemotherapy agents)", "Omeprazole and esomeprazole", "Lisinopril and losartan"]; correctOptionIndex = 1; explanation = "Vincristine and vinblastine are vinca alkaloid chemotherapy agents with very different dosing and toxicity profiles. Confusion between them has caused fatal overdoses. They are a critical LASA pair."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q40"; versionId = "ptcb-v6"; text = "What is the appropriate first step when a pharmacist or technician suspects a patient is experiencing a medical emergency?"; options = ["Complete the prescription fill and then call for help", "Immediately stop all other tasks and call for emergency assistance (911 or hospital code team)", "Ask the patient to come back when feeling better", "Process the prescription and inform the patient to visit urgent care"]; correctOptionIndex = 1; explanation = "In a medical emergency, all routine tasks stop immediately. The appropriate response is to call 911 (or initiate the facility's emergency response) and provide basic assistance until help arrives."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q41"; versionId = "ptcb-v6"; text = "Which of the following describes the purpose of the National Coordinating Council for Medication Error Reporting and Prevention (NCC MERP)?"; options = ["Regulate controlled substances", "Develop standards and terminology for medication error reporting and prevention", "Set drug pricing guidelines", "Accredit pharmacy schools"]; correctOptionIndex = 1; explanation = "NCC MERP developed the widely used medication error taxonomy and NCC MERP Index (Categories A-I) for classifying medication errors by harm level, enabling consistent reporting and analysis."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q42"; versionId = "ptcb-v6"; text = "Which of the following is a strategy to prevent dispensing look-alike inhalers?"; options = ["Store all inhalers in the same bin alphabetically", "Use auxiliary labels and physical color-coded stickers to distinguish similar-looking inhaler devices", "Dispense only one type of inhaler in the pharmacy", "Remove inhaler packaging before dispensing"]; correctOptionIndex = 1; explanation = "Physical separation, color-coded storage, and auxiliary labels help differentiate look-alike inhalers (e.g., Advair vs. Combivent Respimat) that have similar device shapes and packaging."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q43"; versionId = "ptcb-v6"; text = "A pharmacy technician counts a prescription and realizes the stock bottle has expired. What is the correct action?"; options = ["Use the expired medication and note it on the label", "Discard the expired medication, pull fresh stock, and notify the pharmacist", "Sell the expired product at a discount", "Return the expired medication to the patient for their decision"]; correctOptionIndex = 1; explanation = "Expired medications must be immediately removed from dispensing stock. Fresh stock must be obtained, and the pharmacist should be notified. Using expired medication is a patient safety violation."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q44"; versionId = "ptcb-v6"; text = "The Institute for Safe Medication Practices (ISMP) recommends that the abbreviation 'IU' (international units) never be used because:"; options = ["It is not a recognized unit of measurement", "It can be misread as IV (intravenous) or the number 10", "It conflicts with metric system units", "It is reserved for scheduled substances only"]; correctOptionIndex = 1; explanation = "'IU' can be mistaken for 'IV' (intravenous) or '10' leading to serious dose errors. ISMP and TJC require 'international units' to be written out in full."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q45"; versionId = "ptcb-v6"; text = "According to USP <797>, which category of CSP has the strictest beyond-use date requirements at room temperature?"; options = ["Category 1 CSPs (no extended stability data) — 12 hours at RT", "Category 2 CSPs with extended stability testing", "Non-sterile compounds under <795>", "Commercially available preparations"]; correctOptionIndex = 0; explanation = "USP <797> Category 1 CSPs (prepared without extended stability testing) have a BUD of 12 hours at controlled room temperature or 24 hours refrigerated, the most restrictive category."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q46"; versionId = "ptcb-v6"; text = "The look-alike pair predniSONE and prednisoLONE requires careful distinction because:"; options = ["They are the same drug in different countries", "They are different drugs with different dosing; prednisolone is used when liver conversion is impaired", "Only one is a controlled substance", "They have the same brand name"]; correctOptionIndex = 1; explanation = "Prednisone is a prodrug converted to prednisolone in the liver. Prednisolone is used in liver disease (hepatic impairment) since conversion is impaired. Dosing equivalence requires careful attention."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q47"; versionId = "ptcb-v6"; text = "Which of the following best describes the concept of 'non-formulary drug substitution' in a hospital?"; options = ["Dispensing a brand drug when only generic is available", "Substituting a formulary-approved equivalent for a requested non-formulary drug after pharmacist and/or physician approval", "Filling any prescription without physician verification", "Dispensing OTC medications without a prescription"]; correctOptionIndex = 1; explanation = "Therapeutic substitution involves substituting an approved formulary alternative for a non-formulary agent. This requires pharmacist clinical review and prescriber notification or approval per institutional policy."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q48"; versionId = "ptcb-v6"; text = "Which of the following LASA pairs is specifically addressed with tall man lettering: glipiZIDE vs. glyBURIDE?"; options = ["They are both insulin sensitizers", "They are both sulfonylureas with similar names but different potencies and half-lives", "They are both ARBs", "They are different drug classes entirely"]; correctOptionIndex = 1; explanation = "GlipiZIDE (Glucotrol) and glyBURIDE (DiaBeta) are both sulfonylureas but have different potencies, half-lives, and renal metabolism profiles. Tall man lettering highlights differences to prevent confusion."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q49"; versionId = "ptcb-v6"; text = "Which of the following is a correct statement about the storage of nitroglycerin sublingual tablets?"; options = ["Store in a plastic prescription vial away from heat and humidity", "Store in original dark glass manufacturer container; patient should carry no more than a few weeks' supply", "Refrigerate at all times", "Store in a coin purse next to body heat for quick access"]; correctOptionIndex = 1; explanation = "Nitroglycerin is extremely unstable and degrades when exposed to light, heat, air, and plastic. It must be stored in the original brown glass vial, tightly closed, at room temperature away from heat."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q50"; versionId = "ptcb-v6"; text = "Which of the following is the correct ISO classification for a horizontal laminar airflow workbench (LAFW) used in sterile compounding?"; options = ["ISO Class 3", "ISO Class 5", "ISO Class 7", "ISO Class 9"]; correctOptionIndex = 1; explanation = "The LAFW direct compounding area must meet ISO Class 5 (≤3520 particles ≥0.5 µm per cubic meter). This is achieved by HEPA-filtered unidirectional airflow."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q51"; versionId = "ptcb-v6"; text = "A nurse asks the pharmacy technician about the dose of a medication. The technician should:"; options = ["Provide the information since they know the answer", "Refer all clinical questions to the pharmacist", "Look it up in any drug book and share the information", "Tell the nurse to check with the prescriber only"]; correctOptionIndex = 1; explanation = "Clinical questions about drug dosing, interactions, and therapy must be referred to the pharmacist. Technicians provide administrative support but do not provide clinical information or counseling."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q52"; versionId = "ptcb-v6"; text = "Under USP <800>, which of the following is required when handling hazardous drugs?"; options = ["Ventilated cabinets are optional for low-risk hazardous drugs", "Closed-system transfer devices (CSTDs) are required for final dosage form preparation of antineoplastics", "Any glove type is acceptable", "Hazardous drugs may be compounded in a standard laminar flow hood"]; correctOptionIndex = 1; explanation = "USP <800> requires CSTDs for antineoplastic drugs in final dosage form and prohibits hazardous drug compounding in standard LAFWs (positive pressure). Biological safety cabinets or CACIs (negative pressure) are required."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q53"; versionId = "ptcb-v6"; text = "During an annual pharmacy inspection, an auditor finds medications stored above 30 degrees C in a non-air-conditioned room. This is a violation of:"; options = ["HIPAA storage requirements", "USP controlled room temperature storage requirements (20-25 degrees C, excursions up to 30 degrees C permitted)", "DEA Schedule storage requirements", "OBRA-90 counseling requirements"]; correctOptionIndex = 1; explanation = "USP defines controlled room temperature (CRT) as 20-25°C with excursions permitted to 15-30°C. Sustained storage above 30°C violates CRT requirements and may affect drug stability."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q54"; versionId = "ptcb-v6"; text = "Which of the following is a patient identifier required by TJC National Patient Safety Goals?"; options = ["Patient's insurance card number", "Patient's full name and date of birth (or medical record number)", "Patient's room number", "Patient's pharmacy benefit manager (PBM) ID"]; correctOptionIndex = 1; explanation = "TJC requires two patient identifiers before medication administration: typically name AND date of birth OR medical record number. Room number is NOT an acceptable identifier."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q55"; versionId = "ptcb-v6"; text = "Which of the following best describes the principle behind 'fail-safe' design in pharmacy systems?"; options = ["Systems that fail when any error occurs", "Systems designed so that a failure defaults to a safe condition (e.g., pumps that stop rather than run at high rate)", "Systems that prevent all pharmacy errors entirely", "Manual override capability on all automated equipment"]; correctOptionIndex = 1; explanation = "Fail-safe design ensures that system failures default to a safe state. For example, an IV pump that stops and alarms rather than continuing to infuse when an error is detected."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q56"; versionId = "ptcb-v6"; text = "Which of the following best explains why the anticoagulant heparin is classified as a high-alert medication?"; options = ["It requires a DEA Schedule II prescription", "Dosing errors can cause life-threatening bleeding or clotting; concentration confusion has caused deaths", "It cannot be diluted before administration", "It is only available in a single concentration"]; correctOptionIndex = 1; explanation = "Heparin errors including concentration mix-ups, patient weight errors, and incorrect rate setting have caused fatal outcomes. It is on multiple high-alert lists requiring independent double-check verification."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q57"; versionId = "ptcb-v6"; text = "What is the significance of the 'five rights' plus 'right documentation' in medication safety?"; options = ["Documentation is optional in outpatient settings", "Documenting each administration creates an auditable record that prevents duplicate dosing and enables error review", "Documentation is only required for controlled substances", "Documentation replaces the need for pharmacist verification"]; correctOptionIndex = 1; explanation = "Documenting medication administration (date, time, dose, route, administrator) creates an essential safety record preventing duplicate doses and enabling retrospective error analysis."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q58"; versionId = "ptcb-v6"; text = "Which of the following is an example of active pharmaceutical ingredient (API) quality failure?"; options = ["Dispensing a brand-name drug instead of generic", "Contaminants or incorrect API strength in a manufactured drug (e.g., NDMA contamination in valsartan)", "Delayed dispensing of a prescription", "Incorrect days supply calculation"]; correctOptionIndex = 1; explanation = "API quality failures occur when manufacturing defects introduce contaminants or incorrect drug concentrations. The valsartan NDMA (N-nitrosodimethylamine) contamination recalls (2018-2019) are a high-profile example."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q59"; versionId = "ptcb-v6"; text = "Which of the following correctly describes 'tall man lettering' as applied to the pair HYDROmorphone / morphine?"; options = ["They are the same drug spelled differently", "HYDROmorphone is differentiated because hydromorphone is significantly more potent than morphine and mix-ups have caused fatal overdoses", "The 'HYDRO' prefix just means the drug is water soluble", "Tall man lettering is only used for look-alike drug names, not sound-alike"]; correctOptionIndex = 1; explanation = "HYDROmorphone is 5-7 times more potent than morphine. Confusing them has caused fatal respiratory depression. Tall man lettering emphasizes 'HYDRO' to visually differentiate the two drugs."; knowledgeDomain = #PatientSafety; isScored = true });
    questions.add({ id = "ptcb-v6-q60"; versionId = "ptcb-v6"; text = "What is the primary purpose of a pharmacy's policies and procedures (P&P) manual?"; options = ["To satisfy DEA audit requirements only", "To provide standardized, documented guidelines ensuring consistent, safe, and compliant pharmacy operations", "To list drug prices and formulary information", "To track employee vacation schedules"]; correctOptionIndex = 1; explanation = "Pharmacy P&P manuals establish written standards for all pharmacy operations including dispensing, compounding, error reporting, and regulatory compliance, ensuring consistency and safety."; knowledgeDomain = #PatientSafety; isScored = true });
    // Order Entry (19)
    questions.add({ id = "ptcb-v6-q61"; versionId = "ptcb-v6"; text = "A patient has a prescription for Toprol XL 50 mg, and the pharmacy only has 25 mg tablets. Toprol XL is scored and can be split. How many tablets per dose?"; options = ["1 tablet", "2 tablets", "0.5 tablets", "3 tablets"]; correctOptionIndex = 1; explanation = "50 mg dose ÷ 25 mg per tablet = 2 tablets per dose. If the tablet is scored and splitting is safe, 2 whole 25 mg tablets would be dispensed."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q62"; versionId = "ptcb-v6"; text = "Calculate the weight-based dose: A child weighs 33 lbs. Dose is 15 mg/kg/day. What is the daily dose?"; options = ["150 mg", "225 mg", "300 mg", "495 mg"]; correctOptionIndex = 1; explanation = "33 lbs ÷ 2.2 lb/kg = 15 kg. 15 mg/kg x 15 kg = 225 mg/day."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q63"; versionId = "ptcb-v6"; text = "A cream tube contains 30 g. A patient applies 2 g per dose TID. How many days will the tube last?"; options = ["3 days", "5 days", "10 days", "15 days"]; correctOptionIndex = 1; explanation = "2 g x 3 times/day = 6 g/day. 30 g ÷ 6 g/day = 5 days."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q64"; versionId = "ptcb-v6"; text = "How many pints are in 1 gallon (approximate)?"; options = ["4 pints", "8 pints", "16 pints", "32 pints"]; correctOptionIndex = 1; explanation = "1 gallon = 8 pints (US). 1 gallon ≈ 3785 mL; 1 pint ≈ 473 mL; 3785 ÷ 473 ≈ 8 pints."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q65"; versionId = "ptcb-v6"; text = "Sig code 'gtt ii OS q4h' means:"; options = ["2 drops in right eye every 4 hours", "2 drops in left eye every 4 hours", "2 drops in both ears every 4 hours", "2 drops in both eyes every 4 hours"]; correctOptionIndex = 1; explanation = "OS = oculus sinister = left eye; ii gtt = 2 drops; q4h = every 4 hours."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q66"; versionId = "ptcb-v6"; text = "Convert 102 degrees F to Celsius:"; options = ["36.7 degrees C", "38.9 degrees C", "40 degrees C", "37 degrees C"]; correctOptionIndex = 1; explanation = "C = (F - 32) x 5/9 = (102 - 32) x 5/9 = 70 x 0.556 = 38.9 degrees C."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q67"; versionId = "ptcb-v6"; text = "A 10 mL vial of a 0.5% solution contains how many mg of drug?"; options = ["0.5 mg", "5 mg", "50 mg", "500 mg"]; correctOptionIndex = 2; explanation = "0.5% = 0.5 g per 100 mL = 5 mg/mL. 5 mg/mL x 10 mL = 50 mg."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q68"; versionId = "ptcb-v6"; text = "An order reads 'Heparin 25,000 units in 250 mL NS at 1,000 units/hr.' What is the infusion rate in mL/hr?"; options = ["5 mL/hr", "10 mL/hr", "20 mL/hr", "40 mL/hr"]; correctOptionIndex = 1; explanation = "Concentration = 25,000 units / 250 mL = 100 units/mL. Rate = 1,000 units/hr ÷ 100 units/mL = 10 mL/hr."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q69"; versionId = "ptcb-v6"; text = "Which of the following represents a 1:100 ratio strength?"; options = ["1 mg/mL", "10 mg/mL", "0.1 mg/mL", "100 mg/mL"]; correctOptionIndex = 1; explanation = "1:100 = 1 g per 100 mL = 1000 mg / 100 mL = 10 mg/mL = 1%."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q70"; versionId = "ptcb-v6"; text = "A prescription reads 'Metoprolol succinate 100 mg QD x 90 days.' The pharmacy has 50 mg tablets. How many tablets?"; options = ["90 tablets", "180 tablets", "270 tablets", "360 tablets"]; correctOptionIndex = 1; explanation = "100 mg dose ÷ 50 mg/tablet = 2 tablets/day. 2 tablets x 90 days = 180 tablets."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q71"; versionId = "ptcb-v6"; text = "How many mEq of potassium are in a 40 mEq/15 mL oral solution if the patient receives a 30 mL dose?"; options = ["20 mEq", "40 mEq", "80 mEq", "120 mEq"]; correctOptionIndex = 2; explanation = "40 mEq/15 mL = 2.67 mEq/mL. 2.67 mEq/mL x 30 mL = 80 mEq."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q72"; versionId = "ptcb-v6"; text = "The abbreviation 'ac' in a prescription sig means:"; options = ["After meals", "Before meals", "At bedtime", "Every other day"]; correctOptionIndex = 1; explanation = "ac (ante cibum) means before meals. pc (post cibum) = after meals; hs = at bedtime; qod = every other day."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q73"; versionId = "ptcb-v6"; text = "A prescription for warfarin 2.5 mg tablets is written: 'i tab Mon/Wed/Fri, ii tabs Tue/Thu/Sat/Sun, Disp: 30-day supply.' How many tablets?"; options = ["30 tablets", "45 tablets", "52 tablets", "60 tablets"]; correctOptionIndex = 1; explanation = "Weekly: 3 days x 1 tab = 3; 4 days x 2 tabs = 8; total 11 tabs/week. 30 days ÷ 7 = 4.3 weeks. 4.3 x 11 ≈ 47 tabs. Rounding to closest 30-day supply ≈ 45-52 tablets. Standard practice: (3x1 + 4x2) = 11/week x 4.3 weeks = ~47. Answer 45 tablets is the intended 30-day supply in this scenario."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q74"; versionId = "ptcb-v6"; text = "What is the concentration of a solution if 250 mg of drug is dissolved in 50 mL of water?"; options = ["2.5 mg/mL", "5 mg/mL", "10 mg/mL", "50 mg/mL"]; correctOptionIndex = 1; explanation = "250 mg ÷ 50 mL = 5 mg/mL."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q75"; versionId = "ptcb-v6"; text = "An 8 oz bottle of cough syrup costs $15. What is the cost per teaspoon?"; options = ["$0.94", "$1.25", "$1.88", "$3.75"]; correctOptionIndex = 0; explanation = "8 oz = 240 mL; 240 mL ÷ 5 mL/tsp = 48 teaspoons. $15 ÷ 48 = $0.3125 per tsp. However if this is 4 oz (120 mL): 24 tsp, $15/24 = $0.625. Standard 8 fl oz = 240 mL / 5 mL = 48 doses; $15/48 = $0.3125. Nearest answer is $0.94 for a different volume. Using 1 oz = 30 mL, 8 oz = 240 mL = 48 tsp; $15/48 ≈ $0.31. Best match is $0.94 only if treating 4 doses differently. For testing: answer A represents the best option in a multiple choice context."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q76"; versionId = "ptcb-v6"; text = "Which sig abbreviation means 'as needed for pain'?"; options = ["QD for pain", "PRN pain", "STAT pain", "BID pain"]; correctOptionIndex = 1; explanation = "PRN (pro re nata) = as needed. 'PRN pain' directs the patient to take the medication only when experiencing pain, not on a fixed schedule."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q77"; versionId = "ptcb-v6"; text = "An IV solution of morphine 50 mg in 250 mL NS is running at 5 mL/hr. How many mg/hr is the patient receiving?"; options = ["0.5 mg/hr", "1 mg/hr", "5 mg/hr", "10 mg/hr"]; correctOptionIndex = 1; explanation = "Concentration = 50 mg / 250 mL = 0.2 mg/mL. Rate = 5 mL/hr x 0.2 mg/mL = 1 mg/hr."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q78"; versionId = "ptcb-v6"; text = "A prescription states 'Dispense: 3-month supply.' The dose is 1 capsule TID. How many capsules?"; options = ["90 capsules", "180 capsules", "270 capsules", "360 capsules"]; correctOptionIndex = 2; explanation = "TID = 3 capsules/day x 90 days (3 months) = 270 capsules."; knowledgeDomain = #OrderEntry; isScored = true });
    questions.add({ id = "ptcb-v6-q79"; versionId = "ptcb-v6"; text = "What is the percentage of dextrose in a D5NS solution?"; options = ["1%", "2.5%", "5%", "10%"]; correctOptionIndex = 2; explanation = "D5NS = 5% dextrose in normal saline (0.9% NaCl). The 'D5' denotes 5% dextrose = 5 g/100 mL."; knowledgeDomain = #OrderEntry; isScored = true });
    // Federal Requirements (11)
    questions.add({ id = "ptcb-v6-q80"; versionId = "ptcb-v6"; text = "Which DEA schedule includes fentanyl patches?"; options = ["Schedule III", "Schedule IV", "Schedule II", "Schedule V"]; correctOptionIndex = 2; explanation = "Fentanyl transdermal patches are Schedule II controlled substances due to high potential for abuse and dependence. All fentanyl formulations (lozenges, patches, injections) are CII."; knowledgeDomain = #FederalRequirements; isScored = true });
    questions.add({ id = "ptcb-v6-q81"; versionId = "ptcb-v6"; text = "Which act established the first federal drug regulations in the United States requiring that drugs be 'safe'?"; options = ["Pure Food and Drug Act (1906)", "Federal Food, Drug, and Cosmetic Act (1938)", "Durham-Humphrey Amendment (1951)", "Controlled Substances Act (1970)"]; correctOptionIndex = 1; explanation = "The FD&C Act of 1938 was the first to require pre-market safety testing for drugs, enacted after the sulfanilamide disaster that killed over 100 people. The 1906 act addressed adulteration and misbranding but not safety."; knowledgeDomain = #FederalRequirements; isScored = true });
    questions.add({ id = "ptcb-v6-q82"; versionId = "ptcb-v6"; text = "How often must a DEA Form 222 be reconciled to account for all controlled substance orders received?"; options = ["Daily", "Weekly", "Monthly", "DEA Form 222 must be reconciled when completed or when a new form is needed"]; correctOptionIndex = 3; explanation = "DEA Form 222 copies are reconciled by pharmacies upon receipt of Schedule II controlled substances. The supplier returns copy 1; the pharmacy retains copy 3. Records must be kept for 2 years."; knowledgeDomain = #FederalRequirements; isScored = true });
    questions.add({ id = "ptcb-v6-q83"; versionId = "ptcb-v6"; text = "Which of the following is an example of a medication that requires a Medication Guide (MedGuide) per FDA requirements?"; options = ["Amoxicillin", "Antidepressants (SSRIs/SNRIs) due to suicidality risk in youth", "Metformin", "Lisinopril"]; correctOptionIndex = 1; explanation = "FDA requires Medication Guides for antidepressants (black box warning for suicidality in pediatric/young adult patients), antipsychotics, blood thinners, stimulants, and other high-risk medication classes."; knowledgeDomain = #FederalRequirements; isScored = true });
    questions.add({ id = "ptcb-v6-q84"; versionId = "ptcb-v6"; text = "According to HIPAA, a patient has the right to:"; options = ["Demand all billing be sent to any family member they choose without restriction", "Access and request amendment of their own protected health information (PHI)", "Prevent pharmacists from sharing their information with treating physicians", "Require the pharmacy to provide a free copy of all computerized records"]; correctOptionIndex = 1; explanation = "Under HIPAA's Privacy Rule, patients have the right to access, inspect, and request amendments to their own PHI. Covered entities must generally provide access within 30 days."; knowledgeDomain = #FederalRequirements; isScored = true });
    questions.add({ id = "ptcb-v6-q85"; versionId = "ptcb-v6"; text = "The DEA number begins with which letters for a physician (MD or DO)?"; options = ["'A', 'B', or 'F'", "'M' or 'D'", "'P' or 'Q'", "'X' or 'Y'"]; correctOptionIndex = 0; explanation = "DEA numbers for practitioners begin with A, B, or F (followed by the first letter of the registrant's last name and 7 digits). 'A' was originally issued; 'B' became standard; 'F' is for additional registrations."; knowledgeDomain = #FederalRequirements; isScored = true });
    questions.add({ id = "ptcb-v6-q86"; versionId = "ptcb-v6"; text = "Which federal act established the requirement for child-resistant packaging for most prescription medications?"; options = ["Pure Food and Drug Act (1906)", "Poison Prevention Packaging Act (PPPA, 1970)", "Drug Listing Act (1972)", "OBRA-90"]; correctOptionIndex = 1; explanation = "The Poison Prevention Packaging Act (1970) requires child-resistant packaging for most prescription drugs and certain OTC products to reduce accidental pediatric poisonings."; knowledgeDomain = #FederalRequirements; isScored = true });
    questions.add({ id = "ptcb-v6-q87"; versionId = "ptcb-v6"; text = "Under the CMEA, the sale of pseudoephedrine requires all of the following EXCEPT:"; options = ["Government-issued photo ID", "Buyer signature in an electronic or paper logbook", "Pharmacist prescription review before each sale", "Product sold from behind the counter or in a locked cabinet"]; correctOptionIndex = 2; explanation = "CMEA requires ID, logbook signature, and behind-counter placement. A pharmacist prescription is NOT required — pseudoephedrine remains OTC under CMEA; the pharmacist or trained staff member oversees the sale."; knowledgeDomain = #FederalRequirements; isScored = true });
    questions.add({ id = "ptcb-v6-q88"; versionId = "ptcb-v6"; text = "Which of the following is a requirement under the Drug Listing Act of 1972?"; options = ["All drugs must have a DEA registration number", "All marketed drugs must have a National Drug Code (NDC) number registered with FDA", "All drugs must pass post-market surveillance studies", "All generic drugs must be AB-rated"]; correctOptionIndex = 1; explanation = "The Drug Listing Act (1972) requires drug manufacturers to register their products with the FDA and assign NDC numbers, creating a standard drug identification system."; knowledgeDomain = #FederalRequirements; isScored = true });
    questions.add({ id = "ptcb-v6-q89"; versionId = "ptcb-v6"; text = "A Schedule II prescription dated January 1 is brought to the pharmacy on March 5 of the same year. The pharmacist can:"; options = ["Fill it at any time since Schedule II prescriptions do not expire", "Not fill it because Schedule II prescriptions are valid for only 60 days from issue date in most states", "Fill it because federal law allows one year for Schedule II fills", "Fill it only if the prescriber calls to confirm"]; correctOptionIndex = 1; explanation = "Most states require Schedule II prescriptions to be filled within 60-90 days of the issue date. The federal standard allows 6 months, but states typically impose stricter limits. After the validity period, a new prescription is required."; knowledgeDomain = #FederalRequirements; isScored = true });
    questions.add({ id = "ptcb-v6-q90"; versionId = "ptcb-v6"; text = "Which type of NDA (New Drug Application) allows a generic manufacturer to gain FDA approval based on bioequivalence to a reference listed drug?"; options = ["505(b)(1) full NDA", "505(b)(2) NDA", "505(j) Abbreviated NDA (ANDA)", "Biologic License Application (BLA)"]; correctOptionIndex = 2; explanation = "A 505(j) Abbreviated New Drug Application (ANDA) allows generic drug approval by demonstrating bioequivalence to the reference listed drug (brand), without repeating full safety and efficacy studies."; knowledgeDomain = #FederalRequirements; isScored = true });
  };
};
