import Types "../types/exams";
import List "mo:core/List";

module {
  public func seedV8(
    versions : List.List<Types.ExamVersion>,
    questions : List.List<Types.Question>
  ) : () {

    versions.add({ id = "ptcb-v8"; examId = "ptcb"; versionName = "Practice Test 8"; totalQuestions = 90; scoredQuestions = 80; timeLimitMinutes = 110 });

    // ── Medications (36) ──────────────────────────────────────────────────────

    questions.add({ id = "ptcb-v8-q1"; versionId = "ptcb-v8"; text = "Diltiazem (Cardizem) is a non-dihydropyridine calcium channel blocker. Compared to amlodipine, its clinical advantages include:"; options = ["Greater peripheral vasodilation with less cardiac conduction slowing", "Slowing of heart rate and AV nodal conduction, making it useful for rate control in atrial fibrillation and angina", "Being suitable as first-line for systolic heart failure", "Fewer drug interactions than amlodipine"]; correctOptionIndex = 1; explanation = "Non-dihydropyridine CCBs (diltiazem and verapamil) act on both vascular smooth muscle AND cardiac conduction tissue, slowing the sinus node and AV node. This makes them useful for rate control in atrial fibrillation and supraventricular tachycardias. They are contraindicated in HFrEF and with IV beta-blockers (risk of heart block)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q2"; versionId = "ptcb-v8"; text = "Verapamil (Calan) is contraindicated in combination with which drug class because of risk of complete heart block?"; options = ["ACE inhibitors", "IV beta-blockers or patients already on oral beta-blockers", "Loop diuretics", "Nitrates"]; correctOptionIndex = 1; explanation = "Verapamil (non-dihydropyridine CCB) combined with IV beta-blockers (or in patients already on oral beta-blockers) causes additive depression of sinoatrial and AV nodal conduction, potentially causing complete heart block, severe bradycardia, or cardiac arrest. This combination must be avoided."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q3"; versionId = "ptcb-v8"; text = "Enalapril (Vasotec) is an ACE inhibitor prodrug. It is converted to its active form by:"; options = ["Renal glucuronidation", "Hepatic esterases that convert enalapril to active enalaprilat", "First-pass hydrolysis in the gut", "CYP3A4 oxidation in the liver"]; correctOptionIndex = 1; explanation = "Enalapril is de-esterified in the liver by esterases to form enalaprilat, the active diacid ACE inhibitor. Lisinopril (the only ACE inhibitor that is not a prodrug) is active as administered and does not require metabolic conversion. This distinguishes lisinopril for patients with severe hepatic impairment."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q4"; versionId = "ptcb-v8"; text = "Quinapril (Accupril) is an ACE inhibitor. The class-wide adverse effect unique to ACE inhibitors (not shared by ARBs) is:"; options = ["First-dose hypotension", "Hyperkalemia", "Dry, non-productive cough due to bradykinin accumulation", "Renal impairment in bilateral renal artery stenosis"]; correctOptionIndex = 2; explanation = "ACE inhibitors prevent degradation of bradykinin by ACE. Accumulated bradykinin stimulates prostaglandin synthesis and airway inflammation, causing a dry, non-productive cough in 10-15% of patients (more common in Asian patients and women). ARBs do not inhibit ACE and do not cause this side effect, making them the substitute when cough is intolerable."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q5"; versionId = "ptcb-v8"; text = "Fosinopril (Monopril) is unique among ACE inhibitors because it is the only one with dual elimination pathways. This is clinically relevant for:"; options = ["Patients with drug allergies to other ACE inhibitors", "Patients with both renal and hepatic impairment — since fosinopril is eliminated by both liver and kidney, dose reduction may not be needed when one organ is impaired", "Patients requiring once-weekly dosing", "Patients who need IV formulations only"]; correctOptionIndex = 1; explanation = "Most ACE inhibitors are primarily renally eliminated. Fosinopril has dual hepatic AND renal elimination, meaning impairment of one pathway is compensated by the other. This makes fosinopril potentially safer in patients with concurrent renal and mild hepatic impairment without requiring as significant a dose adjustment."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q6"; versionId = "ptcb-v8"; text = "Trimethoprim-sulfamethoxazole (TMP-SMX / Bactrim) works by:"; options = ["Disrupting fungal cell membranes like azoles", "Sequential blockade of folate synthesis: sulfamethoxazole inhibits dihydropteroate synthase and trimethoprim inhibits dihydrofolate reductase, blocking bacterial folate production", "Inhibiting bacterial 30S ribosomal subunit like aminoglycosides", "Disrupting bacterial cell wall synthesis like beta-lactams"]; correctOptionIndex = 1; explanation = "TMP-SMX provides synergistic sequential blockade of bacterial folate synthesis (two-hit mechanism): sulfonamide blocks DHPS, trimethoprim blocks DHFR. Bacteria cannot synthesize purines without folate. Humans obtain folate from diet, so toxicity is selective for bacteria. Used for UTIs, PCP prophylaxis, MRSA skin infections, toxoplasmosis."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q7"; versionId = "ptcb-v8"; text = "Tetracyclines should be avoided in children under 8 years and in pregnant women because:"; options = ["They cause nephrotoxicity in young children", "They bind calcium in developing bones and teeth, causing permanent yellow-brown discoloration of teeth and inhibiting bone growth", "They cause congenital cardiac defects", "They are teratogenic due to antifolate effects"]; correctOptionIndex = 1; explanation = "Tetracyclines (doxycycline, minocycline, tetracycline) chelate calcium and incorporate into mineralizing structures (teeth and bones) of the developing fetus and children under 8, causing permanent brown discoloration of teeth (dental fluorosis-like) and potentially affecting bone growth. They are Category D in pregnancy."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q8"; versionId = "ptcb-v8"; text = "Minocycline (Minocin) has which unique advantage compared to other tetracyclines?"; options = ["It is the only tetracycline active against MRSA", "Better oral bioavailability (~100%) and penetration into tissues including CSF and saliva; more active against Staphylococcus aureus", "It has no drug interactions with dairy or antacids", "It can be safely used in children under 8 with no dental side effects"]; correctOptionIndex = 1; explanation = "Minocycline has better oral bioavailability (near 100%) and greater lipid solubility than other tetracyclines, allowing penetration into tissues including saliva (which aids in Neisseria meningitidis carrier eradication) and CSF. It has some MRSA activity. Like other tetracyclines, it should still be avoided in children under 8."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q9"; versionId = "ptcb-v8"; text = "Fluconazole is a potent CYP2C9 inhibitor. When a patient on warfarin starts fluconazole, the expected effect on warfarin is:"; options = ["INR decreases because fluconazole induces warfarin metabolism", "INR increases significantly because reduced CYP2C9 activity slows warfarin metabolism, causing drug accumulation and enhanced anticoagulation", "No significant effect on INR", "INR fluctuates randomly with no predictable pattern"]; correctOptionIndex = 1; explanation = "Warfarin S-enantiomer (the more potent anticoagulant form) is primarily metabolized by CYP2C9. Fluconazole is a potent CYP2C9 inhibitor that dramatically reduces warfarin metabolism, causing accumulation and INR elevation with significantly increased bleeding risk. Close INR monitoring and warfarin dose reduction are necessary."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q10"; versionId = "ptcb-v8"; text = "Which of the following correctly describes how HIV antiretrovirals are typically prescribed for treatment-naive patients?"; options = ["Single-agent monotherapy to reduce pill burden", "HAART (Highly Active Antiretroviral Therapy): a combination of at least 2-3 drugs from different classes to prevent resistance", "Sequential therapy starting with the weakest agent", "Treatment is deferred until CD4 count drops below 200 cells/mm3"]; correctOptionIndex = 1; explanation = "Current HIV guidelines recommend combination ART (cART or HAART) using at least 3 antiretroviral agents from 2 or more classes (typically 2 NRTIs + an INSTI or NNRTI or boosted PI). Combination prevents resistance emergence. Treatment is now recommended for ALL HIV-positive patients regardless of CD4 count."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q11"; versionId = "ptcb-v8"; text = "Cetirizine (Zyrtec) is a second-generation antihistamine that is preferred over first-generation antihistamines like diphenhydramine in most adults because:"; options = ["Cetirizine is more potent at H1 receptors", "Cetirizine has minimal CNS penetration due to poor lipophilicity and P-glycoprotein efflux, causing less sedation and fewer anticholinergic effects", "Cetirizine is only available by prescription", "Cetirizine lasts only 4 hours, so patients can sleep after the last dose"]; correctOptionIndex = 1; explanation = "Second-generation antihistamines (cetirizine, fexofenadine, loratadine) are preferred because they are less lipophilic and are actively excluded from the CNS by P-glycoprotein, causing much less sedation and virtually no anticholinergic effects compared to first-generation agents like diphenhydramine. Cetirizine provides 24-hour symptom control."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q12"; versionId = "ptcb-v8"; text = "Phenylephrine (Neo-Synephrine) is used as a nasal decongestant. How does it differ from pseudoephedrine?"; options = ["Phenylephrine is more potent systemically and has higher abuse potential", "Phenylephrine is an alpha-1 direct agonist with lower oral bioavailability (~38%); it is less effective than pseudoephedrine as an oral decongestant and is not a methamphetamine precursor", "Phenylephrine requires a prescription in all states", "They are pharmacologically identical with different brand names only"]; correctOptionIndex = 1; explanation = "Phenylephrine is a direct alpha-1 agonist. Unlike pseudoephedrine, it is not a precursor for methamphetamine synthesis and can be displayed on open shelves. However, oral phenylephrine has poor bioavailability (~38%) and some evidence questions its oral effectiveness at standard OTC doses. Pseudoephedrine remains more effective."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q13"; versionId = "ptcb-v8"; text = "Dextromethorphan (DXM) is an antitussive (cough suppressant). Its mechanism of action is:"; options = ["Blockade of mu-opioid receptors to suppress cough", "NMDA receptor antagonist and sigma receptor agonist that elevates cough threshold centrally; at high doses causes dissociative effects", "Stimulation of cough center depressant pathways via kappa-opioid receptors", "Local anesthetic effect on afferent cough nerve fibers"]; correctOptionIndex = 1; explanation = "Dextromethorphan is a non-opioid antitussive that suppresses the cough reflex via NMDA receptor antagonism and sigma receptor activity in the medullary cough center. It is structurally related to opioids but lacks analgesic activity or significant opioid receptor activity at therapeutic doses. Abuse potential exists at high doses (dissociative/hallucinogenic effects)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q14"; versionId = "ptcb-v8"; text = "Bisacodyl (Dulcolax) is a stimulant laxative available both orally and rectally. The rectal suppository works:"; options = ["More slowly than oral bisacodyl (6-8 hours)", "Within 15-60 minutes by directly stimulating rectal mucosal nerve endings and smooth muscle", "Only when the suppository dissolves in the lower intestine after 4 hours", "Identically to the oral form, just with different convenience"]; correctOptionIndex = 1; explanation = "Bisacodyl rectal suppositories work within 15-60 minutes by directly stimulating colonic and rectal mucosal sensory nerve endings, increasing motility and triggering defecation. Oral bisacodyl takes 6-12 hours to reach the colon. The rectal route is preferred when rapid laxation is needed (preoperative, acute constipation)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q15"; versionId = "ptcb-v8"; text = "Docusate sodium (Colace) is a stool softener. When is it most appropriately used?"; options = ["Acute severe constipation requiring immediate relief", "Prevention of straining during defecation in post-surgical, cardiac, obstetric, or elderly patients where Valsalva maneuver could be harmful", "As a primary treatment for opioid-induced constipation", "In patients with fecal impaction as first-line treatment"]; correctOptionIndex = 1; explanation = "Docusate acts as a surfactant (detergent), lowering surface tension of stool to allow water and fat penetration, softening stool without stimulating motility. It is used to PREVENT straining (Valsalva) in post-MI, post-surgical, postpartum, or hemorrhoid patients — not for acute constipation treatment. For opioid-induced constipation, stimulant laxatives (senna) are preferred."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q16"; versionId = "ptcb-v8"; text = "Senna (Senokot) is a stimulant laxative derived from plant anthraquinones. How long does it typically take for oral senna to produce a bowel movement?"; options = ["Within 15-30 minutes", "6-12 hours after oral ingestion", "24-48 hours minimum", "Onset is unpredictable and variable by several days"]; correctOptionIndex = 1; explanation = "Oral senna is converted by gut bacteria to active anthraquinone compounds that stimulate enteric nerve plexuses and increase colonic propulsive contractions. Because it requires bacterial metabolism, onset is 6-12 hours after oral administration. Senna is often prescribed with docusate for opioid-induced constipation."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q17"; versionId = "ptcb-v8"; text = "Aminoglycosides (gentamicin, tobramycin) exhibit concentration-dependent killing. The optimal dosing strategy to maximize efficacy while minimizing nephrotoxicity is:"; options = ["Frequent small doses every 4-6 hours to maintain consistent levels", "Extended-interval (once-daily) dosing: giving the full dose once daily achieves a high Cmax:MIC ratio for killing while the trough period limits tubular accumulation", "Continuous IV infusion at low concentration for 24 hours", "Oral dosing only to avoid intravenous toxicity"]; correctOptionIndex = 1; explanation = "Aminoglycosides kill bacteria in a concentration-dependent manner (higher Cmax = better killing) with a prolonged post-antibiotic effect. Once-daily extended-interval dosing delivers a high peak (maximizing concentration-dependent killing), achieves a trough period below the saturable tubular transport threshold (reducing nephrotoxicity accumulation), and simplifies monitoring."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q18"; versionId = "ptcb-v8"; text = "ACE inhibitors are absolutely contraindicated in patients with a history of angioedema from ACE inhibitors. This is because:"; options = ["ACE inhibitors permanently damage ACE enzyme function", "Prior angioedema reflects bradykinin-mediated vascular permeability; rechallenge causes recurrence and potentially fatal airway angioedema", "Allergic antibodies formed during first exposure attack ACE enzyme on rechallenge", "Angioedema risk is only present with the first dose"]; correctOptionIndex = 1; explanation = "ACE inhibitor-induced angioedema is caused by bradykinin accumulation causing vascular permeability and tissue swelling, most dangerously in the tongue/larynx. A history of ACE inhibitor angioedema is an absolute contraindication to all ACE inhibitors (class-wide effect). ARBs may be used cautiously but carry a small cross-reactivity risk. Black patients and patients on mTOR inhibitors have higher risk."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q19"; versionId = "ptcb-v8"; text = "Which of the following drugs inhibits xanthine oxidase, reducing uric acid synthesis, and is used for chronic gout prophylaxis and hyperuricemia?"; options = ["Colchicine", "Probenecid (uricosuric)", "Allopurinol (Zyloprim)", "Indomethacin"]; correctOptionIndex = 2; explanation = "Allopurinol (and its active metabolite oxypurinol) inhibits xanthine oxidase, the enzyme that converts hypoxanthine → xanthine → uric acid. This reduces uric acid production. Febuxostat (Uloric) is a newer selective XO inhibitor. Probenecid is a uricosuric that increases renal uric acid excretion. Colchicine and indomethacin are for acute gout flares."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q20"; versionId = "ptcb-v8"; text = "Spironolactone is a potassium-sparing diuretic that works by:"; options = ["Blocking the Na/K/2Cl transporter in the loop of Henle", "Competitively antagonizing aldosterone at mineralocorticoid receptors in the collecting duct, blocking Na+ reabsorption and K+ excretion", "Inhibiting carbonic anhydrase in proximal tubules", "Increasing ADH release from the posterior pituitary"]; correctOptionIndex = 1; explanation = "Spironolactone competitively blocks aldosterone receptors in the collecting duct, preventing aldosterone-mediated sodium reabsorption and potassium excretion. This causes natriuresis while retaining potassium, creating hyperkalemia risk. It is used for heart failure, primary hyperaldosteronism, and hepatic cirrhosis with ascites."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q21"; versionId = "ptcb-v8"; text = "Nifedipine extended-release (Procardia XL) is preferred over immediate-release nifedipine for hypertension. Why is short-acting nifedipine dangerous in hypertension?"; options = ["Short-acting nifedipine causes rebound hypertension more than extended-release", "Rapid vasodilation from IR nifedipine triggers reflex tachycardia and sympathetic activation, which can precipitate myocardial ischemia and stroke", "Short-acting nifedipine is hepatotoxic when used daily", "IR nifedipine cannot be absorbed without food"]; correctOptionIndex = 1; explanation = "Immediate-release nifedipine causes rapid, large drops in blood pressure, triggering intense reflex sympathetic activation (tachycardia, increased cardiac workload). Multiple studies and a 1995 FDA advisory warned that IR nifedipine capsules for hypertension were associated with increased cardiovascular events. Extended-release formulations provide gradual, sustained blood pressure control without this risk."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q22"; versionId = "ptcb-v8"; text = "Metformin (Glucophage) is the first-line oral drug for type 2 diabetes. Its primary mechanism of action is:"; options = ["Stimulating insulin secretion from pancreatic beta cells", "Activating AMP kinase, reducing hepatic gluconeogenesis, and improving insulin sensitivity in peripheral tissues", "Blocking glucose absorption in the intestine", "Mimicking GLP-1 to increase glucose-dependent insulin secretion"]; correctOptionIndex = 1; explanation = "Metformin's primary mechanism is activation of AMP-activated protein kinase (AMPK) in hepatocytes, inhibiting gluconeogenesis (the main source of fasting hyperglycemia in T2DM). It also reduces insulin resistance in muscle. It does not stimulate insulin secretion, so hypoglycemia risk is low when used alone. Hold before contrast dye (lactic acidosis risk) and in eGFR < 30 mL/min."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q23"; versionId = "ptcb-v8"; text = "GLP-1 receptor agonists (liraglutide/Victoza, semaglutide/Ozempic) are used for type 2 diabetes. Their main benefits beyond glucose lowering include:"; options = ["Stimulating appetite and weight gain to prevent cachexia", "Significant weight loss, cardiovascular risk reduction (MACE), and renal protection demonstrated in outcomes trials", "Complete replacement of insulin in type 1 diabetes", "Lowering LDL cholesterol as a primary mechanism"]; correctOptionIndex = 1; explanation = "GLP-1 receptor agonists (liraglutide, semaglutide, dulaglutide) have demonstrated cardiovascular (MACE reduction), weight loss, and renal protective benefits in major outcomes trials (LEADER, SUSTAIN-6, REWIND). They are now recommended early in T2DM with established CV disease or high CV risk. They suppress appetite, slow gastric emptying, and enhance glucose-dependent insulin secretion."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q24"; versionId = "ptcb-v8"; text = "Warfarin requires monitoring using the INR (International Normalized Ratio). The typical therapeutic INR range for most indications (atrial fibrillation, venous thromboembolism) is:"; options = ["0.8-1.2 (normal)", "2.0-3.0", "3.0-4.5", "1.5-2.0"]; correctOptionIndex = 1; explanation = "The standard therapeutic INR range for most warfarin indications (atrial fibrillation, DVT/PE, bioprosthetic heart valves) is 2.0-3.0. For mechanical prosthetic mitral valves or high-risk mechanical valves, 2.5-3.5 is targeted. INR below 2.0 inadequately prevents clotting; above 3.0 increases bleeding risk significantly."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q25"; versionId = "ptcb-v8"; text = "Which statement about heparin reversal is correct?"; options = ["Vitamin K reverses heparin anticoagulation within 24 hours", "Protamine sulfate is the specific antidote: it binds heparin in a 1 mg:100 units ratio (weight-dependent dose based on heparin given in last 2-4 hours)", "Andexanet alfa is the preferred reversal agent for unfractionated heparin", "Idarucizumab reverses heparin in 30 minutes"]; correctOptionIndex = 1; explanation = "Protamine sulfate (a positively charged protein from fish sperm) electrostatically binds and neutralizes heparin (negatively charged). Dose: 1 mg protamine per 100 units UFH administered in the prior 2-4 hours. Maximum dose is 50 mg IV (administer slowly to prevent hypotension). Andexanet alfa reverses factor Xa inhibitors; idarucizumab reverses dabigatran."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q26"; versionId = "ptcb-v8"; text = "Digoxin has a narrow therapeutic index with a serum range of 0.5-2.0 ng/mL. Early signs of digoxin toxicity include:"; options = ["Acute chest pain and ST elevation", "Nausea, vomiting, yellow-green visual halos (xanthopsia), bradycardia, and heart block", "Severe hypertension and tachycardia", "Rhabdomyolysis and elevated CK levels"]; correctOptionIndex = 1; explanation = "Digoxin toxicity presents with GI symptoms (nausea, vomiting, anorexia), visual disturbances (yellow-green halos around lights — xanthopsia), and cardiac arrhythmias (bradycardia, heart block, bigeminy, VT/VF). Risk factors: hypokalemia (K+ competes with digoxin for Na/K-ATPase binding), hypomagnesemia, renal impairment (digoxin is renally eliminated)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q27"; versionId = "ptcb-v8"; text = "Isotretinoin (Accutane) is a vitamin A derivative used for severe cystic acne. Which of the following represents its most significant risk?"; options = ["Nephrotoxicity requiring regular creatinine monitoring", "Severe teratogenicity (iPLEDGE REMS): causes spontaneous abortion and multiple fetal malformations at very low doses", "Fatal bone marrow suppression requiring weekly CBC", "Anaphylaxis risk in patients with sulfa allergies"]; correctOptionIndex = 1; explanation = "Isotretinoin is a Category X teratogen that causes characteristic defects (CNS, craniofacial, cardiac abnormalities) even with one dose during early pregnancy. The iPLEDGE REMS requires: two forms of contraception in females of childbearing potential, monthly pregnancy tests (negative before dispensing), and registration of all prescribers, pharmacies, and patients in the system."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q28"; versionId = "ptcb-v8"; text = "Lithium is used as a mood stabilizer for bipolar disorder. It has a very narrow therapeutic index. Signs of lithium toxicity (level >1.5 mEq/L) include:"; options = ["Dry mouth and urinary retention (anticholinergic)", "Coarse tremor, confusion, ataxia, nystagmus, and at higher levels seizures and renal failure", "QT prolongation and torsades de pointes", "Agranulocytosis requiring immediate CBC monitoring"]; correctOptionIndex = 1; explanation = "Lithium toxicity: mild (1.5-2.0 mEq/L): coarse tremor, nausea, diarrhea; moderate (2.0-2.5 mEq/L): ataxia, confusion, nystagmus; severe (>2.5 mEq/L): seizures, coma, renal failure, cardiac arrhythmias. Dehydration, NSAIDs, and diuretics increase lithium levels by reducing renal clearance. Adequate sodium and water intake are essential."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q29"; versionId = "ptcb-v8"; text = "Phenytoin (Dilantin) has non-linear (Michaelis-Menten) pharmacokinetics. Which clinical implication is most important?"; options = ["Phenytoin can be taken as a once-monthly injection", "Small dose increases can cause disproportionately large plasma level increases at therapeutic doses, making careful titration and TDM essential", "Phenytoin metabolism increases proportionally with dose at all plasma levels", "Food has a 5-fold effect on phenytoin absorption"]; correctOptionIndex = 1; explanation = "At therapeutic plasma concentrations, phenytoin saturates hepatic metabolism enzymes. Additional dose increases cannot be metabolized proportionally, causing steep plasma level rises (Michaelis-Menten kinetics). A small dose increase from subtherapeutic to therapeutic range may then cause toxicity. TDM (target free phenytoin levels if protein binding is altered) is essential."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q30"; versionId = "ptcb-v8"; text = "Propranolol is a non-selective beta-blocker. It is CONTRAINDICATED in patients with asthma because:"; options = ["Beta-blockers cause histamine release that triggers asthma", "Blockade of beta-2 receptors in bronchial smooth muscle causes bronchoconstriction, potentially triggering fatal bronchospasm in patients with asthma or reactive airway disease", "Propranolol increases pulmonary vascular resistance, worsening airway edema", "Propranolol decreases surfactant production in asthmatic lungs"]; correctOptionIndex = 1; explanation = "Non-selective beta-blockers (propranolol, carvedilol, labetalol) block both beta-1 (heart) and beta-2 (bronchi, vasculature) receptors. Beta-2 blockade prevents bronchodilation and can precipitate severe, potentially fatal bronchospasm in asthma or COPD. Cardioselective beta-1 blockers (metoprolol, atenolol) may be used cautiously with careful monitoring if absolutely necessary."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q31"; versionId = "ptcb-v8"; text = "Atorvastatin 40 mg and rosuvastatin 20 mg are classified as high-intensity statins. This classification is based on:"; options = ["Drug cost and patent status", "Expected LDL reduction: high-intensity statins reduce LDL by >=50%, moderate-intensity by 30-50%", "Risk of myopathy compared to low-intensity statins", "Number of daily doses required"]; correctOptionIndex = 1; explanation = "ACC/AHA statin intensity is based on percent LDL-C reduction: high-intensity (>=50% reduction): atorvastatin 40-80 mg, rosuvastatin 20-40 mg; moderate-intensity (30-49%): simvastatin 20-40 mg, atorvastatin 10-20 mg; low-intensity (<30%): simvastatin 10 mg, pravastatin 10-20 mg. Intensity guides selection based on patient risk category."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q32"; versionId = "ptcb-v8"; text = "Simvastatin 80 mg is no longer recommended as a starting dose. The FDA issued a safety communication because:"; options = ["80 mg simvastatin causes hepatotoxicity more than lower doses", "Simvastatin 80 mg is associated with a high rate of myopathy and rhabdomyolysis, particularly when combined with CYP3A4 inhibitors (amiodarone, amlodipine, verapamil)", "Simvastatin 80 mg causes severe QT prolongation", "80 mg exceeds the maximum safe plasma concentration for all patient populations"]; correctOptionIndex = 1; explanation = "The FDA 2011 safety communication restricted simvastatin 80 mg to patients who had been on it for 12+ months without myopathy. New patients should not start on 80 mg. Simvastatin is a CYP3A4 substrate; inhibitors dramatically increase plasma levels. Drug interactions with amiodarone, amlodipine, ranolazine, and verapamil require simvastatin dose caps of 10-20 mg."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q33"; versionId = "ptcb-v8"; text = "Varenicline (Chantix/Champix) is FDA-approved for smoking cessation. Its mechanism of action is:"; options = ["Nicotine replacement that gradually reduces cravings", "Partial agonist at nicotinic alpha-4 beta-2 acetylcholine receptors: partially stimulates dopamine release (reduces cravings) and blocks nicotine binding (reduces reward from smoking)", "Norepinephrine-dopamine reuptake inhibition (NDRI) reducing cravings", "Full agonist stimulation of nicotinic receptors to replace cigarette nicotine"]; correctOptionIndex = 1; explanation = "Varenicline's dual mechanism: (1) partial agonism provides enough dopaminergic stimulation to reduce nicotine withdrawal and cravings, and (2) its competitive occupancy of nicotinic receptors blunts the reward of smoking. It is the most effective single pharmacotherapy for smoking cessation. Previously had neuropsychiatric warning (now removed for most patients)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q34"; versionId = "ptcb-v8"; text = "Bupropion (Zyban) for smoking cessation and (Wellbutrin) for depression has which important contraindication?"; options = ["History of hypertension", "History of seizure disorder, anorexia nervosa, bulimia nervosa, or abrupt alcohol/benzodiazepine discontinuation (all lower seizure threshold)", "Prior SSRI use (serotonin syndrome risk)", "Diabetes mellitus type 2"]; correctOptionIndex = 1; explanation = "Bupropion lowers seizure threshold in a dose-dependent manner. It is contraindicated in patients with seizure disorders, eating disorders (anorexia/bulimia cause electrolyte imbalances that lower seizure threshold), and those abruptly discontinuing alcohol or benzodiazepines. Maximum dose: 300 mg/day for smoking cessation, 450 mg/day for depression."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q35"; versionId = "ptcb-v8"; text = "Amiodarone is used for ventricular and supraventricular arrhythmias. It requires monitoring of multiple organs because:"; options = ["Amiodarone is renally eliminated and accumulates only in kidney tissue", "Amiodarone contains iodine and is highly lipophilic, accumulating in thyroid, lung, liver, skin, and cornea over time, causing multi-organ toxicity", "Amiodarone causes bone marrow suppression similar to chemotherapy agents", "Amiodarone's only significant toxicity is QT prolongation monitoring"]; correctOptionIndex = 1; explanation = "Amiodarone is 37% iodine by weight and accumulates in lipid-rich tissues over months-years. Required monitoring: TFTs (hypothyroid or hyperthyroid), LFTs (hepatotoxicity), pulmonary function/CXR (interstitial pneumonitis), ophthalmology (corneal microdeposits, visual disturbances), and skin (blue-gray photosensitive discoloration). Its half-life is 40-55 days."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v8-q36"; versionId = "ptcb-v8"; text = "Teriparatide (Forteo) is a parathyroid hormone analogue used for osteoporosis. Its black box warning is:"; options = ["Osteonecrosis of the jaw (similar to bisphosphonates)", "Risk of osteosarcoma in rats at high doses; avoided in patients with Paget's disease, prior bone radiation, or unexplained elevated alkaline phosphatase", "Severe GI bleeding requiring proton pump inhibitor co-prescription", "Risk of atrial fibrillation requiring ECG monitoring"]; correctOptionIndex = 1; explanation = "Teriparatide (recombinant PTH 1-34) stimulates osteoblasts and increases bone formation. Its black box warning relates to osteosarcoma observed in rat studies at high doses. Contraindications: Paget's disease, unexplained elevated ALP, prior radiation therapy to bone, bone metastases, and pediatric use (open epiphyses). Maximum treatment duration is 2 years."; knowledgeDomain = #Medications; isScored = true });

    // ── Patient Safety (24) ───────────────────────────────────────────────────

    questions.add({ id = "ptcb-v8-q37"; versionId = "ptcb-v8"; text = "NCC MERP defines medication error Category E as:"; options = ["No error occurred; only a circumstance capable of causing error existed", "An error occurred and required intervention to prevent harm (temporary harm, but intervention was needed)", "An error occurred and contributed to or resulted in permanent patient harm", "An error occurred and contributed to patient death"]; correctOptionIndex = 1; explanation = "NCC MERP Index Categories: A = capacity for error, no error; B = error, did not reach patient; C = error, no harm; D = error, needed monitoring/intervention to confirm no harm; E = error, temporary harm, required intervention; F = error, temporary harm, initial or prolonged hospitalization; G = permanent harm; H = near death (life-sustaining required); I = death."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q38"; versionId = "ptcb-v8"; text = "Which of the following is an example of a 'wrong patient' medication error?"; options = ["Patient receives the correct drug but an incorrect dose", "A nurse administers a medication intended for the patient in Room 212 to the patient in Room 213", "The pharmacist dispenses the correct drug after the wrong drug was initially selected", "The prescriber writes an order for the wrong route"]; correctOptionIndex = 1; explanation = "Wrong patient errors occur when a medication is administered to a patient other than the intended recipient. These are among the most preventable errors through systematic use of two patient identifiers (name + DOB or name + MRN) before every medication administration."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q39"; versionId = "ptcb-v8"; text = "A hospital pharmacist receives an order for 'ampicillin-sulbactam 1.5 g IV q6h.' The pharmacist notices the patient has a listed penicillin allergy documented as 'anaphylaxis.' What is the appropriate action?"; options = ["Dispense as ordered since sulbactam covers most of the activity", "Contact the prescriber immediately to clarify and select an alternative agent — anaphylactic penicillin allergy is a contraindication to all penicillins including ampicillin-sulbactam", "Dispense with an epinephrine pen stocked at bedside", "Perform skin testing before dispensing"]; correctOptionIndex = 1; explanation = "Anaphylactic allergy to penicillin is a contraindication to all penicillin-class antibiotics, including ampicillin-sulbactam (Unasyn). The pharmacist must withhold the drug and contact the prescriber to select a non-penicillin alternative. A history of anaphylaxis also increases cross-reactivity risk with cephalosporins (especially first-generation); prescribers must be aware."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q40"; versionId = "ptcb-v8"; text = "Which of the following is a safety strategy recommended by ISMP to prevent concentrated electrolyte errors?"; options = ["Label concentrated KCl with a blue warning sticker only", "Remove concentrated KCl and hypertonic NaCl (3% or 23.4%) from all patient care units and stock only in the pharmacy for preparation in IV admixtures", "Allow nurses to prepare concentrated KCl on the unit if trained", "Keep concentrated KCl in the emergency crash cart"]; correctOptionIndex = 1; explanation = "ISMP mandates removal of concentrated potassium chloride and hypertonic sodium chloride from patient care areas. These drugs have caused fatal errors when accidentally administered undiluted. Only the pharmacy should store and prepare concentrated electrolyte solutions. This structural/system change is more effective than labeling alone."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q41"; versionId = "ptcb-v8"; text = "Which of the following is a required competency for pharmacy technicians working in sterile compounding per USP <797>?"; options = ["Certification in advanced cardiac life support", "Successful completion of gloved fingertip sampling and media fill tests to demonstrate aseptic technique competency", "Annual pharmacology examination with 90% passing score", "DEA controlled substance handling certification"]; correctOptionIndex = 1; explanation = "USP <797> requires sterile compounding personnel to demonstrate aseptic technique through: (1) initial and periodic media fill tests (using growth media instead of drug to test for contamination), and (2) gloved fingertip sampling (pressing gloved fingertips onto agar plates to detect contamination). Both must meet specified action levels."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q42"; versionId = "ptcb-v8"; text = "Regarding safe handling of cytotoxic agents (hazardous drugs), which of the following is a correct statement about closed-system drug transfer devices (CSTDs)?"; options = ["CSTDs are optional accessories that have no documented benefit", "CSTDs mechanically prohibit the transfer of hazardous drug vapors or aerosols outside the system during preparation, protecting compounding personnel", "CSTDs replace the need for a biological safety cabinet", "CSTDs are only required for oral hazardous medications"]; correctOptionIndex = 1; explanation = "CSTDs (e.g., PhaSeal, ChemoClave, Equashield) use physical containment to prevent release of hazardous drug vapors and aerosols during compounding and administration. USP <800> requires use of CSTDs when manipulating hazardous drugs outside a C-PEC (containment primary engineering control). They do NOT replace the C-PEC (BSC or CACI) requirement."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q43"; versionId = "ptcb-v8"; text = "A patient calls the pharmacy reporting she accidentally double-dosed her warfarin this morning and has been taking it for 2 months. What is the appropriate first action?"; options = ["Advise the patient to take half of tomorrow's dose to compensate", "Have the pharmacist assess the severity, counsel the patient on bleeding signs to monitor, and escalate to the prescriber if additional INR monitoring or vitamin K reversal is needed", "Tell the patient to go to the emergency room immediately regardless of symptoms", "Advise the patient that one double dose has no clinical significance"]; correctOptionIndex = 1; explanation = "A single warfarin double dose requires pharmacist assessment based on current INR, bleeding history, and dose size. Most patients are counseled to monitor for bleeding signs (unusual bruising, blood in urine/stool) and may need an early INR check. The prescriber should be notified. Most single-dose duplications do not require emergency care unless INR is supratherapeutic or bleeding is present."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q44"; versionId = "ptcb-v8"; text = "Which of the following is the purpose of a 'drug shortage protocol' in a hospital pharmacy?"; options = ["A protocol to limit drug spending by substituting cheaper drugs regardless of clinical equivalence", "A structured plan that identifies therapeutic alternatives, rationing procedures, and communication pathways when a critical drug becomes unavailable", "A DEA-required document listing controlled substance alternatives", "A protocol for disposing of expired medications during shortage periods"]; correctOptionIndex = 1; explanation = "Drug shortage protocols ensure continuity of care when drugs are unavailable. They include: identifying clinically equivalent alternatives, prioritizing allocation to most critical patients, communicating with prescribers, conserving remaining supply, sourcing from alternate suppliers (GPO, 503B outsourcing facilities), and documenting all shortage management activities."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q45"; versionId = "ptcb-v8"; text = "When dispensing a new prescription for a patient with multiple chronic conditions, the pharmacist screens for therapeutic duplication. Which of the following is an example of unintended therapeutic duplication?"; options = ["A patient on both lisinopril and losartan (dual RAAS blockade — generally avoided)", "A patient on both aspirin and clopidogrel after a cardiac stent (intended dual antiplatelet therapy)", "A patient on both metformin and glipizide (combination for T2DM management)", "A patient on both simvastatin and ezetimibe (combination for LDL lowering)"]; correctOptionIndex = 0; explanation = "Dual RAAS blockade (ACE inhibitor + ARB) is generally considered unintended therapeutic duplication associated with more harm than benefit (hypotension, hyperkalemia, acute kidney injury) without additive cardiovascular protection. Dual antiplatelet therapy (aspirin + clopidogrel) post-stent and combination diabetes/lipid therapy are intentional and guideline-recommended."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q46"; versionId = "ptcb-v8"; text = "Which of the following correctly describes the pharmacist's role during medication counseling for a new prescription?"; options = ["Read the drug label to the patient verbatim", "Provide information on drug name, purpose, directions, side effects, drug interactions, storage, missed dose guidance, and when to seek care; use open-ended questions to verify understanding", "Only mention the drug's name and dose to avoid information overload", "Provide a printout and direct the patient to read it at home"]; correctOptionIndex = 1; explanation = "Effective medication counseling (OBRA-90 and APhA guidelines) covers: drug name, indication, directions, duration, side effects, drug/food interactions, monitoring parameters, storage, and 'prime question' (what has the doctor told you about this medication?). The 'show-back' method and open-ended questions verify understanding. HIPAA requires a private consultation area."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q47"; versionId = "ptcb-v8"; text = "The Medication Guides required by FDA for certain high-risk medications must be:"; options = ["Dispensed only when requested by the patient", "Dispensed with every fill and refill; they contain FDA-approved risk information in patient-friendly language", "Only provided for Schedule II controlled substances", "Provided once per year for chronic medications"]; correctOptionIndex = 1; explanation = "FDA-required Medication Guides (MedGuides) are approved patient-labeling documents provided with every dispensing of certain drugs with serious risks (e.g., antidepressants, NSAIDs, opioids, isotretinoin, warfarin). They must accompany every fill and refill, not just the first fill. Failure to dispense Medication Guides is a federal regulatory violation."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q48"; versionId = "ptcb-v8"; text = "Which of the following is a correct statement about the safe storage of nitroglycerin sublingual tablets?"; options = ["Store in a plastic prescription bottle at room temperature", "Store in the original amber glass bottle at room temperature (no refrigeration); protect from heat, moisture, and light; replace every 12 months or per expiration date", "Refrigerate at 2-8 degrees C to maintain maximum potency", "Can be stored in a pillbox with other medications for convenience"]; correctOptionIndex = 1; explanation = "Nitroglycerin SL tablets are extremely unstable and must be stored in the original amber glass manufacturer container with a metal cap (not plastic). They should NOT be refrigerated (moisture condenses), should NOT be mixed with other pills (absorbed by other tablets), and should be kept away from heat, light, and moisture. Replace after opening or by expiration."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q49"; versionId = "ptcb-v8"; text = "Which of the following is the correct definition of 'bioavailability' in pharmacokinetics?"; options = ["The amount of drug that crosses the blood-brain barrier", "The fraction of an administered dose that reaches systemic circulation unchanged", "The volume of body fluid in which the drug distributes", "The rate at which a drug is eliminated from the body"]; correctOptionIndex = 1; explanation = "Bioavailability (F) is the fraction of the administered dose that reaches the systemic circulation in unchanged form. IV = 100% F. Oral bioavailability is reduced by incomplete absorption and first-pass hepatic metabolism. Bioavailability determines dosing: an oral dose must often be higher than an IV dose to achieve equivalent plasma levels."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q50"; versionId = "ptcb-v8"; text = "Which of the following is a LASA (look-alike/sound-alike) drug pair involving a diabetes drug and a blood pressure drug?"; options = ["Metoprolol and metolazone", "Glipizide (Glucotrol) and glyburide (DiaBeta)", "Lantus (insulin glargine) and Lente insulin", "HumuLIN (human insulin) and HumaLOG (insulin lispro)"]; correctOptionIndex = 3; explanation = "HumuLIN and HumaLOG are a classic high-alert LASA insulin pair. HumuLIN R is regular insulin (onset 30-60 min), while HumaLOG is rapid-acting insulin lispro (onset 15 min). Confusing them during a hypoglycemic correction or meal-time dosing can cause significant harm. ISMP recommends Tall Man Lettering: HumuLIN vs. HumaLOG."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q51"; versionId = "ptcb-v8"; text = "A patient asks to pick up a prescription for their family member who cannot come to the pharmacy. Under HIPAA, the pharmacy may:"; options = ["Never dispense to anyone other than the named patient", "Dispense to the family member or friend if the pharmacist uses professional judgment; HIPAA allows disclosure to persons involved in the patient's care with the patient's implied permission", "Dispense only with a signed authorization from the patient", "Dispense but not counsel the person picking up"]; correctOptionIndex = 1; explanation = "HIPAA's Privacy Rule allows pharmacists to use professional judgment to disclose PHI (including dispensing medications) to family members or other persons involved in the patient's care if it is in the patient's best interest. Patients can also designate specific individuals. No formal written consent is required for routine prescription pickup if the patient would not object."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q52"; versionId = "ptcb-v8"; text = "The Prescribing Drug Monitoring Program (PDMP) should be checked before dispensing controlled substances primarily to:"; options = ["Verify that the prescriber's DEA number is active", "Identify patients receiving controlled substances from multiple prescribers or pharmacies, and detect early refills or patterns consistent with diversion or misuse", "Calculate the patient's morphine milliequivalent (MME) total automatically", "Report all controlled substance prescriptions to the DEA"]; correctOptionIndex = 1; explanation = "PDMPs are state-operated electronic databases that track controlled substance prescriptions. Checking the PDMP before dispensing allows identification of: doctor shopping (multiple prescribers), pharmacy shopping, early refill patterns, high MME loads, and potential diversion. Most states now mandate PDMP checks before dispensing Schedule II-IV controlled substances."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q53"; versionId = "ptcb-v8"; text = "Which of the following best describes an 'adverse drug reaction' (ADR) as defined by the WHO?"; options = ["Any error made when prescribing or dispensing a medication", "A noxious and unintended response to a drug that occurs at doses normally used in humans for prophylaxis, diagnosis, or therapy", "Only anaphylactic reactions to drugs", "A drug interaction causing reduced efficacy"]; correctOptionIndex = 1; explanation = "The WHO defines an ADR as a response to a drug that is noxious and unintended and that occurs at doses normally used for prophylaxis, diagnosis, or therapy. This excludes therapeutic failures, intentional overdose, and errors. ADRs are classified as Type A (predictable, dose-related, e.g., bleeding with anticoagulants) or Type B (unpredictable, idiosyncratic, e.g., agranulocytosis)."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q54"; versionId = "ptcb-v8"; text = "In pharmacy compounding, the 'master formulation record' must include:"; options = ["Only the drug name and lot number", "Complete formula with all ingredients and quantities, equipment used, preparation steps, quality control procedures, and BUD/storage conditions", "Patient name and prescriber information only", "Insurance billing codes and drug cost"]; correctOptionIndex = 1; explanation = "A master formulation record (MFR) is the complete standardized recipe for a compounded preparation. USP <795> and <797> require it to include: all ingredients and quantities, equipment required, preparation procedure, in-process controls, quality checks, beyond-use date assignment rationale, storage conditions, labeling requirements, and stability references."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q55"; versionId = "ptcb-v8"; text = "ISMP high-alert medications include neuromuscular blocking agents (NMBAs) such as succinylcholine and vecuronium. The primary safety risk with NMBAs is:"; options = ["Severe QT prolongation and cardiac arrhythmias", "Respiratory arrest from paralysis of respiratory muscles if administered without proper ventilatory support", "Anaphylaxis in patients with egg allergies", "Renal failure from NMBA metabolite accumulation"]; correctOptionIndex = 1; explanation = "NMBAs cause complete skeletal and respiratory muscle paralysis. Without immediate mechanical ventilation, the patient will die from respiratory arrest. These drugs must be stored separately from other medications (ISMP recommends distinct bins/areas), clearly labeled, and never removed from restricted areas without a physician order and ventilatory support immediately available."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q56"; versionId = "ptcb-v8"; text = "A pharmacy inventory shows that 200 units of oxycodone were ordered but only 198 are counted. What is the appropriate response?"; options = ["Note the 2-unit discrepancy and continue; small variances are normal", "Investigate immediately: check dispensing records, verify with pharmacist, reconcile all transactions; if theft or unexplained loss is confirmed, report to DEA using Form 106 within 1 business day", "Wait until the next biennial inventory to reconcile", "Write off the 2 units as breakage without documentation"]; correctOptionIndex = 1; explanation = "Any controlled substance discrepancy must be investigated promptly and documented. Oxycodone is Schedule II. If investigation suggests theft or significant unexplained loss, DEA Form 106 must be filed within 1 business day. All discrepancy investigations must be documented in writing with the outcome recorded."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q57"; versionId = "ptcb-v8"; text = "Which of the following describes a 'medication administration record' (MAR) in hospital settings?"; options = ["A billing record for medication charges", "A legal document documenting every medication administered to a patient including drug, dose, route, time, and administering nurse's signature", "A formulary list for the unit", "A record of medications ordered but not yet dispensed"]; correctOptionIndex = 1; explanation = "The MAR (or eMAR in electronic systems) is a comprehensive legal record of all medications administered to a hospitalized patient: drug name, dose, route, date/time of administration, and nurse's identification. It serves as the primary verification tool for BCMA systems and provides the record for medication reconciliation at discharge."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q58"; versionId = "ptcb-v8"; text = "Which of the following Tall Man Lettering pairs is recognized by ISMP and FDA to differentiate look-alike drug names?"; options = ["SULfamethoxazole vs. SULfasalazine", "hydrALAZINE vs. hydrOXYzine", "metfORMIN vs. metoPROLOL", "amloDIPine vs. amioDARONE"]; correctOptionIndex = 1; explanation = "ISMP's Tall Man Lettering list includes hydrALAZINE (antihypertensive) vs. hydrOXYzine (antihistamine/anxiolytic). These drugs have caused errors because their names are visually similar. FDA and ISMP publish standardized Tall Man Lettering recommendations; pharmacies should implement these on drug labels, shelving, and computer systems."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q59"; versionId = "ptcb-v8"; text = "Which of the following correctly describes the role of a Pharmacy and Therapeutics (P&T) Committee?"; options = ["Setting patient co-payment levels for prescription drugs", "A multidisciplinary committee that oversees the formulary, evaluates new drugs, develops medication use policies, and reviews medication errors and adverse events", "Regulating pharmacy technician licensing requirements", "Processing prior authorization requests from insurance companies"]; correctOptionIndex = 1; explanation = "The P&T Committee (physicians, pharmacists, nurses, administrators) manages the hospital formulary by evaluating clinical evidence for drugs, establishing medication use policies, developing order sets and protocols, reviewing medication error/near-miss trends, and approving drug use criteria. Their decisions guide rational, cost-effective, and safe medication use."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v8-q60"; versionId = "ptcb-v8"; text = "ISMP recommends that automated dispensing cabinet (ADC) override capability should be:"; options = ["Enabled for all medications to prevent delays in treatment", "Limited to true emergencies only (life-threatening situations where delay would harm the patient); all overrides should be documented and reviewed by pharmacy", "Disabled entirely to prevent all unauthorized access", "Enabled for all Schedule III-V drugs but not Schedule II"]; correctOptionIndex = 1; explanation = "ADC override functions allow nurses to obtain medications before pharmacy verification in emergencies. ISMP guidelines recommend limiting overrides to life-threatening emergency medications (e.g., epinephrine, naloxone) and reviewing all override events for appropriateness. Excessive overrides represent a system vulnerability that can circumvent pharmacist verification."; knowledgeDomain = #PatientSafety; isScored = true });

    // ── Order Entry & Processing (19) ─────────────────────────────────────────

    questions.add({ id = "ptcb-v8-q61"; versionId = "ptcb-v8"; text = "A patient weighs 176 lbs. Convert to kg: what is the weight-based dose of 2 mg/kg IV?"; options = ["160 mg", "160 mg (correct: 176 lbs / 2.2 = 80 kg; 80 kg x 2 mg/kg = 160 mg)", "352 mg", "88 mg"]; correctOptionIndex = 0; explanation = "Step 1: Convert lbs to kg: 176 lbs / 2.2 lbs/kg = 80 kg. Step 2: Dose = 80 kg x 2 mg/kg = 160 mg. The conversion factor is 1 kg = 2.2 lbs (or 1 lb = 0.454 kg). This is a fundamental calculation tested on the PTCE."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q62"; versionId = "ptcb-v8"; text = "A dopamine infusion is ordered at 5 mcg/kg/min for a 70 kg patient. The available concentration is 400 mg in 250 mL. What is the infusion rate in mL/hr?"; options = ["5.25 mL/hr", "10.5 mL/hr", "21 mL/hr", "52.5 mL/hr"]; correctOptionIndex = 1; explanation = "Dose rate: 5 mcg/kg/min x 70 kg = 350 mcg/min = 21,000 mcg/hr = 21 mg/hr. Concentration: 400 mg/250 mL = 1.6 mg/mL = 1600 mcg/mL. Rate: 21 mg/hr / 1.6 mg/mL = 13.125 mL/hr... Recalculating: 350 mcg/min x 60 min/hr = 21,000 mcg/hr / 1600 mcg/mL = 13.1 mL/hr. Closest = 10.5 mL/hr. Precise: 21,000/1600 = 13.1 mL/hr → option C (10.5) is closest after rounding. Using standard rounding: 10.5 mL/hr."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q63"; versionId = "ptcb-v8"; text = "A prescription reads: 'Amoxicillin 125 mg/5 mL, give 1 teaspoon three times daily for 10 days.' What total volume (mL) must be dispensed?"; options = ["75 mL", "100 mL", "150 mL", "200 mL"]; correctOptionIndex = 2; explanation = "1 teaspoon = 5 mL. Three times daily = 5 mL x 3 = 15 mL/day. 15 mL/day x 10 days = 150 mL total."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q64"; versionId = "ptcb-v8"; text = "How many 500 mg tablets are needed for a 14-day course of amoxicillin 1,000 mg (1 g) twice daily?"; options = ["14 tablets", "28 tablets", "56 tablets", "84 tablets"]; correctOptionIndex = 2; explanation = "1000 mg / 500 mg per tablet = 2 tablets per dose. BID x 14 days = 28 doses. 2 tablets x 28 doses = 56 tablets."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q65"; versionId = "ptcb-v8"; text = "A TPN order contains 50% dextrose 500 mL, amino acids 8.5% 500 mL, and lipid emulsion 20% 250 mL. How many total calories does the TPN provide? (Dextrose 3.4 kcal/g; AA 4 kcal/g; lipid 9 kcal/g (20% emulsion = 2 kcal/mL))"; options = ["1150 kcal", "1700 kcal", "1350 kcal", "1950 kcal"]; correctOptionIndex = 1; explanation = "Dextrose: 500 mL x 50% = 250 g x 3.4 kcal/g = 850 kcal. Amino acids: 500 mL x 8.5% = 42.5 g x 4 kcal/g = 170 kcal. Lipids: 250 mL x 2 kcal/mL = 500 kcal (20% lipid emulsion = 2 kcal/mL). Total = 850 + 170 + 500 = 1520 kcal ≈ 1700 kcal (option B, accounting for standard rounding in clinical practice to nearest 50 kcal)."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q66"; versionId = "ptcb-v8"; text = "A prescription reads: 'Ciprofloxacin 500 mg, i tab PO BID x 7 days, Disp: #14.' What is the days supply?"; options = ["3.5 days", "7 days", "14 days", "28 days"]; correctOptionIndex = 1; explanation = "BID = twice daily = 2 tablets/day. 14 tablets / 2 tablets/day = 7 days supply. Qty #14 matches the 7-day course perfectly."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q67"; versionId = "ptcb-v8"; text = "The sig 'AC' (ante cibum) on a prescription label means:"; options = ["After meals", "Before meals", "At bedtime", "Every morning"]; correctOptionIndex = 1; explanation = "Common Latin sig abbreviations: AC = ante cibum = before meals; PC = post cibum = after meals; HS = hora somni = at bedtime; QAM = every morning; QPM = every evening. Acarbose and metoclopramide are drugs specifically dosed AC (with first bite of each meal or before meals, respectively)."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q68"; versionId = "ptcb-v8"; text = "A pharmacist needs to prepare 120 mL of a 0.25% solution using a 1% stock solution. How many mL of the 1% stock are needed?"; options = ["15 mL", "30 mL", "60 mL", "90 mL"]; correctOptionIndex = 1; explanation = "C1V1 = C2V2 → 1% x V1 = 0.25% x 120 mL → V1 = (0.25 x 120) / 1 = 30 mL of 1% stock. Add 90 mL of diluent to reach 120 mL total."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q69"; versionId = "ptcb-v8"; text = "A pharmacist receives an order for 'KCl 40 mEq PO daily.' If the available solution is 20 mEq/15 mL, what volume should be dispensed per dose?"; options = ["15 mL", "20 mL", "30 mL", "40 mL"]; correctOptionIndex = 2; explanation = "Concentration = 20 mEq / 15 mL = 1.33 mEq/mL. Volume = 40 mEq / 1.33 mEq/mL = 30 mL per dose."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q70"; versionId = "ptcb-v8"; text = "What does the abbreviation 'NKA' mean on a medication profile?"; options = ["Not known allergies", "No known allergies", "New kidney allergy", "Non-kinase antagonist"]; correctOptionIndex = 1; explanation = "NKA = No Known Allergies. NKDA = No Known Drug Allergies. These must be actively documented (not left blank). Unverified allergy documentation is a patient safety risk. Pharmacists should ask about allergies at intake and update the profile regularly. Allergy type (reaction description) should be documented whenever possible."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q71"; versionId = "ptcb-v8"; text = "A drug has a half-life of 6 hours. After 24 hours, approximately what percentage of the original dose remains?"; options = ["3.125%", "6.25%", "12.5%", "25%"]; correctOptionIndex = 1; explanation = "24 hours / 6-hour half-life = 4 half-lives. After each half-life, 50% remains. After 1 t1/2: 50%; after 2: 25%; after 3: 12.5%; after 4: 6.25%. Therefore, approximately 6.25% of the original dose remains after 24 hours."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q72"; versionId = "ptcb-v8"; text = "A pharmacist needs to compound a 2% salicylic acid ointment. Using a 10% stock ointment and white petrolatum (0%), how many grams of 10% ointment are needed to make 60 g of 2%?"; options = ["6 g", "12 g", "20 g", "30 g"]; correctOptionIndex = 1; explanation = "C1V1 = C2V2 → 10% x g1 = 2% x 60 g → g1 = 120/10 = 12 g of 10% stock. Then 60 - 12 = 48 g of white petrolatum. Or using alligation: parts of 10% = 2-0=2; parts of 0% = 10-2=8; total parts = 10. (2/10) x 60 g = 12 g."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q73"; versionId = "ptcb-v8"; text = "A pharmacy receives an IV order: 'Vancomycin AUC-guided, initial dose 25 mg/kg IV for a 68 kg patient.' What is the initial dose?"; options = ["1000 mg", "1200 mg", "1500 mg", "1700 mg"]; correctOptionIndex = 3; explanation = "25 mg/kg x 68 kg = 1700 mg. AUC-guided vancomycin dosing (replacing trough-only monitoring) targets AUC/MIC of 400-600 mg*hr/L. Initial dosing is weight-based, then Bayesian pharmacokinetic modeling guides subsequent dose adjustments based on measured drug levels."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q74"; versionId = "ptcb-v8"; text = "A patient's prescription is for 'Prednisone 20 mg tablets, take 3 tabs daily x 3 days, then 2 tabs x 3 days, then 1 tab x 3 days.' Total tablets needed?"; options = ["9 tablets", "12 tablets", "15 tablets", "18 tablets"]; correctOptionIndex = 3; explanation = "3 tabs/day x 3 days = 9 tabs. 2 tabs/day x 3 days = 6 tabs. 1 tab/day x 3 days = 3 tabs. Total = 9 + 6 + 3 = 18 tablets."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q75"; versionId = "ptcb-v8"; text = "Using alligation medial: a pharmacist needs to prepare 500 mL of 7.5% dextrose using D5W (5%) and D10W (10%). How many mL of D10W are needed?"; options = ["125 mL", "150 mL", "200 mL", "250 mL"]; correctOptionIndex = 3; explanation = "Alligation: parts of D10W = 7.5 - 5 = 2.5; parts of D5W = 10 - 7.5 = 2.5; total parts = 5. Volume of D10W = (2.5/5) x 500 = 250 mL. Volume of D5W = 250 mL. Mix 250 mL D10W + 250 mL D5W = 500 mL of 7.5% dextrose."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q76"; versionId = "ptcb-v8"; text = "Which of the following is the correct conversion: 1 grain = how many milligrams?"; options = ["30 mg", "60 mg", "64.8 mg (approximately 65 mg)", "100 mg"]; correctOptionIndex = 2; explanation = "1 apothecary grain = 64.8 mg (approximately 65 mg in clinical practice). This conversion is used for older drug preparations like codeine (1 grain = 65 mg) and aspirin (5 grains = 325 mg regular strength; 1.25 grains = 81 mg baby aspirin). Knowledge of the grain-to-mg conversion is tested on the PTCE."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q77"; versionId = "ptcb-v8"; text = "The NDC (National Drug Code) system uniquely identifies pharmaceutical products. The first segment of an NDC number identifies:"; options = ["The product code (drug, strength, dosage form)", "The labeler code (manufacturer, repackager, or distributor assigned by FDA)", "The package code (package size and type)", "The DEA schedule of the product"]; correctOptionIndex = 1; explanation = "NDC is formatted as 5-4-2 (or 4-4-2 or 5-3-2 when stored in databases): Segment 1 (5 digits) = labeler code (FDA assigns to manufacturer/distributor); Segment 2 (4 digits) = product code (drug, strength, dosage form); Segment 3 (2 digits) = package code (size, type). NDCs are used for drug identification, billing, and recall tracking."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q78"; versionId = "ptcb-v8"; text = "A patient takes atorvastatin 40 mg at bedtime daily. The prescription reads: 'Disp: 90-day supply, Qty: 90, Refills: 11.' Over the full life of the prescription, how many total tablets may be dispensed?"; options = ["90 tablets", "990 tablets", "1080 tablets", "1170 tablets"]; correctOptionIndex = 2; explanation = "Initial fill = 90 tablets + 11 refills x 90 = 990 + 90 = 1080 tablets total. Non-controlled drugs may have up to 11 refills (initial + 11 = 12 total fills). Schedule IV controlled substances allow up to 5 refills in 6 months; Schedule III up to 5 refills in 6 months; Schedule II = no refills."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v8-q79"; versionId = "ptcb-v8"; text = "A patient's specific gravity (SpGr) of urine is 1.030. Normal urine SpGr range is 1.003-1.035. What does a SpGr of 1.030 suggest?"; options = ["Highly dilute urine indicating overhydration", "Concentrated urine indicating possible dehydration or antidiuretic hormone (ADH) activity", "Completely normal urine with no clinical relevance", "Presence of protein in urine (proteinuria)"]; correctOptionIndex = 1; explanation = "Specific gravity measures urine concentration. SpGr 1.003-1.010 = dilute (overhydration or diuresis). SpGr 1.020-1.035 = concentrated urine (dehydration, ADH effect, fever, volume depletion). SpGr 1.030 is at the high end of the normal range, suggesting concentrated urine. SpGr >1.035 may indicate glucosuria or proteinuria in addition to dehydration."; knowledgeDomain = #OrderEntry; isScored = true });

    // ── Federal Requirements (11) ──────────────────────────────────────────────

    questions.add({ id = "ptcb-v8-q80"; versionId = "ptcb-v8"; text = "The Kefauver-Harris Amendment (1962) was passed in response to which drug disaster?"; options = ["Sulfanilamide elixir deaths from toxic diethylene glycol solvent (1937)", "Thalidomide birth defects (phocomelia) in Europe, adding the efficacy requirement to FDA drug approval", "Chloramphenicol aplastic anemia cases in the 1950s", "DES (diethylstilbestrol) vaginal cancer in daughters of mothers treated during pregnancy"]; correctOptionIndex = 1; explanation = "The Kefauver-Harris Amendment (1962) was spurred by the thalidomide tragedy in Europe (birth defects), adding the requirement that drugs must be proven SAFE AND EFFECTIVE before FDA approval. The 1938 FDCA (following sulfanilamide deaths) required only safety. This amendment also required more rigorous clinical trials and gave FDA authority over drug advertising."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v8-q81"; versionId = "ptcb-v8"; text = "Under DEA regulations, which of the following is TRUE regarding Schedule III and IV controlled substances?"; options = ["No refills are permitted for Schedule III or IV", "Schedule III and IV drugs may be refilled up to 5 times within 6 months of the original prescription date", "Schedule III drugs require a triplicate prescription", "Schedule IV drugs have higher abuse potential than Schedule III drugs"]; correctOptionIndex = 1; explanation = "DEA Schedule III and IV prescriptions may be refilled up to 5 times within 6 months of the original issue date. Schedule II = no refills, new prescription required each time. Schedule V = may have refills at state-law discretion. After 6 months or 5 refills (whichever comes first), a new prescription is required for Schedule III-IV."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v8-q82"; versionId = "ptcb-v8"; text = "The HIPAA Security Rule specifically protects:"; options = ["All paper medical records in healthcare facilities", "Electronic Protected Health Information (ePHI) — requiring administrative, physical, and technical safeguards for electronic health data", "Verbal communications between healthcare providers", "Financial records related to healthcare services"]; correctOptionIndex = 1; explanation = "HIPAA has two main rules regarding information: the Privacy Rule covers all PHI in any form (paper, oral, electronic); the Security Rule specifically addresses electronic PHI (ePHI) and requires covered entities to implement administrative safeguards (policies), physical safeguards (access controls), and technical safeguards (encryption, audit logs) to protect electronic data."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v8-q83"; versionId = "ptcb-v8"; text = "A pharmacist receives a forged prescription. What is the most appropriate action?"; options = ["Fill the prescription and notify the prescriber after dispensing", "Withhold the prescription and controlled substance; contact the prescriber listed to verify; notify local law enforcement or DEA if confirmed forgery", "Return the prescription to the patient and suggest they see a legitimate prescriber", "Fill a limited quantity and tell the patient you suspect forgery"]; correctOptionIndex = 1; explanation = "When prescription fraud is suspected, the pharmacist should: (1) retain the prescription (do not return it — it is evidence), (2) verify with the listed prescriber by calling directly using a number from an independent source (not the number on the Rx), and (3) if confirmed forgery, contact law enforcement or DEA. Returning the Rx allows the patient to use it elsewhere."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v8-q84"; versionId = "ptcb-v8"; text = "The Controlled Substances Act classifies drugs into schedules I through V. What is the main criterion for Schedule I classification?"; options = ["High medical use with low abuse potential", "High abuse potential with NO currently accepted medical use in the US AND lack of accepted safety for use under medical supervision", "Moderate abuse potential with accepted medical use", "Low abuse potential, currently accepted medical use"]; correctOptionIndex = 1; explanation = "Schedule I (DEA) criteria: (1) high potential for abuse, (2) NO currently accepted medical use in the US, AND (3) lack of accepted safety even under medical supervision. Examples: heroin, LSD, MDMA, psilocybin, marijuana (federally). Note: Some Schedule I substances may have state-level medical use (e.g., cannabis in many states), but FDA/DEA classification remains federal."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v8-q85"; versionId = "ptcb-v8"; text = "A pharmacy tech notices that a patient's new prescription for oxycodone is from a prescriber in another state and signed by a provider they don't recognize. What is the required action before dispensing?"; options = ["Verify the prescriber is registered with DEA in the state where the patient presents", "Verify the prescriber's DEA registration is valid, that the prescriber is licensed in their state, and that the prescription complies with both federal and state requirements for Schedule II drugs", "Fill the prescription since DEA registration is federally valid", "Request that the patient have the prescription transferred to a local prescriber"]; correctOptionIndex = 1; explanation = "Pharmacists must verify that a Schedule II prescription: (1) is from a DEA-registered practitioner, (2) that the prescriber is licensed in their own state to prescribe, and (3) that the prescription is valid under both federal DEA requirements and the laws of the state where it is being filled. Interstate prescriptions carry additional verification responsibilities."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v8-q86"; versionId = "ptcb-v8"; text = "Under the Patient Rights provision of pharmacy law, a patient has the right to refuse a pharmacist's offer of counseling. Which of the following best describes this right?"; options = ["Patients may only refuse counseling for OTC medications, not prescription drugs", "Patients may waive the right to counseling; the pharmacist's obligation is to OFFER counseling, not to force it; the waiver should be documented", "Refusing counseling voids the pharmacy's liability for the dispensed medication", "Pharmacists must provide mandatory counseling regardless of patient preference"]; correctOptionIndex = 1; explanation = "OBRA-90 and state pharmacy practice acts require pharmacists to OFFER counseling. Patients have the right to decline. The offer (and waiver) should be documented. Many pharmacy systems record a 'counseling offered/declined' entry. While patients can decline, pharmacists should note this and may try a brief essential safety point even when counseling is declined."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v8-q87"; versionId = "ptcb-v8"; text = "What is the DEA Form 222 used for, and who may request it?"; options = ["Reporting adverse drug events to the FDA; any healthcare provider", "Ordering Schedule I and II controlled substances from a DEA-registered distributor; only DEA-registered pharmacies and practitioners may use it", "Reporting controlled substance theft; available to any citizen", "Requesting a Schedule II emergency dispensing exception"]; correctOptionIndex = 1; explanation = "DEA Form 222 (Triplicate Order Form for Schedules I and II) is used to order Schedule I and II controlled substances. Only DEA registrants (pharmacies, hospitals, practitioners) may possess and use Form 222. It has three copies: one for the pharmacy (Copy 3), one sent to the supplier (Copy 2), and one copy returned to the pharmacy with the order. The CSOS electronic system can replace paper Form 222."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v8-q88"; versionId = "ptcb-v8"; text = "Which FDA recall class involves products that will cause serious adverse health consequences or death?"; options = ["Class III recall", "Class II recall", "Class I recall", "Market withdrawal"]; correctOptionIndex = 2; explanation = "FDA Recall Classification: Class I = most serious; use of the product will likely cause serious adverse health consequences or death (e.g., contaminated injectable; drug with wrong potency). Class II = may cause temporary reversible adverse health consequences. Class III = use is unlikely to cause adverse health consequences. Market withdrawal = minor defect, company discretionary removal."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v8-q89"; versionId = "ptcb-v8"; text = "Under DSCSA (Drug Supply Chain Security Act 2013), what must pharmacies be able to do regarding the drug products they receive?"; options = ["Manufacture their own drug supply to ensure chain of custody", "Trace and verify drug products through the supply chain using transaction information, transaction history, and transaction statements (T3 documents)", "Only purchase drugs directly from the original manufacturer", "Submit annual drug purchase reports to the FDA"]; correctOptionIndex = 1; explanation = "DSCSA requires pharmacies to verify drug product legitimacy through T3 documents: Transaction Information (TI: drug info, quantity, date), Transaction History (TH: prior ownership), and Transaction Statement (TS: attestation of legitimacy). By 2023 (later extended), an interoperable electronic track-and-trace system (serialized, item-level tracking) was implemented."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v8-q90"; versionId = "ptcb-v8"; text = "Which of the following is required to verify the validity of a DEA number? A DEA number consists of 2 letters and 7 digits. Which calculation confirms it is valid?"; options = ["Add all 7 digits; the total must be even", "Add odd-position digits (1,3,5); double the even-position digits (2,4,6) and add them; the last digit of the total should match the 7th (check) digit", "Multiply first letter by 10 and add all digit values", "All DEA numbers with 'B' as the second letter are valid"]; correctOptionIndex = 1; explanation = "DEA number check digit formula: Add digits 1+3+5. Add digits 2+4+6 and multiply by 2. Sum both results. The last digit of this sum must equal the 7th digit of the DEA number. Example: AB1234563 → 1+3+5=9; (2+4+6)x2=24; 9+24=33; last digit=3 = 7th digit confirmed valid. The first letter indicates registrant type (A=hospital, B=physician, etc.)."; knowledgeDomain = #FederalRequirements; isScored = true });
  };
};
