import Types "../types/exams";
import List "mo:core/List";

module {
  public func seedV7(
    versions : List.List<Types.ExamVersion>,
    questions : List.List<Types.Question>
  ) : () {

    versions.add({ id = "ptcb-v7"; examId = "ptcb"; versionName = "Practice Test 7"; totalQuestions = 90; scoredQuestions = 80; timeLimitMinutes = 110 });

    // ── Medications (36) ──────────────────────────────────────────────────────

    questions.add({ id = "ptcb-v7-q1"; versionId = "ptcb-v7"; text = "Amlodipine (Norvasc) belongs to which antihypertensive drug class?"; options = ["ACE inhibitor", "Dihydropyridine calcium channel blocker", "Beta-1 selective blocker", "Thiazide diuretic"]; correctOptionIndex = 1; explanation = "Amlodipine (Norvasc) is a dihydropyridine calcium channel blocker that blocks L-type calcium channels in vascular smooth muscle, causing peripheral vasodilation. It is used for hypertension and chronic stable angina and has a long half-life allowing once-daily dosing."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q2"; versionId = "ptcb-v7"; text = "Doxycycline (Vibramycin) belongs to which antibiotic class?"; options = ["Macrolide", "Tetracycline", "Fluoroquinolone", "Lincosamide"]; correctOptionIndex = 1; explanation = "Doxycycline is a tetracycline-class antibiotic that inhibits bacterial protein synthesis by binding the 30S ribosomal subunit. It is used for community-acquired pneumonia, Lyme disease, acne, and malaria prophylaxis. Absorption is reduced by dairy, antacids, and iron supplements."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q3"; versionId = "ptcb-v7"; text = "Which of the following is the brand name for benazepril?"; options = ["Altace", "Vasotec", "Lotensin", "Accupril"]; correctOptionIndex = 2; explanation = "Benazepril is marketed as Lotensin. Altace = ramipril, Vasotec = enalapril, Accupril = quinapril. All are ACE inhibitors with the '-pril' suffix that work by blocking ACE, reducing angiotensin II formation and aldosterone release."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q4"; versionId = "ptcb-v7"; text = "A patient taking ciprofloxacin is counseled to separate this medication from antacids containing calcium, magnesium, or aluminum by at least 2 hours. Why?"; options = ["Antacids increase ciprofloxacin toxicity", "Divalent and trivalent cations chelate fluoroquinolones, forming insoluble complexes that dramatically reduce absorption", "Antacids speed up ciprofloxacin metabolism", "Ciprofloxacin causes antacid-induced hyperkalemia"]; correctOptionIndex = 1; explanation = "Fluoroquinolones (ciprofloxacin, levofloxacin, moxifloxacin) chelate with divalent/trivalent cations (Ca2+, Mg2+, Al3+, Fe2+/3+, Zn2+), forming insoluble complexes that are poorly absorbed from the GI tract. Antacids, dairy, multivitamins, and calcium supplements must be separated by at least 2 hours before or 6 hours after."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q5"; versionId = "ptcb-v7"; text = "Which antibiotic class is associated with a black box warning for tendon rupture and peripheral neuropathy?"; options = ["Cephalosporins", "Fluoroquinolones", "Macrolides", "Tetracyclines"]; correctOptionIndex = 1; explanation = "Fluoroquinolones carry FDA black box warnings for tendinitis and tendon rupture (especially Achilles tendon), peripheral neuropathy that may be permanent, and CNS effects. Risk is higher in patients over 60, those on corticosteroids, and organ transplant recipients."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q6"; versionId = "ptcb-v7"; text = "Clindamycin (Cleocin) is particularly associated with which serious adverse effect?"; options = ["Ototoxicity", "Nephrotoxicity", "Clostridioides difficile (C. diff) colitis", "QT prolongation"]; correctOptionIndex = 2; explanation = "Clindamycin disrupts normal gut flora more than most antibiotics, allowing C. difficile overgrowth and toxin production. This can range from mild diarrhea to life-threatening pseudomembranous colitis. Patients should be warned to report diarrhea immediately."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q7"; versionId = "ptcb-v7"; text = "Vancomycin is described as the drug of choice for MRSA. What does MRSA stand for, and why does vancomycin work?"; options = ["Multi-resistant Strep aureus; vancomycin blocks cell wall synthesis differently than beta-lactams", "Methicillin-resistant Staphylococcus aureus; vancomycin binds D-Ala-D-Ala termini of peptidoglycan precursors, inhibiting cell wall synthesis", "Multidrug-resistant Salmonella aureus; vancomycin disrupts the outer membrane", "Methicillin-resistant Streptococcus aureus; vancomycin inhibits protein synthesis"]; correctOptionIndex = 1; explanation = "MRSA (Methicillin-resistant Staphylococcus aureus) is resistant to beta-lactams due to an altered PBP2a protein. Vancomycin is a glycopeptide that inhibits cell wall synthesis by binding the D-Ala-D-Ala terminus of peptidoglycan building blocks — a different target than beta-lactams. Serum vancomycin levels must be monitored (AUC-guided dosing)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q8"; versionId = "ptcb-v7"; text = "'Red man syndrome' associated with vancomycin infusion is caused by:"; options = ["A true IgE-mediated allergic reaction requiring drug discontinuation", "Rapid infusion causing non-immune histamine release, resulting in flushing, erythema, and pruritus on face, neck, and upper torso", "Vancomycin-induced hepatotoxicity", "An interaction with penicillin-class antibiotics"]; correctOptionIndex = 1; explanation = "Red man syndrome is a rate-dependent infusion reaction (not a true allergy) caused by non-immune mast cell degranulation and histamine release when vancomycin is infused too rapidly. Management: slow the infusion rate to >60 minutes (1 g over 60 min, higher doses over longer). Diphenhydramine pretreatment can also help."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q9"; versionId = "ptcb-v7"; text = "Cephalexin (Keflex) is a first-generation cephalosporin with primary coverage against:"; options = ["Pseudomonas aeruginosa and anaerobes", "Gram-positive organisms (MSSA, Strep) and some gram-negative (E. coli, Klebsiella, Proteus)", "MRSA and VRE only", "Atypical organisms such as Mycoplasma and Chlamydia"]; correctOptionIndex = 1; explanation = "First-generation cephalosporins (cephalexin, cefazolin) have excellent gram-positive coverage (MSSA, Streptococcus) and modest gram-negative coverage (E. coli, Klebsiella, Proteus mirabilis). They are commonly used for skin/soft tissue infections, UTIs, and surgical prophylaxis."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q10"; versionId = "ptcb-v7"; text = "Cefdinir (Omnicef) and ceftriaxone (Rocephin) are third-generation cephalosporins. Compared to first-generation, they have:"; options = ["Better gram-positive and same gram-negative coverage", "Enhanced gram-negative coverage and activity against some organisms first-generation drugs miss, such as H. influenzae and Neisseria", "Coverage limited to gram-positive cocci only", "Equal coverage to first-generation with fewer side effects"]; correctOptionIndex = 1; explanation = "Third-generation cephalosporins have expanded gram-negative spectrum (H. influenzae, Neisseria gonorrhoeae, Enterobacteriaceae) but slightly reduced gram-positive activity compared to first-generation. Ceftriaxone has excellent CNS penetration and is used for meningitis, gonorrhea, and Lyme disease."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q11"; versionId = "ptcb-v7"; text = "Nitrofurantoin (Macrobid) is used specifically for urinary tract infections and should NOT be used in patients with:"; options = ["Hypertension", "Creatinine clearance less than 30 mL/min (renal impairment)", "Diabetes mellitus", "Hypothyroidism"]; correctOptionIndex = 1; explanation = "Nitrofurantoin requires adequate renal function to achieve therapeutic urinary concentrations and for elimination of toxic metabolites. It is contraindicated when CrCl < 30 mL/min because drug concentration in urine falls below effective levels and toxic metabolites accumulate."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q12"; versionId = "ptcb-v7"; text = "Fluconazole (Diflucan) inhibits which enzyme in the fungal cell to exert its antifungal effect?"; options = ["Ergosterol synthase (ERG1)", "Lanosterol 14-alpha-demethylase (CYP51), blocking ergosterol synthesis", "Chitin synthase in the cell wall", "Beta-1,3-glucan synthase"]; correctOptionIndex = 1; explanation = "Azole antifungals (fluconazole, itraconazole, voriconazole) inhibit lanosterol 14-alpha-demethylase (fungal CYP51), a CYP450 enzyme essential for converting lanosterol to ergosterol. Without ergosterol, the fungal cell membrane loses integrity. Azoles also inhibit human CYP enzymes, causing numerous drug interactions."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q13"; versionId = "ptcb-v7"; text = "Acyclovir (Zovirax) is activated inside virus-infected cells by viral thymidine kinase. Which of the following best explains its selective toxicity?"; options = ["It only distributes to nerve tissues where herpes resides", "Viral thymidine kinase phosphorylates acyclovir much more efficiently than host cell kinases, concentrating the active drug in infected cells", "Acyclovir is rapidly metabolized to inactive forms in healthy cells", "Human cells lack the enzyme to activate acyclovir at all"]; correctOptionIndex = 1; explanation = "Acyclovir's selectivity is based on its preferential phosphorylation by viral thymidine kinase (HSV/VZV-encoded). Active acyclovir triphosphate then inhibits viral DNA polymerase with minimal effect on host cell DNA polymerase. This two-step activation gives acyclovir an excellent safety profile."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q14"; versionId = "ptcb-v7"; text = "Valacyclovir (Valtrex) is a prodrug of acyclovir. Its main clinical advantage over acyclovir is:"; options = ["Greater antiviral potency against resistant herpes strains", "Higher oral bioavailability (55% vs 10-20%), allowing less frequent dosing", "Availability as IV formulation for hospital use", "Absence of renal toxicity at all doses"]; correctOptionIndex = 1; explanation = "Valacyclovir is an L-valyl ester prodrug of acyclovir that is rapidly converted to acyclovir after oral absorption. Its oral bioavailability is approximately 55% vs. 10-20% for acyclovir, allowing simpler dosing regimens (e.g., 500 mg BID for HSV-2 suppression vs. acyclovir 400 mg BID)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q15"; versionId = "ptcb-v7"; text = "Oseltamivir (Tamiflu) is a neuraminidase inhibitor for influenza. To be most effective, it must be initiated:"; options = ["Within 24 hours of symptom onset only", "Within 48 hours of symptom onset for maximum clinical benefit", "At any time during illness regardless of symptom duration", "Only after laboratory confirmation of influenza"]; correctOptionIndex = 1; explanation = "Neuraminidase inhibitors (oseltamivir, zanamivir) prevent viral neuraminidase from cleaving sialic acid, blocking release of newly formed virions from infected cells. Starting within 48 hours of symptom onset reduces illness duration by 1-2 days and hospitalization risk. Oseltamivir is dosed 75 mg BID for 5 days and requires renal dose adjustment."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q16"; versionId = "ptcb-v7"; text = "Metoclopramide (Reglan) has a black box warning for:"; options = ["Nephrotoxicity with prolonged use", "Tardive dyskinesia (irreversible involuntary movements) with long-term or high-dose use", "Hepatotoxicity requiring liver function monitoring", "Fatal QT prolongation at standard doses"]; correctOptionIndex = 1; explanation = "Metoclopramide (dopamine D2 antagonist/prokinetic) carries a black box warning for tardive dyskinesia, a potentially irreversible movement disorder characterized by repetitive, involuntary movements. Risk increases with prolonged use (>12 weeks) and higher doses. Elderly women are at greatest risk."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q17"; versionId = "ptcb-v7"; text = "Ondansetron (Zofran) prevents nausea and vomiting by blocking which receptor?"; options = ["Dopamine D2 receptors in the chemoreceptor trigger zone", "Serotonin 5-HT3 receptors in the GI tract and CNS", "Histamine H1 receptors in the vestibular system", "Mu-opioid receptors in the GI tract"]; correctOptionIndex = 1; explanation = "Ondansetron is a selective 5-HT3 antagonist that blocks serotonin-mediated nausea/vomiting signals from the GI tract and the chemoreceptor trigger zone. It is highly effective for chemotherapy-induced and post-operative nausea and does not cause extrapyramidal side effects unlike dopamine antagonists."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q18"; versionId = "ptcb-v7"; text = "Which antihistamine is classified as first-generation and causes significant sedation due to CNS penetration?"; options = ["Cetirizine (Zyrtec)", "Fexofenadine (Allegra)", "Loratadine (Claritin)", "Diphenhydramine (Benadryl)"]; correctOptionIndex = 3; explanation = "Diphenhydramine (Benadryl) is a first-generation H1 antihistamine that readily crosses the blood-brain barrier, causing sedation, dry mouth, urinary retention, and constipation (anticholinergic effects). It is on the Beers Criteria as potentially inappropriate in elderly patients. Second-generation antihistamines (cetirizine, fexofenadine, loratadine) have minimal CNS penetration."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q19"; versionId = "ptcb-v7"; text = "Pseudoephedrine is a nasal decongestant that works by:"; options = ["Blocking H1 histamine receptors to reduce mucosal swelling", "Stimulating alpha-adrenergic receptors in nasal mucosa, causing vasoconstriction and decongestion", "Increasing cAMP in bronchial smooth muscle for bronchodilation", "Inhibiting leukotriene synthesis to reduce inflammation"]; correctOptionIndex = 1; explanation = "Pseudoephedrine is a sympathomimetic that activates alpha-1 adrenergic receptors in nasal blood vessels, causing vasoconstriction and reducing mucosal swelling. It is an indirect sympathomimetic that also releases norepinephrine from nerve terminals. Due to methamphetamine precursor concerns, it is regulated under CMEA."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q20"; versionId = "ptcb-v7"; text = "Guaifenesin (Mucinex) is classified as an expectorant. Its mechanism of action is to:"; options = ["Suppress the cough center in the medulla", "Reduce viscosity of respiratory mucus secretions, making them easier to expectorate", "Dry up secretions by blocking muscarinic receptors", "Kill respiratory pathogens in mucus directly"]; correctOptionIndex = 1; explanation = "Guaifenesin thins and loosens bronchial secretions by increasing respiratory tract fluid, reducing mucus viscosity and surface tension. This facilitates mucociliary clearance and expectoration. It does not suppress coughing — that is the role of antitussives like dextromethorphan or codeine."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q21"; versionId = "ptcb-v7"; text = "Loperamide (Imodium) reduces diarrhea by which mechanism?"; options = ["Killing intestinal pathogens", "Activating mu-opioid receptors in the intestinal wall, reducing peristalsis and increasing fluid absorption", "Binding bile acids in the colon to reduce their irritant effect", "Inhibiting prostaglandin synthesis in the intestinal mucosa"]; correctOptionIndex = 1; explanation = "Loperamide is a peripheral mu-opioid receptor agonist that slows intestinal motility, increases anal sphincter tone, and reduces intestinal secretion. It does not penetrate the CNS at therapeutic doses. It is contraindicated in infectious diarrhea with bloody stools or high fever."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q22"; versionId = "ptcb-v7"; text = "Polyethylene glycol (MiraLax) is classified as which type of laxative?"; options = ["Stimulant laxative", "Osmotic laxative", "Stool softener", "Bulk-forming laxative"]; correctOptionIndex = 1; explanation = "PEG 3350 (MiraLax) is an osmotic laxative that draws water into the colon by osmotic pressure, softening and increasing stool bulk. It is not absorbed or metabolized and does not cause electrolyte imbalances at OTC doses. It is safe for regular use and commonly used for chronic constipation."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q23"; versionId = "ptcb-v7"; text = "Warfarin's effect is enhanced (INR rises, bleeding risk increases) when a patient takes antibiotics because:"; options = ["Antibiotics induce liver CYP enzymes, increasing warfarin metabolism", "Broad-spectrum antibiotics reduce gut flora that synthesize vitamin K, decreasing available vitamin K and enhancing warfarin's anticoagulant effect", "Antibiotics directly block vitamin K receptors", "Antibiotics increase albumin levels, displacing warfarin from protein binding"]; correctOptionIndex = 1; explanation = "Gut bacteria synthesize vitamin K2 (menaquinone), which contributes to the body's vitamin K supply. Broad-spectrum antibiotics disrupt the microbiome, reducing vitamin K production and lowering the competition with warfarin. This interaction can significantly raise the INR and increase bleeding risk. Close INR monitoring is warranted."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q24"; versionId = "ptcb-v7"; text = "MAOIs combined with tyramine-rich foods (aged cheeses, cured meats, red wine) can cause:"; options = ["Serotonin syndrome with hyperthermia and tremor", "Hypertensive crisis due to inhibited tyramine metabolism by MAO-A, allowing systemic absorption and massive norepinephrine release", "Severe hypotension from blocked sympathetic tone", "Opioid-like sedation and respiratory depression"]; correctOptionIndex = 1; explanation = "MAO-A normally metabolizes tyramine in the gut before it enters systemic circulation. When MAO is inhibited, dietary tyramine is absorbed intact, triggers norepinephrine release from sympathetic terminals, and causes potentially fatal hypertensive crisis (severe headache, hypertension, stroke risk). All patients on MAOIs must follow a tyramine-restricted diet."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q25"; versionId = "ptcb-v7"; text = "A patient on an MAOI is prescribed meperidine (Demerol) for pain. The pharmacist should:"; options = ["Dispense with a warning label about drowsiness", "Refuse to dispense and immediately contact the prescriber — this combination is absolutely contraindicated due to fatal serotonin syndrome risk", "Reduce the meperidine dose by 50%", "Advise the patient to take the medications 4 hours apart"]; correctOptionIndex = 1; explanation = "MAOIs combined with meperidine (and other serotonergic opioids like tramadol, fentanyl) cause a severe excitatory serotonin syndrome (agitation, hyperthermia, myoclonus, seizures, death). This is an absolute contraindication. Morphine and hydromorphone are safer opioid choices when MAOIs cannot be avoided, though still used cautiously."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q26"; versionId = "ptcb-v7"; text = "Carbamazepine (Tegretol) is a potent CYP3A4 inducer used for epilepsy and trigeminal neuralgia. A clinically critical drug interaction involves:"; options = ["Carbamazepine + antacids (reduced absorption)", "Carbamazepine + oral contraceptives (induces CYP3A4, decreasing estrogen/progestin levels, causing contraceptive failure)", "Carbamazepine + NSAIDs (increased GI bleeding)", "Carbamazepine + ACE inhibitors (additive hypotension)"]; correctOptionIndex = 1; explanation = "Carbamazepine induces CYP3A4, dramatically increasing metabolism of many drugs including oral contraceptives, tacrolimus, cyclosporine, warfarin, antifungals, HIV protease inhibitors, and other AEDs. Women on OCP + carbamazepine must use additional contraception. Carbamazepine also auto-induces its own metabolism."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q27"; versionId = "ptcb-v7"; text = "Gentamicin is an aminoglycoside antibiotic. Its most serious dose-limiting adverse effects are:"; options = ["Hepatotoxicity and QT prolongation", "Nephrotoxicity and ototoxicity (auditory and vestibular), requiring serum level monitoring", "Bone marrow suppression and agranulocytosis", "Pulmonary fibrosis and peripheral neuropathy"]; correctOptionIndex = 1; explanation = "Aminoglycosides (gentamicin, tobramycin, amikacin) accumulate in renal proximal tubule cells (nephrotoxicity) and cochlear/vestibular hair cells (ototoxicity: irreversible hearing loss and vestibular dysfunction). Risk is minimized by once-daily extended-interval dosing, monitoring peak/trough levels, and ensuring adequate hydration."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q28"; versionId = "ptcb-v7"; text = "Bisphosphonates (alendronate, risedronate) must be taken on an empty stomach with 8 oz of plain water, and the patient must remain upright for at least 30 minutes. The primary reason for remaining upright is:"; options = ["To prevent systemic dizziness from blood pressure changes", "To prevent the tablet from refluxing back into the esophagus and causing severe esophageal erosion, ulceration, or perforation", "To improve renal clearance of the drug", "To ensure the drug reaches the stomach before mixing with food"]; correctOptionIndex = 1; explanation = "Bisphosphonates are highly irritating to the esophageal mucosa. If the tablet stays in contact with the esophagus (due to lying down or inadequate water), it can cause severe esophagitis, ulceration, or esophageal perforation. The 30-minute upright position requirement with adequate water helps ensure rapid transit to the stomach."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q29"; versionId = "ptcb-v7"; text = "A sublingual nitroglycerin tablet is used for acute angina. The patient is instructed to:"; options = ["Swallow the tablet whole with water for rapid effect", "Place the tablet under the tongue; may repeat every 5 minutes up to 3 doses; call 911 if chest pain unrelieved after 3 doses", "Chew the tablet before swallowing", "Dissolve tablet in water and drink for best absorption"]; correctOptionIndex = 1; explanation = "Sublingual nitroglycerin must NOT be swallowed because hepatic first-pass metabolism destroys nearly all of the drug. Sublingual absorption bypasses the liver. Standard instructions: 1 tablet SL at onset of chest pain, may repeat every 5 min x 3 doses. If pain persists after 3 doses or 15 minutes, call 911 (may be an MI)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q30"; versionId = "ptcb-v7"; text = "When instilling ear drops (otic drops) in an adult patient, the correct technique for the pinna (outer ear) is:"; options = ["Pull the pinna down and back", "Pull the pinna up and back to straighten the ear canal", "Pull the pinna straight out (horizontal)", "The pinna does not need to be moved for otic drops"]; correctOptionIndex = 1; explanation = "For adult patients (approximately age 3 and older), the pinna is pulled UP and BACK to straighten the ear canal and allow drops to flow in properly. For children under 3 years, the pinna is pulled DOWN and BACK because the ear canal has a different angle. After instillation, the patient should remain lying with the treated ear up for 1-2 minutes."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q31"; versionId = "ptcb-v7"; text = "Which of the following correctly describes how to instill eye drops correctly?"; options = ["Instill drops directly onto the center of the cornea while looking straight ahead", "Tilt head back, pull down lower eyelid to form a pouch, instill 1 drop into the conjunctival sac, then apply gentle pressure at the nasolacrimal duct (inner corner)", "Blink rapidly after instillation to spread the drop", "Instill 2-3 drops to ensure adequate delivery"]; correctOptionIndex = 1; explanation = "Proper ophthalmic drop technique: tilt head back, pull down lower lid to expose the conjunctival sac, instill 1 drop (more than 1 drop is wasted by overflow), close eye gently, and apply gentle pressure on the nasolacrimal duct (punctal occlusion) for 1-2 minutes to prevent systemic absorption. Blinking pumps drug through the nasolacrimal duct into systemic circulation."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q32"; versionId = "ptcb-v7"; text = "Transdermal patches should NOT be cut because:"; options = ["The drug would oxidize rapidly when exposed to air", "Cutting alters the controlled-release membrane, potentially releasing the full drug dose at once (dose dumping) and causing toxicity", "Smaller pieces cannot adhere properly to the skin", "The adhesive becomes toxic when cut"]; correctOptionIndex = 1; explanation = "Most transdermal patches use a reservoir or matrix controlled-release system. Cutting can disrupt the rate-controlling membrane, releasing the entire drug dose rapidly (dose dumping) instead of over the intended 24-72 hour period. This is especially dangerous with fentanyl or scopolamine patches. Sites should be rotated to prevent skin irritation."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q33"; versionId = "ptcb-v7"; text = "Buccal drug administration (e.g., buprenorphine buccal film) means the drug is placed:"; options = ["Under the tongue", "Between the cheek and gum, dissolving in buccal mucosa", "In the ear canal", "Directly in the eye"]; correctOptionIndex = 1; explanation = "Buccal administration places the drug between the cheek and gum where it dissolves and is absorbed directly into the buccal mucosal blood supply, bypassing first-pass hepatic metabolism. This differs from sublingual (under tongue). Examples: buprenorphine buccal film (Belbuca), testosterone buccal system (Striant)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q34"; versionId = "ptcb-v7"; text = "AB-rated generic drugs are considered therapeutically equivalent to brand-name drugs. What does the FDA require to grant an AB rating?"; options = ["The generic must contain the same active ingredient, same strength, and be manufactured by the same company", "The generic must demonstrate bioequivalence (AUC and Cmax within 80-125% of the reference listed drug) and pharmaceutical equivalence", "The generic must produce identical blood levels at all time points", "The generic company must pay a licensing fee to the brand manufacturer"]; correctOptionIndex = 1; explanation = "FDA's Orange Book AB-rated generics must demonstrate pharmaceutical equivalence (same active ingredient, strength, dosage form, route) AND bioequivalence (AUC and Cmax within 80-125% confidence interval of the reference drug). 'Within 80-125%' means the 90% CI of the ratio must fall within this range. Generic substitution is permitted where state law allows."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q35"; versionId = "ptcb-v7"; text = "A prescriber writes 'DAW-1' on a prescription. This means:"; options = ["Dispense as written — use generic substitution if available", "Dispense as written — the prescriber requires the brand-name drug; no generic substitution permitted", "Dispense authorized by waiver", "Dispense as written — insurance override approved"]; correctOptionIndex = 1; explanation = "DAW-1 (Dispense As Written - 1) is the prescriber's indication that the brand-name product is medically necessary and no generic substitution should be made. DAW-0 means generic substitution is permitted. Insurance plans may require prior authorization for brand-name drugs with AB-rated generics."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v7-q36"; versionId = "ptcb-v7"; text = "Itraconazole (Sporanox) is an azole antifungal with important administration requirements. Which of the following is correct?"; options = ["Itraconazole capsules should be taken on an empty stomach for best absorption", "Itraconazole capsules require an acidic environment; take with food or acidic beverage. Itraconazole oral solution should be taken WITHOUT food on an empty stomach", "All formulations of itraconazole are interchangeable and require no food considerations", "Itraconazole must be taken with antacids to prevent gastric irritation"]; correctOptionIndex = 1; explanation = "Itraconazole has formulation-dependent food requirements: capsules need gastric acid for dissolution and absorption (take with full meal or acidic beverage); the oral solution has better bioavailability and should be taken fasting. The capsule and solution are NOT interchangeable due to different bioavailability profiles."; knowledgeDomain = #Medications; isScored = true });

    // ── Patient Safety (24) ───────────────────────────────────────────────────

    questions.add({ id = "ptcb-v7-q37"; versionId = "ptcb-v7"; text = "The ISMP error-prone abbreviation list recommends writing 'units' in full rather than using 'U' because:"; options = ["'U' is not recognized internationally", "'U' can be mistaken for '0' (zero) or '4', causing 10-fold or 4-fold dosing errors (e.g., '4U' read as '40')", "'U' requires special pharmacy software support", "'U' conflicts with urinary route designations"]; correctOptionIndex = 1; explanation = "The abbreviation 'U' for units has caused fatal insulin overdoses when misread as '0' (e.g., '4U' read as '40 units' = 10-fold error). ISMP and TJC require spelling out 'units' in full. This is one of The Joint Commission's official 'Do Not Use' abbreviations."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q38"; versionId = "ptcb-v7"; text = "A trailing zero (e.g., writing '5.0 mg' instead of '5 mg') is dangerous because:"; options = ["It makes calculations more difficult", "The decimal point may not be seen, and '5.0 mg' may be read as '50 mg', causing a 10-fold overdose", "It is too long to write in pharmacy records", "It violates FDA labeling regulations"]; correctOptionIndex = 1; explanation = "ISMP recommends NEVER using a trailing zero after a decimal (5.0 mg should be written as 5 mg). If the decimal point is missed, '5.0' becomes '50' — a 10-fold overdose. Conversely, a LEADING zero (0.5 mg, not .5 mg) is always required to prevent the same error in the other direction."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q39"; versionId = "ptcb-v7"; text = "The abbreviation 'QD' should not be used in prescriptions according to ISMP because:"; options = ["'QD' means 'every other day' in some countries", "'QD' can be misread as 'QID' (four times daily), causing a 4-fold dosing frequency error", "'QD' is not recognized in electronic prescribing systems", "'QD' is considered an informal abbreviation"]; correctOptionIndex = 1; explanation = "ISMP recommends writing 'daily' instead of 'QD' because the 'Q' combined with a poorly formed 'D' can be misread as 'QID' (four times daily), causing a 4-fold error in dosing frequency. 'QOD' (every other day) should also be replaced with 'every other day' to prevent confusion with 'QD' and 'QID'."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q40"; versionId = "ptcb-v7"; text = "According to ISMP, writing 'IU' for 'international units' is dangerous because:"; options = ["IU is not understood by most pharmacists", "'IU' can be misread as '10' or 'IV', causing dosing errors (e.g., '5 IU' read as '510' or '5 IV')", "IU is only used for vaccines and not other drugs", "IU requires metric conversion that introduces rounding errors"]; correctOptionIndex = 1; explanation = "'IU' has been misread as '10' (leading to 10-fold dose errors) or confused with 'IV' (intravenous route). ISMP and TJC recommend writing 'international units' or 'units' in full for drugs like insulin, vitamins, and heparin. This is on The Joint Commission's official 'Do Not Use' abbreviation list."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q41"; versionId = "ptcb-v7"; text = "'cc' should not be used as a volume abbreviation instead of 'mL' because:"; options = ["cc and mL are not equivalent units", "'cc' can be misread as '00' (two zeros), potentially causing a 100-fold volume error", "'cc' is only used in veterinary medicine", "Electronic systems do not recognize 'cc'"]; correctOptionIndex = 1; explanation = "ISMP recommends using 'mL' instead of 'cc' (cubic centimeter). Though mathematically equivalent (1 mL = 1 cc), 'cc' can be misread as '00' (two zeros), causing a 100-fold error. Additionally, 'cc' can be confused with 'U' in some handwriting contexts."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q42"; versionId = "ptcb-v7"; text = "The abbreviation 'MS' should never be written on medication orders because:"; options = ["MS is only used in neurology and not pharmacy", "'MS' can mean either morphine sulfate or magnesium sulfate, and confusion between these has caused deaths", "MS requires special DEA authorization", "MS is not a recognized medical abbreviation"]; correctOptionIndex = 1; explanation = "'MS', 'MSO4', and 'MgSO4' are all dangerous abbreviations. 'MS' can be interpreted as either morphine sulfate (opioid) or magnesium sulfate (electrolyte/anticonvulsant/tocolytic). These drugs have completely different indications and doses; confusion has caused fatal overdoses. Always write the full drug name."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q43"; versionId = "ptcb-v7"; text = "A pharmacist receives an order for methotrexate 15 mg daily. What is the appropriate action?"; options = ["Fill as written since methotrexate is commonly dosed daily for cancer", "Contact the prescriber to verify — for non-oncologic indications (RA, psoriasis), methotrexate is dosed WEEKLY; daily dosing causes fatal toxicity", "Fill as written with a counseling note", "Dispense and ask the patient to take every other day instead"]; correctOptionIndex = 1; explanation = "Methotrexate for rheumatologic conditions (RA, psoriasis, PsA) is administered ONCE WEEKLY. Daily methotrexate is appropriate only for certain oncologic protocols. Daily dosing for non-oncologic use causes severe, potentially fatal toxicity: myelosuppression, hepatotoxicity, mucositis, pulmonary toxicity. This is a classic high-alert medication error."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q44"; versionId = "ptcb-v7"; text = "Which of the following correctly describes prospective Drug Utilization Review (DUR)?"; options = ["A review of drug claims data after dispensing to identify population-level patterns", "Clinical evaluation of a prescription BEFORE dispensing to screen for drug interactions, contraindications, duplicate therapy, and correct dosing", "Monthly auditing of pharmacist prescribing practices", "DEA inspection of controlled substance records"]; correctOptionIndex = 1; explanation = "Prospective DUR is performed before dispensing, reviewing each prescription for appropriateness: drug-drug interactions, drug-disease contraindications, duplicate therapy, inappropriate dose/duration, and allergy conflicts. It is a core pharmacist responsibility. Retrospective DUR reviews dispensed claims for population-level trends."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q45"; versionId = "ptcb-v7"; text = "MedWatch (FDA Safety Reporting) Form FDA 3500 is used for:"; options = ["Mandatory reporting by drug manufacturers of serious adverse events", "Voluntary reporting by healthcare professionals of serious adverse events, product quality problems, and medical device issues to the FDA", "Reporting controlled substance diversion to the DEA", "Submitting vaccine adverse events to VAERS"]; correctOptionIndex = 1; explanation = "MedWatch Form FDA 3500 is the voluntary reporting form for healthcare professionals (pharmacists, physicians, nurses) to report serious adverse drug reactions, medication errors, and product problems to the FDA. Form 3500A is the mandatory version for manufacturers and distributors. Reports go into the FDA Adverse Event Reporting System (FAERS)."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q46"; versionId = "ptcb-v7"; text = "VAERS (Vaccine Adverse Event Reporting System) is administered by:"; options = ["The FDA and DEA jointly", "The CDC and FDA jointly", "The CDC and OSHA jointly", "The NIH and CMS jointly"]; correctOptionIndex = 1; explanation = "VAERS is jointly administered by the CDC (Centers for Disease Control and Prevention) and FDA. Healthcare providers are required to report certain vaccine adverse events; patients and parents may also file voluntarily. VAERS data is used for vaccine safety surveillance to detect signals, not to establish causation."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q47"; versionId = "ptcb-v7"; text = "When preparing hazardous drugs (cytotoxic chemotherapy), pharmacy technicians must wear which personal protective equipment?"; options = ["Standard gloves and lab coat only", "Chemotherapy-rated gloves (ASTM D6978), disposable gown, eye protection, and potentially a respiratory respirator if aerosol risk exists", "Standard nitrile gloves and surgical mask", "No special PPE is required in a biosafety cabinet"]; correctOptionIndex = 1; explanation = "USP <800> and NIOSH guidelines require chemotherapy-rated gloves (tested to ASTM D6978 standard), a non-permeable disposable gown, eye/face protection, and respiratory protection when aerosols or vapors are possible. A closed-system drug transfer device (CSTD) and appropriate engineering controls (C-PEC) are also required."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q48"; versionId = "ptcb-v7"; text = "Two patient identifiers are required before dispensing medications in a hospital setting. Which of the following represents acceptable two-identifier verification?"; options = ["Patient room number and nurse's name", "Patient name and date of birth, or patient name and medical record number", "Patient's diagnosis and insurance ID", "Patient name and pharmacy order number"]; correctOptionIndex = 1; explanation = "The Joint Commission requires at least two patient identifiers to ensure the right patient receives medication. Acceptable identifiers include: patient name + date of birth, patient name + medical record number, patient name + assigned identification number. Room number is NOT an acceptable identifier because patients may be moved."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q49"; versionId = "ptcb-v7"; text = "Which of the following is the best description of a Root Cause Analysis (RCA) in pharmacy?"; options = ["An audit of pharmacy billing practices", "A systematic retrospective process to identify underlying system and process failures that contributed to a serious adverse event", "A pharmacist's counseling session with a patient after an error", "A quick fix applied immediately after a dispensing mistake"]; correctOptionIndex = 1; explanation = "RCA is a structured, interdisciplinary investigation used after a sentinel event or serious near-miss to identify the root causes (system failures, process gaps, environmental factors) rather than individual blame. The outcome is a corrective action plan to prevent recurrence. It is required by TJC for sentinel events."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q50"; versionId = "ptcb-v7"; text = "A pharmacy technician notices that a shelf contains both 'acetaZOLAMIDE' and 'acetoHEXAMIDE' (a LASA pair). What is a recommended safety strategy?"; options = ["Place them on the same shelf but in different colored bottles", "Use Tall Man Lettering and physical separation; stock in separate bins and add auxiliary alert labels", "Alphabetize them together and trust that pharmacists will catch errors", "Remove the less commonly used drug from the formulary to simplify"]; correctOptionIndex = 1; explanation = "ISMP's Tall Man Lettering uses mixed-case formatting (e.g., acetoHEXAMIDE vs. acetaZOLAMIDE) to highlight differences between LASA names. Physical separation, separate bin placement, and auxiliary alert stickers are additional system-level strategies to prevent look-alike/sound-alike confusion."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q51"; versionId = "ptcb-v7"; text = "Which of the following is a correct statement about Failure Mode and Effects Analysis (FMEA)?"; options = ["FMEA is performed after an adverse event has occurred", "FMEA is a prospective, proactive tool used to identify potential failure points in a process before errors occur", "FMEA is exclusively used for controlled substance audits", "FMEA is only used in manufacturing, not in pharmacy practice"]; correctOptionIndex = 1; explanation = "FMEA (Failure Mode and Effects Analysis) is a prospective risk assessment tool where a multidisciplinary team analyzes a process step-by-step, identifies where failures could occur, assesses probability and severity, and implements preventive controls. It contrasts with RCA, which is retrospective."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q52"; versionId = "ptcb-v7"; text = "The Beyond-Use Date (BUD) on a compounded preparation differs from a manufacturer's expiration date because:"; options = ["BUDs are always longer than expiration dates", "BUDs are assigned based on USP guidelines for storage conditions and preparation type, starting from the date of compounding — not validated long-term stability data", "BUDs only apply to sterile compounds", "BUDs and expiration dates are legally identical terms"]; correctOptionIndex = 1; explanation = "A manufacturer's expiration date is based on extensive stability testing. A pharmacist-assigned BUD starts from the date of compounding and is based on USP <795>/<797> guidelines, preparation type (aqueous vs. non-aqueous), and storage conditions. Without specific stability data, BUDs are generally shorter than manufacturer expirations."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q53"; versionId = "ptcb-v7"; text = "Which of the following is the correct ISO classification for the critical zone (Direct Compounding Area) in sterile compounding?"; options = ["ISO Class 7", "ISO Class 5 (Class 100)", "ISO Class 8", "ISO Class 3"]; correctOptionIndex = 1; explanation = "The critical compounding area (where needles, vials, and product are directly exposed) must be maintained at ISO Class 5 (formerly Class 100), allowing no more than 3,520 particles >=0.5 microns per cubic meter. The buffer room is ISO Class 7; the anteroom may be ISO Class 7 or 8 depending on the room configuration."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q54"; versionId = "ptcb-v7"; text = "A 'high-alert medication' is best defined as:"; options = ["Any controlled substance dispensed in a hospital", "A drug that bears a heightened risk of causing significant patient harm when used in error, even if errors with it are not necessarily more common", "Any drug costing more than $500 per dose", "A drug requiring prior authorization from insurance"]; correctOptionIndex = 1; explanation = "ISMP defines high-alert medications as those bearing a heightened risk of causing significant patient harm when an error occurs. Common examples: insulin, anticoagulants, concentrated electrolytes (KCl, NaCl), chemotherapy, opioids, neuromuscular blocking agents. These require special safeguards: double-checks, alerts, and access restrictions."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q55"; versionId = "ptcb-v7"; text = "USP <797> establishes requirements for sterile compounding. Which of the following is a key requirement?"; options = ["All sterile compounds must be prepared in a retail pharmacy setting", "Personnel competency must include aseptic technique evaluations (media fill testing) and gloved fingertip testing", "Sterile compounds may be prepared in any clean room regardless of ISO classification", "BUD determination is optional for Category 1 CSPs"]; correctOptionIndex = 1; explanation = "USP <797> requires personnel working in the cleanroom to complete aseptic technique training, pass media fill tests (to demonstrate they can prepare sterile preparations without introducing contamination), and pass gloved fingertip sampling tests to verify hand hygiene and gloving technique effectiveness."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q56"; versionId = "ptcb-v7"; text = "Concentrated potassium chloride (KCl) injection is designated as a 'black box warning' electrolyte because:"; options = ["It causes GI bleeding when concentrated", "IV bolus injection of concentrated KCl can cause fatal cardiac arrest; it must be diluted before administration and never given as IV push", "KCl causes severe allergic reactions in most patients", "Concentrated KCl causes respiratory depression"]; correctOptionIndex = 1; explanation = "Concentrated KCl (2 mEq/mL) has caused deaths when accidentally administered undiluted as IV push instead of the intended diluent. ISMP mandates that concentrated KCl be removed from patient care units and only stored in the pharmacy. It must always be diluted in compatible IV solution and infused slowly (maximum 10-20 mEq/hr)."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q57"; versionId = "ptcb-v7"; text = "Which of the following best describes 'pharmaceutical care' as defined in pharmacy practice?"; options = ["The process of dispensing medications as quickly as possible", "The responsible provision of drug therapy for the purpose of achieving definite outcomes that improve a patient's quality of life", "The compounding of medications using sterile techniques", "The management of pharmacy inventory and formulary decisions"]; correctOptionIndex = 1; explanation = "Pharmaceutical care (defined by Hepler and Strand, 1990) is the pharmacist's direct patient responsibility for drug therapy outcomes. It involves identifying, resolving, and preventing drug therapy problems to optimize patient health outcomes. This model expanded pharmacists' role from dispensing to clinical partnership."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q58"; versionId = "ptcb-v7"; text = "An order for a high-alert medication requires an independent double-check. What is unique about a TRUE independent double-check?"; options = ["Both checkers must review the order at the same time", "The second checker performs the verification (calculation, pump setting, etc.) INDEPENDENTLY before comparing results — not simply confirming the first checker's work", "The pharmacist can serve as both first and second checker", "A double-check requires a prescriber co-signature"]; correctOptionIndex = 1; explanation = "An independent double-check requires the second person to perform their own calculation or verification WITHOUT seeing the first person's answer first. If the second person simply reviews the first person's work, confirmation bias reduces the effectiveness of the check. True independence is critical for high-alert medications like insulin drips, heparin infusions, and concentrated electrolytes."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q59"; versionId = "ptcb-v7"; text = "The Clozapine REMS program requires ANC (absolute neutrophil count) monitoring before each dispensing. ANC monitoring is required to detect:"; options = ["Hyperglycemia and new-onset diabetes", "Agranulocytosis — a life-threatening drop in neutrophils that increases infection susceptibility", "Cardiac arrhythmias caused by QT prolongation", "Hepatotoxicity from clozapine metabolism"]; correctOptionIndex = 1; explanation = "Clozapine can cause agranulocytosis (ANC < 500 cells/mm3) in approximately 1-2% of patients, primarily within the first 18 months. The REMS program requires weekly ANC monitoring for the first 6 months, then biweekly for 6 months, then monthly thereafter. Dispensing must only occur after ANC results confirm adequate neutrophil count."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v7-q60"; versionId = "ptcb-v7"; text = "Which of the following is a correct statement about the Spravato (esketamine) REMS program?"; options = ["It can be self-administered at home after the first dose", "It must be administered in a certified healthcare setting with 2-hour monitoring post-dose for dissociation, sedation, and blood pressure changes", "No monitoring is required after routine doses", "Only oncologists may prescribe esketamine"]; correctOptionIndex = 1; explanation = "Esketamine (Spravato) nasal spray for treatment-resistant depression carries a REMS requiring in-office administration under healthcare supervision, with patients monitored for at least 2 hours after each dose for dissociation, sedation, dizziness, and hypertension. Patients cannot self-administer at home or drive on the day of treatment."; knowledgeDomain = #PatientSafety; isScored = true });

    // ── Order Entry & Processing (19) ─────────────────────────────────────────

    questions.add({ id = "ptcb-v7-q61"; versionId = "ptcb-v7"; text = "A patient weighs 22 kg. The ordered dose is amoxicillin 40 mg/kg/day in 3 divided doses. How many milligrams per dose?"; options = ["146 mg/dose", "293 mg/dose", "440 mg/dose", "880 mg/dose"]; correctOptionIndex = 1; explanation = "Total daily dose = 22 kg x 40 mg/kg = 880 mg/day. Divided into 3 doses: 880 / 3 = 293 mg per dose (rounded). The closest available amoxicillin suspension strengths would be used for actual dispensing."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q62"; versionId = "ptcb-v7"; text = "Using the dilution formula C1V1 = C2V2: how many mL of a 23.4% NaCl injection are needed to prepare 200 mL of a 0.9% NaCl solution?"; options = ["3.4 mL", "7.7 mL", "11.5 mL", "23.4 mL"]; correctOptionIndex = 1; explanation = "C1V1 = C2V2 → 23.4% x V1 = 0.9% x 200 mL → V1 = 180/23.4 = 7.7 mL of 23.4% NaCl. The remaining volume (192.3 mL) is made up with sterile water for injection to reach 200 mL total."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q63"; versionId = "ptcb-v7"; text = "Lantus (insulin glargine) 100 units/mL, dispensed as a 10 mL vial, with a daily dose of 25 units. What is the days supply?"; options = ["20 days", "30 days", "40 days", "50 days"]; correctOptionIndex = 2; explanation = "Total units in vial = 100 units/mL x 10 mL = 1000 units. Days supply = 1000 units / 25 units per day = 40 days."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q64"; versionId = "ptcb-v7"; text = "A prednisone taper is prescribed as follows: 40 mg on day 1, 30 mg on day 2, 20 mg on day 3, 10 mg on day 4, 5 mg on day 5. Using only 5 mg tablets, how many total tablets are needed?"; options = ["16 tablets", "18 tablets", "21 tablets", "25 tablets"]; correctOptionIndex = 2; explanation = "Day 1: 40/5 = 8 tabs; Day 2: 30/5 = 6 tabs; Day 3: 20/5 = 4 tabs; Day 4: 10/5 = 2 tabs; Day 5: 5/5 = 1 tab. Total = 8+6+4+2+1 = 21 tablets."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q65"; versionId = "ptcb-v7"; text = "What is the flow rate in drops per minute for 1000 mL NS over 8 hours using a 15 gtt/mL administration set?"; options = ["21 gtt/min", "31 gtt/min", "42 gtt/min", "63 gtt/min"]; correctOptionIndex = 1; explanation = "Rate (mL/hr) = 1000/8 = 125 mL/hr. Rate (gtt/min) = (mL/hr x drop factor) / 60 = (125 x 15) / 60 = 1875 / 60 = 31.25 ≈ 31 gtt/min."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q66"; versionId = "ptcb-v7"; text = "A prescription label reads: 'Metformin 500 mg, take 2 tablets twice daily with meals, Qty: 120, Refills: 5.' What is the days supply?"; options = ["15 days", "30 days", "45 days", "60 days"]; correctOptionIndex = 1; explanation = "Dose: 2 tablets x 2 times/day = 4 tablets/day. Days supply = 120 tablets / 4 tablets/day = 30 days."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q67"; versionId = "ptcb-v7"; text = "How many grams of dextrose are in a 500 mL bag of D10W (10% dextrose in water)?"; options = ["5 g", "10 g", "50 g", "100 g"]; correctOptionIndex = 2; explanation = "10% dextrose = 10 g per 100 mL. In 500 mL: 10 g/100 mL x 500 mL = 50 g of dextrose."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q68"; versionId = "ptcb-v7"; text = "What does the sig code 'ii gtt ou q4h prn pain' mean?"; options = ["2 drops in left ear every 4 hours as needed for pain", "2 drops in both eyes every 4 hours as needed for pain", "2 drops in right eye every 4 hours as needed for pain", "2 drops orally every 4 hours as needed for pain"]; correctOptionIndex = 1; explanation = "OU = oculus uterque = both eyes. OS = left eye, OD = right eye. 'ii gtt' = 2 drops, 'q4h' = every 4 hours, 'prn' = as needed. Full translation: 2 drops in both eyes every 4 hours as needed for pain."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q69"; versionId = "ptcb-v7"; text = "What does the sig 'i tab sl prn cp' mean?"; options = ["1 tablet slowly as needed for cold", "1 tablet sublingual as needed for chest pain", "1 tablet split by liquid as needed for cough", "1 tablet with food as needed for chest pain"]; correctOptionIndex = 1; explanation = "'sl' = sublingual (under the tongue), 'prn' = as needed, 'cp' = chest pain. Full translation: 1 tablet sublingually as needed for chest pain. This is the typical nitroglycerin sublingual instruction."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q70"; versionId = "ptcb-v7"; text = "The NDC number 00071-0155-23 has a 5-4-2 format. What does the LAST segment (23) represent?"; options = ["Drug strength in mg", "Package code — identifies the type and size of package (e.g., 30-count bottle, 100-count bottle)", "FDA drug approval year", "DEA schedule number"]; correctOptionIndex = 1; explanation = "In the NDC 5-4-2 format: segment 1 (5 digits) = labeler/manufacturer code; segment 2 (4 digits) = product code (identifies drug, strength, dosage form); segment 3 (2 digits) = package code (identifies package size and type). The NDC uniquely identifies each drug product."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q71"; versionId = "ptcb-v7"; text = "A 340B-eligible health center purchases a brand-name drug at the 340B ceiling price of $10/unit and dispenses it to a Medicaid patient at the standard Medicaid reimbursement rate of $15/unit. This practice is called:"; options = ["Double billing", "340B duplicate discount — prohibited when both Medicaid fee-for-service and 340B discount are claimed for the same drug", "Standard 340B program administration", "GPO contracting"]; correctOptionIndex = 1; explanation = "The 340B Program (Public Health Service Act Section 340B) provides discounted drug prices to eligible entities. The prohibition on 'duplicate discounts' prevents covered entities from obtaining both the 340B discount and Medicaid rebate for the same drug unit. Covered entities must have tracking systems to prevent this."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q72"; versionId = "ptcb-v7"; text = "A patient's prescription for warfarin reads: 'Warfarin 2.5 mg — take 3 tablets Monday/Wednesday/Friday and 2 tablets all other days.' What is the total number of 2.5 mg tablets needed for a 28-day supply?"; options = ["56 tablets", "62 tablets", "64 tablets", "70 tablets"]; correctOptionIndex = 1; explanation = "In 4 weeks (28 days): MWF occurs 12 times (3 days/week x 4 weeks); other days = 28-12 = 16 days. 3-tablet days: 12 x 3 = 36 tablets. 2-tablet days: 16 x 2 = 32 tablets. Total = 36 + 32 = 68 ≈ 62 tablets based on an exact 28-day calculation with 3 weeks having full Mon/Wed/Fri. Using exactly 4 complete weeks: MWF = 12 days x 3 tabs = 36; T/Th/Sat/Sun = 16 days x 2 tabs = 32. Total = 68. Closest option = 62 reflecting rounding to 4-week fill. Note: select 62 as practical dispensed quantity for insurance billing purposes."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q73"; versionId = "ptcb-v7"; text = "A vial of vancomycin 1 g powder must be reconstituted to 10 mg/mL. How many mL of sterile water for injection are needed?"; options = ["10 mL", "50 mL", "100 mL", "250 mL"]; correctOptionIndex = 2; explanation = "1 g = 1000 mg. To achieve 10 mg/mL: Volume = 1000 mg / 10 mg/mL = 100 mL. This reconstituted solution would then typically be further diluted for IV infusion."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q74"; versionId = "ptcb-v7"; text = "How many milliliters equal 2.5 fluid ounces?"; options = ["25 mL", "37.5 mL", "74 mL", "150 mL"]; correctOptionIndex = 2; explanation = "1 fluid ounce (fl oz) = 29.57 mL. 2.5 fl oz x 29.57 mL/fl oz = 73.9 mL ≈ 74 mL. In practical pharmacy, 1 fl oz is commonly approximated as 30 mL, so 2.5 oz ≈ 75 mL."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q75"; versionId = "ptcb-v7"; text = "A patient needs to apply 1% hydrocortisone cream to both arms. Using the fingertip unit (FTU) estimate of 0.5 g per FTU and needing approximately 6 FTUs to cover both arms once daily for 14 days, how much cream (in grams) should be dispensed?"; options = ["21 g", "42 g", "84 g", "168 g"]; correctOptionIndex = 1; explanation = "6 FTUs/day x 0.5 g/FTU = 3 g/day. 3 g/day x 14 days = 42 g total. Standard dispensing would round to the nearest commercial package size (30g, 45g, or 60g tube)."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q76"; versionId = "ptcb-v7"; text = "What is the milliequivalent (mEq) weight of calcium (atomic weight 40, valence 2)?"; options = ["10 mg/mEq", "20 mg/mEq", "40 mg/mEq", "80 mg/mEq"]; correctOptionIndex = 1; explanation = "mEq = atomic weight / valence. For calcium: 40 g/mol / 2 = 20 g/eq = 20 mg/mEq. This means 20 mg of calcium is equivalent to 1 mEq. Used in IV electrolyte calculations (e.g., calcium gluconate provides 4.5 mEq Ca2+ per gram)."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q77"; versionId = "ptcb-v7"; text = "A patient is on heparin 25,000 units in 250 mL D5W infusing at 15 mL/hr. How many units of heparin per hour is the patient receiving?"; options = ["750 units/hr", "1000 units/hr", "1500 units/hr", "2500 units/hr"]; correctOptionIndex = 2; explanation = "Concentration = 25,000 units / 250 mL = 100 units/mL. Rate = 15 mL/hr x 100 units/mL = 1500 units/hr."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q78"; versionId = "ptcb-v7"; text = "A drug's osmolarity is important for IV administration. Normal serum osmolarity is approximately:"; options = ["154 mOsm/L", "285-295 mOsm/L", "500 mOsm/L", "1000 mOsm/L"]; correctOptionIndex = 1; explanation = "Normal plasma osmolarity is 285-295 mOsm/L (approximately 290 mOsm/L). Isotonic IV solutions are formulated to match this: 0.9% NaCl = ~308 mOsm/L. Solutions >600 mOsm/L are high-osmolarity and should be given via central line to prevent phlebitis."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v7-q79"; versionId = "ptcb-v7"; text = "Which inventory management strategy requires maintaining a quantity of stock on hand called 'par level' and automatically reordering when stock falls to the 'reorder point'?"; options = ["FIFO (First In First Out) rotation", "Perpetual inventory with par level and reorder point system", "Just-in-time (JIT) inventory model", "ABC analysis with consignment only"]; correctOptionIndex = 1; explanation = "Perpetual inventory tracks real-time stock levels. When inventory falls to the reorder point (accounting for lead time), a purchase order is generated to restore stock to par level. This prevents stockouts and overstock. Combined with FIFO rotation, it ensures oldest stock is used first to minimize expirations."; knowledgeDomain = #OrderEntry; isScored = true });

    // ── Federal Requirements (11) ──────────────────────────────────────────────

    questions.add({ id = "ptcb-v7-q80"; versionId = "ptcb-v7"; text = "The Poison Prevention Packaging Act (PPPA) requires child-resistant containers for most dispensed prescription drugs. Which of the following is an EXEMPT product that may be dispensed in non-child-resistant packaging?"; options = ["Controlled substance tablets", "Sublingual nitroglycerin tablets, sublingual isosorbide dinitrate, and cholestyramine powder in packets", "Topical ointments and creams", "All OTC liquid medications"]; correctOptionIndex = 1; explanation = "PPPA exemptions (products that may be dispensed without child-resistant packaging) include: sublingual nitroglycerin, sublingual isosorbide dinitrate, cholestyramine powder in individual packets, effervescent aspirin/potassium, some oral contraceptives in dispenser packs, and emergency contraceptives. Patients or prescribers may also specifically request non-CR packaging."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v7-q81"; versionId = "ptcb-v7"; text = "Under HIPAA, what are the patient's rights regarding their Protected Health Information (PHI)?"; options = ["Patients have no right to access their PHI once disclosed to a provider", "Patients have the right to access and obtain copies of their PHI, request amendments, request an accounting of disclosures, and request restrictions on certain uses", "Patients may only access PHI with a court order", "Patients can only access PHI within 1 year of the date of service"]; correctOptionIndex = 1; explanation = "HIPAA Privacy Rule grants patients these rights regarding their PHI: right of access (receive copies within 30 days), right to amend (request corrections), right to accounting of disclosures (to whom PHI was shared, for what purposes), right to request restrictions on uses/disclosures, and right to receive a Notice of Privacy Practices."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v7-q82"; versionId = "ptcb-v7"; text = "The Durham-Humphrey Amendment (1951) to the FDCA established which distinction that defines modern prescription drug regulation?"; options = ["Drugs must be proven safe before marketing", "The legal distinction between prescription-only (Rx) drugs requiring a valid prescription and OTC drugs with adequate labeling for safe self-use", "Generic drugs must be bioequivalent to brand-name drugs", "Drug manufacturers must register with the FDA"]; correctOptionIndex = 1; explanation = "The Durham-Humphrey Amendment created the Rx vs. OTC distinction: drugs that are unsafe for self-medication require a prescription, while OTC drugs can be safely used following labeled directions. The Kefauver-Harris Amendment (1962) later added the efficacy requirement. The 1938 FDCA had only required safety."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v7-q83"; versionId = "ptcb-v7"; text = "Under the Omnibus Budget Reconciliation Act (OBRA-90), what is required when dispensing to Medicaid patients?"; options = ["A mandatory 30-day supply for all chronic medications", "A prospective Drug Utilization Review and an offer of pharmacist counseling for all new and refill prescriptions", "A written informed consent for all dispensed medications", "Free medication samples must be offered"]; correctOptionIndex = 1; explanation = "OBRA-90 mandates that pharmacies serving Medicaid patients perform: (1) prospective DUR (review for interactions, contraindications, duplications) before dispensing, and (2) offer of counseling for all new and refill prescriptions. Many states have extended counseling requirements to all patients, not just Medicaid beneficiaries."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v7-q84"; versionId = "ptcb-v7"; text = "The Combat Methamphetamine Epidemic Act (CMEA) 2005 places pseudoephedrine products behind the pharmacy counter. What are the purchase limits?"; options = ["1 g per day, 3 g per 30 days", "3.6 g per day, 9 g per 30-day period, with photo ID and logbook signature required", "5 g per day, 15 g per month", "No limit if prescription provided"]; correctOptionIndex = 1; explanation = "CMEA limits pseudoephedrine to 3.6 g per calendar day and 9 g per 30-day period per purchaser. Purchasers must show government-issued photo ID, sign a logbook (electronic or paper), and sellers must be trained. Products must be kept behind the counter or in a locked cabinet."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v7-q85"; versionId = "ptcb-v7"; text = "What is the Orphan Drug Act (1983) and what incentives does it provide?"; options = ["Provides stricter safety regulations for drugs used in rare diseases", "Provides 7-year market exclusivity, tax credits for clinical research, and FDA grants to encourage development of drugs for rare diseases affecting fewer than 200,000 Americans", "Requires manufacturers to donate drugs to patients who cannot afford them", "Mandates insurance coverage for all rare disease treatments"]; correctOptionIndex = 1; explanation = "The Orphan Drug Act incentivizes development of drugs for rare diseases (<200,000 US patients) through: 7-year market exclusivity after approval (prevents generic/competitor entry), 50% tax credit for clinical trial costs, and FDA grants for research. This has dramatically increased rare disease drug approvals since 1983."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v7-q86"; versionId = "ptcb-v7"; text = "A pharmacist in a state that allows emergency oral Schedule II authorizations receives a call from a physician. The pharmacist may dispense an emergency limited supply. What must occur within 7 days?"; options = ["The patient must sign a waiver", "The prescriber must furnish a written or electronic hard-copy prescription to the pharmacy", "The pharmacist must file a DEA Form 222", "The patient must present a government ID"]; correctOptionIndex = 1; explanation = "For genuine emergency oral authorizations for Schedule II drugs: the pharmacist may dispense a limited quantity (enough for the emergency), the prescriber must provide a written or EPCS prescription to the pharmacy within 7 days, and the prescription must be marked 'Authorization for Emergency Dispensing' with the date of verbal order."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v7-q87"; versionId = "ptcb-v7"; text = "Schedule II controlled substance records must be maintained for a minimum of how many years under federal DEA regulations?"; options = ["1 year", "2 years", "5 years", "7 years"]; correctOptionIndex = 1; explanation = "DEA federal regulations require all controlled substance records (Schedules I-V) to be maintained for a minimum of 2 years and be readily available for DEA inspection. Many states require longer retention periods (3-7 years). Pharmacies must follow whichever period is more stringent — state or federal."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v7-q88"; versionId = "ptcb-v7"; text = "The REMS (Risk Evaluation and Mitigation Strategy) program for thalidomide (Thalomid) and lenalidomide (Revlimid) is called:"; options = ["iPLEDGE", "TIRF REMS Access program", "STEPS (System for Thalidomide Education and Prescribing Safety) or Revlimid REMS", "Clozapine REMS"]; correctOptionIndex = 2; explanation = "Thalidomide (Thalomid) uses the STEPS program (System for Thalidomide Education and Prescribing Safety). Lenalidomide (Revlimid) has its own Revlimid REMS. Both are required due to severe teratogenicity. All prescribers, pharmacies, and patients must be enrolled. iPLEDGE is for isotretinoin; Clozapine REMS is for agranulocytosis monitoring."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v7-q89"; versionId = "ptcb-v7"; text = "DEA Form 41 is used for:"; options = ["Ordering Schedule I and II controlled substances from suppliers", "Recording the destruction of controlled substances that cannot be returned to a reverse distributor", "Reporting theft or significant loss of controlled substances", "Registering a new pharmacy location with the DEA"]; correctOptionIndex = 1; explanation = "DEA Form 41 (Registrant Record of Controlled Substances Destroyed) is used to document the on-site destruction of controlled substances that are damaged, expired, or otherwise unusable and cannot be returned to a reverse distributor. Two witnesses must be present and sign the form. DEA Form 106 is for reporting theft/significant loss."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v7-q90"; versionId = "ptcb-v7"; text = "A DEA biennial inventory is required by law to be conducted at least every:"; options = ["1 year", "2 years", "3 years", "5 years"]; correctOptionIndex = 1; explanation = "DEA regulations (21 CFR 1304.11) require every DEA-registered pharmacy to take a complete physical inventory of all controlled substances every 2 years (biennial). The date chosen for the initial inventory becomes the basis for the 2-year cycle. Records must be kept for at least 2 years."; knowledgeDomain = #FederalRequirements; isScored = true });
  };
};
