import Types "../types/exams";
import List "mo:core/List";

module {
  public func seedV9(
    versions : List.List<Types.ExamVersion>,
    questions : List.List<Types.Question>
  ) : () {

    versions.add({ id = "ptcb-v9"; examId = "ptcb"; versionName = "Practice Test 9"; totalQuestions = 90; scoredQuestions = 80; timeLimitMinutes = 110 });

    // ── Medications (36) ──────────────────────────────────────────────────────

    questions.add({ id = "ptcb-v9-q1"; versionId = "ptcb-v9"; text = "Cefdinir (Omnicef) oral suspension interacts with iron supplements. When a patient on oral iron asks about timing, the correct counseling is:"; options = ["Iron supplements enhance cefdinir absorption and should be taken together", "Iron chelates cefdinir, reducing bioavailability by up to 80%; separate cefdinir and iron supplements by at least 2 hours", "Iron has no interaction with oral cephalosporins", "Cefdinir should be taken with iron to reduce GI side effects"]; correctOptionIndex = 1; explanation = "Like fluoroquinolones and tetracyclines, cefdinir forms chelation complexes with iron (Fe2+ and Fe3+), dramatically reducing its oral absorption. Cefdinir should be administered at least 2 hours before or 2 hours after iron-containing products. The stool may turn red-black (harmless iron-cefdinir complex in feces)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q2"; versionId = "ptcb-v9"; text = "Which of the following correctly describes the Narrow Therapeutic Index (NTI) designation for drugs like levothyroxine, warfarin, and digoxin?"; options = ["NTI drugs have a large margin between therapeutic and toxic doses", "NTI drugs have a small margin between therapeutic and subtherapeutic/toxic doses; small changes in dose or bioavailability cause clinically significant fluctuations in efficacy or safety", "NTI drugs require IV administration only", "NTI designation allows only brand-name drugs to be dispensed"]; correctOptionIndex = 1; explanation = "NTI (Narrow Therapeutic Index) drugs require careful monitoring because the therapeutic range is narrow — small dose changes or bioavailability differences between formulations can cause toxicity or treatment failure. For levothyroxine and warfarin, some states require prescriber notification before generic substitution. For digoxin, cyclosporine, lithium, and phenytoin, serum level monitoring is essential."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q3"; versionId = "ptcb-v9"; text = "Clotrimazole troches (lozenges) are used for oropharyngeal candidiasis (oral thrush). The most important counseling point is:"; options = ["Swallow the troche whole for best systemic absorption", "Dissolve slowly in the mouth (5 times daily for 14 days); avoid eating or drinking for 30 minutes after; rinse mouth after use if also on inhaled corticosteroids", "Chew and swallow for maximum contact with mucosa", "Take with food and milk to prevent nausea"]; correctOptionIndex = 1; explanation = "Clotrimazole troches must be dissolved slowly in the mouth (not chewed or swallowed) to maintain prolonged contact with oral mucosa. Patients on inhaled corticosteroids (which can cause thrush as a side effect) should always rinse mouth after ICS use to prevent oral candidiasis. Troche dosing: 1 troche 5 times daily x 14 days."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q4"; versionId = "ptcb-v9"; text = "Miconazole (Monistat) is available OTC as a topical antifungal. It is most commonly used for:"; options = ["Onychomycosis (nail fungus)", "Vaginal candidiasis and tinea infections (ringworm, athlete's foot, jock itch)", "Systemic fungal infections requiring hospitalization", "Bacterial vaginosis"]; correctOptionIndex = 1; explanation = "Topical miconazole (an azole antifungal) is widely used OTC for vaginal yeast infections (Monistat 1-day, 3-day, 7-day) and superficial dermatophyte/candida skin infections (tinea pedis, tinea corporis, tinea cruris). It inhibits ergosterol synthesis in the fungal cell membrane. It is not effective for systemic fungal infections or nail fungus (which requires oral terbinafine)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q5"; versionId = "ptcb-v9"; text = "Ganciclovir is an antiviral used specifically for:"; options = ["Herpes simplex virus (HSV) oral and genital herpes", "Cytomegalovirus (CMV) retinitis and disease in immunocompromised patients (HIV/AIDS, transplant)", "Influenza A and B (as an alternative to oseltamivir)", "Hepatitis B virus treatment"]; correctOptionIndex = 1; explanation = "Ganciclovir (and its oral prodrug valganciclovir/Valcyte) is the primary treatment for CMV infections, particularly CMV retinitis in AIDS patients and CMV prophylaxis/treatment in organ transplant recipients. It inhibits CMV DNA polymerase. Major toxicities: myelosuppression (neutropenia, thrombocytopenia), nephrotoxicity. Acyclovir is used for HSV/VZV."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q6"; versionId = "ptcb-v9"; text = "Nystatin oral suspension is used for oral candidiasis. The correct administration technique is:"; options = ["Swallow immediately for best systemic absorption", "Swish vigorously in the mouth for several minutes, then swallow (swish-and-swallow); take after meals", "Apply with a cotton swab to lesions only", "Dilute with water before use"]; correctOptionIndex = 1; explanation = "Nystatin oral suspension for thrush is administered as 'swish and swallow' (or swish and spit in some protocols). Swishing for 1-2 minutes maximizes contact with oral mucosa; swallowing treats esophageal involvement. Take AFTER meals to prevent food from washing drug away. Not absorbed systemically, so safe for infants."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q7"; versionId = "ptcb-v9"; text = "Which of the following is a correct statement about ibuprofen's mechanism of action?"; options = ["Ibuprofen is a selective COX-2 inhibitor that spares gastric prostaglandins", "Ibuprofen is a non-selective COX-1 and COX-2 inhibitor; COX-1 inhibition reduces platelet thromboxane A2 and gastric mucus, increasing GI risk", "Ibuprofen inhibits leukotriene synthesis exclusively", "Ibuprofen activates prostaglandin receptors to reduce pain signaling"]; correctOptionIndex = 1; explanation = "NSAIDs like ibuprofen and naproxen non-selectively inhibit both COX-1 and COX-2. COX-1 inhibition reduces thromboxane A2 (impairing platelet aggregation — antiplatelet effect) and gastric prostaglandins (reducing mucus and bicarbonate secretion, increasing GI ulcer risk). COX-2 inhibition provides analgesia, antipyresis, and anti-inflammation. Selective COX-2 inhibitors (celecoxib) spare COX-1."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q8"; versionId = "ptcb-v9"; text = "Celecoxib (Celebrex) is a selective COX-2 inhibitor. Which of the following is its key advantage and risk compared to non-selective NSAIDs?"; options = ["Lower cardiovascular risk and higher GI risk", "Lower GI risk (no COX-1 inhibition of gastric mucus) but potentially higher cardiovascular risk (no antiplatelet effect, may increase thromboembolic events)", "Safer in renal impairment and without cardiovascular concerns", "Lower cost with equivalent analgesic efficacy to opioids"]; correctOptionIndex = 1; explanation = "Celecoxib selectively inhibits COX-2, sparing COX-1 (preserving gastric protection), resulting in lower GI ulcer risk than non-selective NSAIDs. However, without COX-1 inhibition, thromboxane A2 synthesis is preserved while prostacyclin (PGI2) production falls, potentially tipping the balance toward thrombosis. Celecoxib carries a cardiovascular risk black box warning similar to other NSAIDs."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q9"; versionId = "ptcb-v9"; text = "Naloxone (Narcan) is the antidote for opioid overdose. It works by:"; options = ["Stimulating opioid receptors to reverse sedation", "Competitive antagonism at mu, delta, and kappa opioid receptors, displacing opioids and reversing respiratory depression, sedation, and miosis", "Hepatically metabolizing opioids to inactive compounds", "Increasing respiratory drive through central norepinephrine release"]; correctOptionIndex = 1; explanation = "Naloxone is a pure opioid antagonist with higher receptor affinity than most opioids. It competitively displaces opioid agonists from mu receptors (primary mediator of respiratory depression), rapidly reversing overdose. Onset: IV <2 min, IM/intranasal 2-5 min. Half-life: 30-90 min (shorter than most opioids) — may require repeated doses or infusion for long-acting opioids."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q10"; versionId = "ptcb-v9"; text = "Naltrexone (Vivitrol) is used for alcohol use disorder and opioid use disorder. How does it differ from naloxone?"; options = ["Naltrexone is shorter-acting and only available IV", "Naltrexone is an oral/IM extended-release opioid antagonist; unlike naloxone, it is used for PREVENTION of relapse, not emergency reversal; patients must be opioid-free for 7-10 days before starting", "Naltrexone is a partial opioid agonist like buprenorphine", "Naltrexone has no role in alcohol use disorder"]; correctOptionIndex = 1; explanation = "Naltrexone (oral ReVia, monthly IM Vivitrol) is an opioid antagonist for relapse prevention. For AUD, it blocks the reinforcing effects of alcohol via endogenous opioid pathways. For OUD, it prevents euphoria from opioids. Patients must be opioid-free for 7-10 days to avoid precipitated withdrawal. No abuse potential. Hepatotoxicity risk at high doses."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q11"; versionId = "ptcb-v9"; text = "Buprenorphine/naloxone (Suboxone) is used for opioid use disorder. The naloxone component is included to:"; options = ["Enhance the analgesic effect of buprenorphine", "Deter IV abuse: naloxone is poorly absorbed sublingually but reverses effects if injected, precipitating withdrawal in opioid-dependent users", "Reduce the euphoria of buprenorphine at therapeutic doses", "Provide additional antidepressant effects"]; correctOptionIndex = 1; explanation = "Suboxone contains buprenorphine (partial mu-opioid agonist for OUD treatment) and naloxone (opioid antagonist as abuse deterrent). When taken sublingually as intended, naloxone has minimal absorption. If crushed and injected, naloxone is fully bioavailable, precipitating immediate opioid withdrawal in opioid-dependent patients. This discourages diversion and injection misuse."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q12"; versionId = "ptcb-v9"; text = "Which of the following drugs used for type 2 diabetes has the primary mechanism of slowing gastric emptying and reducing appetite via GLP-1 receptor activation?"; options = ["Glipizide", "Semaglutide (Ozempic)", "Pioglitazone", "Sitagliptin"]; correctOptionIndex = 1; explanation = "GLP-1 receptor agonists (semaglutide, liraglutide, dulaglutide, exenatide) activate GLP-1 receptors, causing: glucose-dependent insulin secretion, glucagon suppression, gastric emptying slowing (reducing postprandial glucose spikes), and hypothalamic appetite suppression (leading to weight loss). Semaglutide (Ozempic/Wegovy) also has FDA approval for chronic weight management at higher doses."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q13"; versionId = "ptcb-v9"; text = "SGLT-2 inhibitors (canagliflozin, dapagliflozin, empagliflozin) are associated with which unique side effect due to their mechanism?"; options = ["Hypoglycemia as a primary risk", "Genital mycotic infections (yeast infections) due to glucosuria creating a favorable environment for fungal growth", "Hypothyroidism from iodine depletion", "Agranulocytosis requiring weekly CBC monitoring"]; correctOptionIndex = 1; explanation = "SGLT-2 inhibitors cause glucosuria (glucose in urine). The high glucose environment in genital tissues promotes Candida growth, causing vulvovaginal candidiasis in women and balanitis in men. Patients should be counseled on genital hygiene. SGLT-2 inhibitors also increase risk of UTIs, euglycemic DKA (rare), Fournier's gangrene (rare but serious), and lower limb amputations (canagliflozin-specific risk)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q14"; versionId = "ptcb-v9"; text = "Insulin lispro (Humalog) is a rapid-acting insulin analog. How does its onset of action compare to regular human insulin?"; options = ["Insulin lispro has a slower onset (60-90 min) vs. regular insulin (15 min)", "Insulin lispro onset is 15 min (given right before meals) vs. regular insulin 30-60 min (given 30 min before meals)", "They have identical onset; lispro only differs in duration", "Insulin lispro requires IV administration only for rapid onset"]; correctOptionIndex = 1; explanation = "Rapid-acting insulin analogs (lispro/Humalog, aspart/NovoLog, glulisine/Apidra) have onset 15 min, peak 1-2 hrs, duration 3-4 hrs. They are given immediately before meals. Regular insulin has onset 30-60 min, peak 2-4 hrs, duration 5-8 hrs, requiring 30 min pre-meal timing. The faster profile of analogs better matches postprandial glucose excursions."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q15"; versionId = "ptcb-v9"; text = "Insulin glargine (Lantus) is a long-acting basal insulin. Which of the following is a critical counseling point about its use?"; options = ["It may be mixed in the same syringe with rapid-acting insulin for convenience", "It should NOT be mixed with other insulins (altered pH changes pharmacokinetics); inject once daily at the same time each day; does not have a pronounced peak", "It must be refrigerated at all times, even after opening", "It can be given IV in hyperglycemic emergencies"]; correctOptionIndex = 1; explanation = "Insulin glargine is formulated at pH 4 (acidic). Mixing with other insulins (which are pH 7) changes the pH profile, disrupting its prolonged absorption mechanism and unpredictably altering PK. It is 'peakless' (flat profile) providing stable 24-hour basal coverage. After first use, vials/pens can be stored at room temperature for 28 days."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q16"; versionId = "ptcb-v9"; text = "Prednisone is a glucocorticoid prodrug. Which statement about long-term corticosteroid use is most important for patient counseling?"; options = ["Long-term corticosteroids do not affect electrolytes or blood sugar", "Long-term corticosteroids cause adrenal suppression (HPA axis suppression), hyperglycemia, osteoporosis, weight gain, immunosuppression, and should never be abruptly stopped — taper required", "Long-term use causes dose-dependent agranulocytosis", "Corticosteroids are safe for extended use if doses are kept below 40 mg/day"]; correctOptionIndex = 1; explanation = "Prolonged corticosteroid use causes multiple adverse effects: adrenal suppression (HPA axis), hyperglycemia, osteoporosis (prevent with calcium/vitamin D/bisphosphonate), weight gain, Cushing's syndrome, cataracts, and immunosuppression. Abrupt discontinuation after long-term use can cause adrenal crisis. Tapering allows adrenal recovery. Short courses (5-7 days) generally don't require tapering."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q17"; versionId = "ptcb-v9"; text = "Which of the following correctly describes budesonide (Pulmicort) compared to an oral corticosteroid?"; options = ["Budesonide is more potent systemically and causes more HPA suppression", "Inhaled budesonide delivers drug directly to airway mucosa with minimal systemic absorption, reducing systemic side effects; mouth rinsing after use prevents oral candidiasis", "Inhaled budesonide is equally as effective as oral prednisone for acute asthma exacerbations", "Budesonide must be taken with oral steroids for adequate asthma control"]; correctOptionIndex = 1; explanation = "Inhaled corticosteroids (ICS) like budesonide, fluticasone, and beclomethasone provide targeted airway anti-inflammatory effects with minimal systemic absorption (high first-pass hepatic metabolism). This dramatically reduces systemic steroid side effects. Key side effects: local oral candidiasis and dysphonia (prevented by rinsing mouth with water after each use)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q18"; versionId = "ptcb-v9"; text = "Tiotropium (Spiriva) is a long-acting muscarinic antagonist (LAMA) used in COPD. Its mechanism differs from SABA (albuterol) in that tiotropium:"; options = ["Acts faster than albuterol with a 5-minute onset", "Blocks M3 muscarinic receptors to reduce bronchospasm and secretions with 24-hour duration; it is a maintenance agent, NOT rescue medication", "Stimulates beta-2 receptors to cause bronchodilation", "Suppresses inflammatory cytokines in airway tissue"]; correctOptionIndex = 1; explanation = "Tiotropium (Spiriva HandiHaler/Respimat) is a LAMA (long-acting muscarinic antagonist) blocking M3 receptors in bronchial smooth muscle and submucosal glands. This reduces bronchoconstriction and mucus secretion. Its 24-hour duration makes it a once-daily maintenance bronchodilator. It is NOT a rescue drug. SABAs (albuterol, levalbuterol) are for acute bronchospasm."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q19"; versionId = "ptcb-v9"; text = "Fluticasone/salmeterol (Advair) is an ICS/LABA combination. The black box warning for LABAs (salmeterol, formoterol) states:"; options = ["LABAs cause fatal cardiac arrhythmias in elderly patients", "LABAs increase risk of asthma-related death when used WITHOUT an ICS; they should never be used as monotherapy in asthma", "LABAs cause severe QT prolongation requiring ECG monitoring", "LABAs are contraindicated in all COPD patients over age 65"]; correctOptionIndex = 1; explanation = "The SABA Safety Clinical Trial demonstrated increased asthma deaths with salmeterol monotherapy. FDA's black box warning: LABAs must only be used in patients whose asthma is not adequately controlled on other medications (like ICS), and should be prescribed in combination with an ICS. They should never be the sole asthma controller. In COPD, LABA monotherapy is acceptable."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q20"; versionId = "ptcb-v9"; text = "Montelukast (Singulair) is a leukotriene receptor antagonist used for asthma and allergic rhinitis. Which of the following is a known risk requiring an FDA black box warning?"; options = ["Hepatotoxicity requiring monthly LFT monitoring", "Serious neuropsychiatric events (depression, suicidal ideation, aggressive behavior); prescribers should consider risk vs. benefit before prescribing", "Agranulocytosis requiring weekly CBC", "Severe bronchospasm paradox with first dose"]; correctOptionIndex = 1; explanation = "In 2020, FDA added a black box warning to montelukast for serious neuropsychiatric events including suicidal ideation, behavior changes, aggression, and depression. Due to this risk, FDA restricted use: for allergic rhinitis, avoid in patients who have less severe disease; asthma use should weigh benefits vs. neuropsychiatric risks especially in children and adolescents."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q21"; versionId = "ptcb-v9"; text = "Omeprazole (Prilosec) is a PPI. After oral administration, omeprazole is absorbed in the:"; options = ["Stomach, where the acid environment activates it immediately", "Small intestine (as delayed-release formulation to prevent acid degradation in the stomach), then delivered via blood to parietal cells where it is acid-activated", "Colon via controlled-release mechanism", "Buccal mucosa, bypassing first-pass metabolism"]; correctOptionIndex = 1; explanation = "PPIs are acid-labile and given as enteric-coated (delayed-release) formulations to prevent degradation in the stomach. They are absorbed from the small intestine, enter the circulation, and concentrate in the acidic secretory canaliculi of parietal cells where they are activated by acid and irreversibly bind the H+/K+-ATPase. Best taken 30-60 min before the first meal for optimal efficacy."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q22"; versionId = "ptcb-v9"; text = "H2 receptor antagonists (ranitidine/famotidine) differ from proton pump inhibitors primarily in that they:"; options = ["Are more potent than PPIs at equivalent doses", "Block histamine H2 receptors on parietal cells, reducing acid output; less potent than PPIs and subject to tolerance with continuous use (tachyphylaxis)", "Irreversibly inhibit the proton pump", "Have no drug interactions"]; correctOptionIndex = 1; explanation = "H2RAs (famotidine/Pepcid, cimetidine) block histamine-stimulated acid secretion at H2 receptors. They are less effective than PPIs because they only block one of three pathways (histamine, ACh, gastrin) and develop tachyphylaxis (loss of efficacy within 2 weeks of continuous use). PPIs block the final common pathway (proton pump), making them more potent and complete acid suppressors."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q23"; versionId = "ptcb-v9"; text = "Sertraline (Zoloft) is an SSRI antidepressant. When starting an SSRI, patients should be counseled that:"; options = ["Mood improvement occurs within 24-48 hours of the first dose", "Antidepressant effects take 2-4 weeks (sometimes 6-8 weeks) to fully develop; anxiety may initially worsen; do not stop abruptly (discontinuation syndrome)", "SSRIs have no discontinuation symptoms", "SSRIs are safe to take with MAOIs without a washout period"]; correctOptionIndex = 1; explanation = "SSRIs require 2-4 weeks for antidepressant effects due to neuroadaptive changes. Patients must be counseled not to discontinue early if they don't feel better immediately. Abrupt discontinuation causes SSRI discontinuation syndrome (dizziness, nausea, 'brain zaps', flu-like symptoms). A 14-day washout after stopping an MAOI is required before starting an SSRI (5 weeks after fluoxetine due to long half-life)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q24"; versionId = "ptcb-v9"; text = "Which antidepressant class carries a black box warning for suicidal ideation in children, adolescents, and young adults?"; options = ["All antidepressants carry this black box warning", "TCAs (tricyclic antidepressants) only", "All antidepressants (SSRIs, SNRIs, TCAs, MAOIs) through a class-wide FDA black box warning", "MAOIs only"]; correctOptionIndex = 2; explanation = "FDA issued a class-wide black box warning for ALL antidepressants regarding increased risk of suicidal thinking and behavior in patients under 25. The warning applies to SSRIs, SNRIs, TCAs, MAOIs, and other antidepressants. This risk must be balanced against the risks of untreated depression. Patients must be monitored closely during initial treatment and dose changes."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q25"; versionId = "ptcb-v9"; text = "Serotonin syndrome caused by combining an SSRI with tramadol is characterized by:"; options = ["Slow heart rate and hypothermia (opioid-like toxidrome)", "Hyperthermia, agitation, muscle rigidity/clonus, diaphoresis, autonomic instability — requiring immediate drug discontinuation", "Mild drowsiness that resolves within 24 hours", "A gradual onset over weeks of mild mood changes"]; correctOptionIndex = 1; explanation = "Serotonin syndrome is a potentially life-threatening condition caused by excess serotonergic activity (SSRI + tramadol, MAOIs + SSRIs, linezolid + SSRIs). The classic triad: neuromuscular abnormalities (clonus, hyperreflexia, tremor), autonomic instability (hyperthermia, tachycardia, diaphoresis), and altered mental status (agitation, confusion). Severe cases require cyproheptadine (5-HT antagonist) and supportive care."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q26"; versionId = "ptcb-v9"; text = "Duloxetine (Cymbalta) is an SNRI with FDA-approved indications that extend beyond depression. Which of the following is a unique approved indication?"; options = ["Bipolar mania", "Diabetic peripheral neuropathic pain, fibromyalgia, chronic musculoskeletal pain, and generalized anxiety disorder", "Seizure prophylaxis", "ADHD in adults"]; correctOptionIndex = 1; explanation = "Duloxetine is an SNRI with the broadest range of approved indications: MDD, GAD, diabetic peripheral neuropathic pain, fibromyalgia, chronic musculoskeletal pain, and stress urinary incontinence (in some countries). Its norepinephrine reuptake inhibition contributes to pain modulation in descending pain pathways. Dose: 60-120 mg/day for pain indications."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q27"; versionId = "ptcb-v9"; text = "Gabapentin (Neurontin) and pregabalin (Lyrica) are used for neuropathic pain and partial seizures. Their mechanism of action is:"; options = ["Blocking voltage-gated sodium channels like phenytoin", "Binding the alpha-2-delta subunit of voltage-gated calcium channels, reducing excitatory neurotransmitter release", "Enhancing GABA-A receptor function like benzodiazepines", "Blocking NMDA glutamate receptors"]; correctOptionIndex = 1; explanation = "Gabapentin and pregabalin bind the alpha-2-delta (alpha2delta) auxiliary subunit of voltage-gated calcium channels in the dorsal horn and brain, reducing calcium influx and thereby reducing release of excitatory neurotransmitters (glutamate, norepinephrine, substance P). Despite the name, they do NOT bind GABA receptors or have GABAergic activity."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q28"; versionId = "ptcb-v9"; text = "A patient taking amiodarone and warfarin has their INR rise significantly. The pharmacist knows this is due to:"; options = ["Amiodarone directly competing with vitamin K clotting factors", "Amiodarone inhibiting CYP2C9 and CYP3A4, reducing warfarin metabolism and causing its accumulation", "Amiodarone reducing vitamin K absorption from the gut", "Amiodarone displacing warfarin from albumin binding sites"]; correctOptionIndex = 1; explanation = "Amiodarone is a potent inhibitor of CYP2C9 (metabolizes warfarin S-enantiomer) and CYP3A4 (metabolizes warfarin R-enantiomer). This combination causes dramatic warfarin accumulation and INR elevation. Typically the warfarin dose must be reduced by 30-50% when amiodarone is started. The interaction persists long-term and even after amiodarone discontinuation due to its very long half-life (40-55 days)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q29"; versionId = "ptcb-v9"; text = "Rosuvastatin (Crestor) has less drug interaction potential than simvastatin or lovastatin because:"; options = ["Rosuvastatin is more potent and therefore needs lower doses that cause fewer interactions", "Rosuvastatin is minimally metabolized by CYP3A4 (primarily CYP2C9 with minor hepatic metabolism), making it less susceptible to CYP3A4 inhibitor interactions (azoles, HIV PIs, macrolides)", "Rosuvastatin does not inhibit HMG-CoA reductase", "Rosuvastatin is excreted exclusively renally with no hepatic metabolism"]; correctOptionIndex = 1; explanation = "Simvastatin and lovastatin are extensively metabolized by CYP3A4, making them vulnerable to numerous interactions (azoles, HIV PIs, macrolides, diltiazem, verapamil). Rosuvastatin is primarily a CYP2C9 substrate with minimal CYP3A4 involvement, avoiding most of these interactions. Pravastatin is not significantly CYP-metabolized at all. Fluvastatin is a CYP2C9 substrate."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q30"; versionId = "ptcb-v9"; text = "Which of the following correctly describes the mechanism of action of erythropoietin-stimulating agents (ESAs) such as epoetin alfa (Epogen/Procrit) and darbepoetin alfa (Aranesp)?"; options = ["Stimulate the immune system to produce white blood cells for anemia treatment", "Bind erythropoietin receptors in bone marrow, stimulating red blood cell precursor proliferation and maturation", "Directly increase iron absorption from the GI tract", "Stimulate the spleen to release stored erythrocytes"]; correctOptionIndex = 1; explanation = "ESAs (epoetin alfa, darbepoetin alfa) are recombinant erythropoietin analogs that stimulate EPO receptors on erythroid progenitor cells in bone marrow, promoting differentiation and proliferation of red blood cells. Used for anemia of CKD and chemotherapy-induced anemia. Adequate iron stores are required for response. Black box warning: increased cardiovascular events and mortality when used to target Hgb >11-12 g/dL."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q31"; versionId = "ptcb-v9"; text = "Filgrastim (Neupogen) and pegfilgrastim (Neulasta) are granulocyte colony-stimulating factors (G-CSFs). They are used to:"; options = ["Stimulate red blood cell production in chemotherapy-induced anemia", "Stimulate bone marrow production and mobilization of neutrophils to reduce risk of febrile neutropenia after myelosuppressive chemotherapy", "Prevent platelet loss during chemotherapy", "Treat thrombocytopenia by stimulating megakaryocyte production"]; correctOptionIndex = 1; explanation = "G-CSFs (filgrastim, pegfilgrastim) stimulate granulocyte (neutrophil) precursor proliferation, differentiation, and mobilization from bone marrow. Used for: primary/secondary febrile neutropenia prophylaxis after chemotherapy, stem cell mobilization, severe chronic neutropenia. Pegfilgrastim is a long-acting PEGylated form requiring only one dose per chemotherapy cycle."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q32"; versionId = "ptcb-v9"; text = "Which of the following medications requires periodic monitoring of serum creatinine and potassium due to renal effects?"; options = ["Omeprazole and statins", "ACE inhibitors and ARBs (lisinopril, losartan) require monitoring of SCr and K+ due to reduced GFR and decreased aldosterone-mediated potassium excretion", "SSRIs and benzodiazepines", "Antihistamines and decongestants"]; correctOptionIndex = 1; explanation = "ACE inhibitors and ARBs reduce angiotensin II, causing efferent arteriolar dilation and reduced GFR (monitored via SCr). They also decrease aldosterone, reducing K+ excretion (hyperkalemia risk). Baseline labs (SCr, K+) before starting and 1-2 weeks after initiation or dose changes are recommended. Hold if K+ >5.5 mEq/L or if SCr rises >30% above baseline."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q33"; versionId = "ptcb-v9"; text = "Tacrine was the first acetylcholinesterase inhibitor for Alzheimer's disease but is no longer used. It was withdrawn because of:"; options = ["Insufficient efficacy compared to placebo", "Severe hepatotoxicity with elevated transaminases in many patients", "Unacceptable cardiovascular side effects", "Development of resistance after long-term use"]; correctOptionIndex = 1; explanation = "Tacrine (Cognex) was the first FDA-approved AChEI for Alzheimer's (1993). It was abandoned due to a high rate of hepatotoxicity (elevated ALT in up to 50% of patients). It was replaced by donepezil, rivastigmine, and galantamine, which have better safety profiles. All AChEIs can cause cholinergic side effects (nausea, vomiting, bradycardia)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q34"; versionId = "ptcb-v9"; text = "Memantine (Namenda) is approved for moderate-to-severe Alzheimer's disease. Its mechanism differs from AChEIs because it:"; options = ["Inhibits acetylcholinesterase with higher selectivity for the CNS", "Blocks NMDA glutamate receptors, reducing excitotoxicity from excessive glutamate activity believed to contribute to Alzheimer's neurodegeneration", "Increases serotonin levels in the hippocampus to improve memory", "Stimulates nerve growth factor receptors to promote neuronal survival"]; correctOptionIndex = 1; explanation = "Memantine (Namenda) is a low-to-moderate affinity, uncompetitive NMDA receptor antagonist. It blocks excessive glutamate-mediated excitotoxic activity while allowing normal synaptic transmission. Used for moderate-to-severe Alzheimer's, often combined with donepezil (Namzaric). Side effects: dizziness, confusion, headache (generally well-tolerated)."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q35"; versionId = "ptcb-v9"; text = "Which of the following PCSK9 inhibitors (evolocumab/Repatha, alirocumab/Praluent) correctly describes their mechanism and clinical role?"; options = ["Oral agents taken daily that block HMG-CoA reductase", "Monoclonal antibodies injected every 2-4 weeks that inhibit PCSK9 protein, preventing LDL receptor degradation and dramatically reducing LDL-C (50-60%) beyond statin therapy", "Drugs that block bile acid reabsorption in the terminal ileum", "Drugs that require weekly liver function tests due to hepatotoxicity"]; correctOptionIndex = 1; explanation = "PCSK9 inhibitors are monoclonal antibodies that bind PCSK9 protein, which normally marks LDL receptors for lysosomal degradation. By inhibiting PCSK9, more LDL receptors are available on hepatocytes, increasing LDL clearance from plasma. They reduce LDL by 50-60% on top of statin therapy. Used for familial hypercholesterolemia and statin-intolerant patients at high cardiovascular risk."; knowledgeDomain = #Medications; isScored = true });

    questions.add({ id = "ptcb-v9-q36"; versionId = "ptcb-v9"; text = "Fenofibrate (Tricor) is a fibrate used for hypertriglyceridemia. Its mechanism of action is:"; options = ["Inhibiting HMG-CoA reductase to reduce triglyceride synthesis", "Activating PPAR-alpha receptors in the liver, increasing lipoprotein lipase activity and reducing VLDL triglyceride production", "Binding bile acids in the gut to reduce cholesterol reabsorption", "Blocking intestinal cholesterol absorption via NPC1L1"]; correctOptionIndex = 1; explanation = "Fibrates (fenofibrate, gemfibrozil) activate PPAR-alpha nuclear receptors, increasing lipoprotein lipase expression (which hydrolyzes triglycerides from VLDL and chylomicrons) and reducing hepatic VLDL production. They are most effective for hypertriglyceridemia and also raise HDL. Note: gemfibrozil increases myopathy risk when combined with statins (inhibits CYP2C8 and UGT1A3); fenofibrate is safer with statins."; knowledgeDomain = #Medications; isScored = true });

    // ── Patient Safety (24) ───────────────────────────────────────────────────

    questions.add({ id = "ptcb-v9-q37"; versionId = "ptcb-v9"; text = "Which of the following safety measures is specifically recommended by ISMP to prevent look-alike/sound-alike errors with insulin?"; options = ["Store all insulin types in the same refrigerator shelf for easy access", "Use Tall Man Lettering (HumuLIN vs. HumaLOG), separate storage, color-coded labels, and alert nurses that insulin is a high-alert medication", "Only use brand names on all insulin labels to prevent generic confusion", "Replace all insulin orders with weight-based protocols"]; correctOptionIndex = 1; explanation = "ISMP recommends multiple layers for insulin safety: Tall Man Lettering (HumuLIN/HumaLOG, NovoLIN/NovoLOG), color-coding by type, physical separation in the ADC, alert labels, and independent double-checks for high-alert insulin administration. These system-design changes prevent errors more reliably than reliance on individual vigilance alone."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q38"; versionId = "ptcb-v9"; text = "A hospitalized patient's medication reconciliation on admission reveals they take ibuprofen 400 mg TID at home for knee pain but this was not included in admission orders. The clinical pharmacist should:"; options = ["Assume the prescriber intentionally omitted it", "Review whether ibuprofen is appropriate (renal function, GI risk, drug interactions) and communicate the omission to the prescriber for a decision on whether to continue, substitute, or hold", "Add ibuprofen to the orders independently without prescriber notification", "Withhold all OTC medications until discharge"]; correctOptionIndex = 1; explanation = "Medication reconciliation identifies discrepancies between home medications and hospital orders. OTC NSAID omission may be intentional (e.g., patient has AKI, is on anticoagulation) or inadvertent. The clinical pharmacist's role is to identify the discrepancy, assess clinical implications, and communicate recommendations to the prescribing team — not to unilaterally add orders."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q39"; versionId = "ptcb-v9"; text = "Which of the following correctly describes the function of the USP <800> chapter for hazardous drug handling?"; options = ["Establishes packaging requirements for Schedule II controlled substances", "Sets standards for safe handling of hazardous drugs to minimize occupational exposure through engineering controls, personal protective equipment, and work practice controls", "Defines sterility testing requirements for USP compounded preparations", "Regulates the pharmacist-to-technician ratio in hospital settings"]; correctOptionIndex = 1; explanation = "USP <800> (Hazardous Drugs — Handling in Healthcare Settings) addresses occupational safety for healthcare workers handling hazardous drugs. It requires: NIOSH list review, engineering controls (C-PEC for compounding, ventilated cabinets), appropriate PPE (chemotherapy gloves, gowns), training, spill kits, and segregated storage of HDs. Applies to all settings that receive, store, prepare, or administer HDs."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q40"; versionId = "ptcb-v9"; text = "A pharmacy receives a drug recall notice for a specific lot of amoxicillin 500 mg capsules (Lot XY1234). The correct immediate action is:"; options = ["Check the lot number against current inventory; if lot XY1234 is on the shelf, continue dispensing until current supplies are exhausted to avoid waste", "Immediately quarantine and remove all Lot XY1234 from dispensing stock, place in a labeled 'RECALLED — DO NOT DISPENSE' area, notify the pharmacist-in-charge, and follow recall return/destruction procedures", "Wait for official written DEA confirmation before removing from inventory", "Only notify patients who have already received the recalled lot"]; correctOptionIndex = 1; explanation = "Drug recall procedures require immediate action: pull the recalled lot from all dispensing locations, segregate in a 'do not use' quarantine area, document all recalled stock, notify supervisors/pharmacist-in-charge, and follow manufacturer/FDA return or destruction instructions. Patients who received the recalled lot must also be identified and contacted per the recall class instructions."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q41"; versionId = "ptcb-v9"; text = "The 'five rights' of medication administration are a foundational safety checklist. However, research shows errors still occur even when all five rights are verbally confirmed. What additional strategy has demonstrated the greatest systematic error reduction?"; options = ["Requiring pharmacists to memorize all 5 rights before licensure", "Barcode Medication Administration (BCMA) scanning: electronically verifying patient ID, drug, dose, route, and time at point of care before administration", "Verbal confirmation alone between nurse and prescriber", "Double-checking all 5 rights on paper daily"]; correctOptionIndex = 1; explanation = "BCMA systems electronically verify the 5 rights at the bedside by scanning patient wristband (patient ID) and medication barcode (drug, dose, form, expiration). BCMA has been shown to reduce medication administration errors by 50-80% in hospital settings. It supplements but does not replace clinical nursing judgment. Alert fatigue from overriding alerts remains a concern."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q42"; versionId = "ptcb-v9"; text = "A nursing home patient's medication list contains zolpidem 10 mg at bedtime, promethazine PRN nausea, oxybutynin for OAB, and diphenhydramine PRN sleep. A pharmacist reviewing this list should flag:"; options = ["All of these are appropriate standard medications for elderly patients", "Multiple anticholinergic medications (promethazine, oxybutynin, diphenhydramine) plus a sedative-hypnotic (zolpidem) represent high-risk polypharmacy for the elderly per Beers Criteria", "Only the zolpidem requires monitoring", "None of these require intervention since all are prescribed by the physician"]; correctOptionIndex = 1; explanation = "The Beers Criteria identifies all of these as potentially inappropriate in elderly: anticholinergics (promethazine, oxybutynin, diphenhydramine) cause confusion, urinary retention, constipation, falls; zolpidem increases fall/fracture risk. Cumulative anticholinergic burden (Anticholinergic Burden Scale) in this patient is very high. Deprescribing conversation with prescriber and nursing home staff is warranted."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q43"; versionId = "ptcb-v9"; text = "Which of the following is the correct action when a pharmacist suspects a prescriber's DEA number on a controlled substance prescription is invalid?"; options = ["Fill the prescription and note the issue in the patient's record", "Withhold the prescription and contact the prescriber using a number independently obtained (not from the Rx) to verify DEA registration; check the DEA number using the check-digit formula", "Fill the prescription since the prescriber has a valid state license", "Call the patient to ask if the DEA number is correct"]; correctOptionIndex = 1; explanation = "Pharmacists are required to verify controlled substance prescriptions. If a DEA number appears invalid (check-digit formula fails), the pharmacist should: (1) NOT dispense, (2) contact the prescriber directly using an independently verified phone number, and (3) verify the DEA number via the DEA website or NABP resources. Accepting invalid DEA numbers constitutes a federal violation."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q44"; versionId = "ptcb-v9"; text = "A patient calls the pharmacy and says they have been taking their metoprolol succinate 50 mg tablet by cutting it in half to make it easier to swallow. Is this safe?"; options = ["Yes, all tablets may be safely split regardless of formulation", "Metoprolol succinate is an extended-release (XL) tablet; splitting destroys the controlled-release mechanism, potentially causing rapid drug release and adverse effects. A different dosage form or approach should be identified", "Splitting any tablet doubles its bioavailability", "Half a tablet will have zero efficacy since the coating is disrupted"]; correctOptionIndex = 1; explanation = "Extended-release (ER/XL/XR) tablets should NEVER be crushed, cut, or chewed unless specifically approved by the manufacturer. Doing so destroys the controlled-release matrix or coating, potentially releasing the entire dose at once (dose dumping), causing toxicity. Metoprolol succinate ER may also have a film coating. Metoprolol tartrate (immediate-release) can generally be safely split."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q45"; versionId = "ptcb-v9"; text = "Which of the following is the correct regulatory requirement for a pharmacy technician ratio in most US states?"; options = ["1 technician per pharmacist, regulated federally by DEA", "Technician-to-pharmacist ratios are regulated by individual STATE boards of pharmacy, not federally; ratios vary by state (commonly 1:1, 2:1, or up to 4:1 in some states)", "No ratio is required under federal law; states have no authority to regulate this", "Technicians must be licensed by the FDA before working in a pharmacy"]; correctOptionIndex = 1; explanation = "Pharmacy technician oversight ratios are set by STATE boards of pharmacy, not the DEA or FDA. Ratios vary widely: e.g., California allows up to 1:1 (tech:pharmacist), Arizona up to 4:1, Texas 4:1. National technician certification (PTCB's CPhT) is widely required by states but not mandated federally. Some states require registration, others require certification."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q46"; versionId = "ptcb-v9"; text = "Which of the following correctly describes the difference between a pharmacist's 'screening' role and a 'dispensing' role during prescription review?"; options = ["There is no meaningful difference; both roles involve only counting pills", "Screening: reviewing for clinical appropriateness (DUR, drug interactions, doses, allergies — pharmacist clinical judgment). Dispensing: verifying that the correct drug, strength, and quantity were prepared and labeled correctly", "Screening is done only for controlled substances; dispensing is for all drugs", "Screening is exclusively a technician function; dispensing is exclusively pharmacist"]; correctOptionIndex = 1; explanation = "Pharmacy practice involves two distinct reviews: (1) Clinical/DUR review (pharmacist — screening the prescription for appropriateness: correct dose, interactions, contraindications, allergy conflicts); and (2) Final verification (pharmacist — verifying the prepared product matches the prescription). Both functions belong to the pharmacist under standard of care, though technicians assist in preparation."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q47"; versionId = "ptcb-v9"; text = "A patient presents with a prescription for lisinopril 20 mg from 18 months ago with 3 refills remaining. Under federal and typical state guidelines, may the pharmacy fill this prescription?"; options = ["Yes, since refills remain on the prescription", "No — non-controlled prescription refills are typically valid for 1 year from the date of issue; this prescription is expired and a new prescription is needed", "Yes, there is no expiration on non-controlled drug prescriptions", "Only if the prescriber verbally authorizes the refill by phone"]; correctOptionIndex = 1; explanation = "Non-controlled substance prescriptions are typically valid for 1 year from the date issued (this standard is set by most state boards of pharmacy). After 1 year, remaining refills expire regardless of quantity remaining. A new prescription is required. The pharmacist should contact the prescriber for a new prescription or authorization."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q48"; versionId = "ptcb-v9"; text = "Which of the following is a correct principle for safe reconstitution of an oral antibiotic suspension (e.g., amoxicillin powder for suspension)?"; options = ["Add the entire volume of water at once and shake", "Add approximately half the total water, shake to dissolve the powder, then add remaining water to the final volume mark and shake again; check with the pharmacy bottle label for the specific volume", "Add water until the powder is fully visible above the water line", "Reconstitute using warm water to speed dissolution"]; correctOptionIndex = 1; explanation = "Two-step reconstitution of oral antibiotic suspensions ensures complete powder wetting and uniform mixing: add half the water → shake well → add remaining water to the bottle's calibration mark → shake again. Using the volume specified on the manufacturer's label is essential; adding too much or too little water changes drug concentration and dosing accuracy."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q49"; versionId = "ptcb-v9"; text = "The Medication Reconciliation Best Practice Advisory recommends reconciling a patient's complete medication list at which care transitions?"; options = ["Only at hospital admission", "Hospital admission, transfer between units, and discharge (the 'three moments of reconciliation'); also at outpatient care transitions such as post-discharge follow-up visits", "Only at discharge", "Only when medications are changed during hospitalization"]; correctOptionIndex = 1; explanation = "Medication reconciliation must occur at every care transition where orders are written or changed: (1) admission (compare home medications with admission orders), (2) internal transfers (ICU to step-down unit, unit to unit), and (3) discharge (create accurate medication list, counsel patient on changes). Post-discharge medication discrepancies are a major cause of readmissions."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q50"; versionId = "ptcb-v9"; text = "Which of the following is a correct statement about the proper handling of a chemotherapy spill in a non-cleanroom area?"; options = ["Wipe up the spill immediately with paper towels and discard in regular trash", "Use a dedicated chemo spill kit: wear PPE (double chemo gloves, gown, face shield, respirator), absorb liquid with chemo absorbent pads, place in labeled chemo waste bag, clean area with detergent and water, document the spill", "Cover the spill with a laboratory coat until it can be addressed by a cleaning crew", "Flush liquid spills with large amounts of water down a drain"]; correctOptionIndex = 1; explanation = "Hazardous drug (chemotherapy) spills require dedicated chemo spill kits and strict PPE. Procedure: don PPE → contain spill with chemo-rated absorbent → clean area with detergent/water → dispose in yellow chemo waste bag → remove PPE in correct sequence → wash hands → document spill with date, drug, quantity, circumstances, personnel involved. Regular trash disposal of cytotoxic waste is a federal violation."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q51"; versionId = "ptcb-v9"; text = "Which of the following is an appropriate use of a pharmacy's automated dispensing cabinet (ADC) profiling requirement?"; options = ["All medications should be accessible through ADC override without pharmacy review", "Most medications should only be accessible after pharmacist review and electronic profile approval (profile mode); overrides limited to true emergencies", "ADCs are only required in ICU settings", "Pharmacy profile review is optional for oral medications but required for IV medications"]; correctOptionIndex = 1; explanation = "ADC profiling: pharmacist electronically reviews and approves the patient's medication orders before nurses can retrieve medications from the cabinet (profile mode). This provides pharmacist oversight before administration. Profile mode for most medications ensures clinical screening (dose, interactions) occurs before drug reaches the patient. Override should be reserved for life-threatening emergencies."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q52"; versionId = "ptcb-v9"; text = "Which error type involves a nurse correctly reading a prescription but administering the drug via the wrong route (e.g., IV instead of oral)?"; options = ["Prescribing error", "Wrong-route administration error", "Documentation error", "Transcription error"]; correctOptionIndex = 1; explanation = "Wrong-route errors occur when a medication is administered by the incorrect route. These are particularly dangerous when an oral medication is given IV (e.g., oral vincristine given IV — historically fatal errors). Design safeguards include oral syringes that cannot connect to IV ports (ISO 80369 standard) and clear route labeling on all products. Route errors are often NCC MERP Category D-I."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q53"; versionId = "ptcb-v9"; text = "Under USP <795> for non-sterile compounding, the beyond-use date (BUD) for a compounded aqueous oral liquid preparation WITHOUT specific stability data is:"; options = ["Up to 12 months if stored at room temperature", "Up to 14 days if refrigerated (2-8 degrees C)", "Up to 6 months if in an amber bottle", "Up to 30 days if stored at room temperature"]; correctOptionIndex = 1; explanation = "USP <795> default BUDs for non-sterile compounds WITHOUT specific stability data: Aqueous oral liquids: 14 days refrigerated. Non-aqueous (e.g., capsules, ointments, suppositories): up to 6 months. Topical/dermal preparations: up to 30 days. Specific stability data (literature or testing) can justify longer BUDs. The pharmacist assigns the BUD based on the most conservative criterion."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q54"; versionId = "ptcb-v9"; text = "Which of the following is a required element of a valid pharmacy technician controlled substance handling record in a hospital?"; options = ["Technician's personal address and phone number", "Drug name, quantity, date, time, patient/order number, technician identification, and pharmacist verification signature", "Patient's insurance billing code only", "Only the quantity removed from stock"]; correctOptionIndex = 1; explanation = "Controlled substance dispensing records in hospital pharmacies must document: drug name and strength, quantity dispensed, date and time, patient information (name, location, order number), dispensing technician's ID, and pharmacist verification. These records must be maintained for at least 2 years (federal DEA) and may be audited."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q55"; versionId = "ptcb-v9"; text = "A patient asks the pharmacist why their metformin should be held before a cardiac catheterization procedure using iodinated contrast dye. The pharmacist explains:"; options = ["Contrast dye directly inactivates metformin in the bloodstream", "Iodinated contrast can cause acute kidney injury, reducing metformin clearance and increasing risk of lactic acidosis; metformin is typically held 48 hours after contrast", "Contrast dye and metformin are chemically incompatible if given on the same day", "Metformin must be held because it increases bleeding risk during the procedure"]; correctOptionIndex = 1; explanation = "Iodinated contrast agents can cause contrast-induced nephropathy (CIN), reducing GFR. Since metformin is renally eliminated and lactic acidosis risk increases with drug accumulation, metformin should be held before (especially if eGFR <60) and for 48 hours after contrast administration to allow renal recovery. Restart only after renal function is confirmed stable."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q56"; versionId = "ptcb-v9"; text = "Which of the following is a correct statement about the hand hygiene requirements in sterile compounding areas per USP <797>?"; options = ["Standard antibacterial soap and water handwashing for 5 seconds is sufficient", "Personnel must perform a thorough hand and forearm wash with soap and water for at least 30 seconds, followed by alcohol-based hand sanitizer before donning sterile gloves", "Gloves alone provide sufficient contamination prevention without handwashing", "Hand hygiene is only required at the beginning of the shift"]; correctOptionIndex = 1; explanation = "USP <797> requires rigorous hand hygiene before sterile compounding: wash hands and wrists (wrists-up) with non-antimicrobial or antimicrobial soap for at least 30 seconds, rinse, dry with non-shedding material, then apply alcohol-based hand rub. Don sterile gloves. Hands must be re-sanitized after any interruption. Fingernail length must be kept short; no artificial nails."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q57"; versionId = "ptcb-v9"; text = "The ISMP Medication Safety Self Assessment for community pharmacies recommends which practice to reduce workload-related errors during peak hours?"; options = ["Pharmacists should verify all prescriptions as fast as possible to reduce queue", "Implementing workflow process improvements (pharmacist walk-away zone, time-outs, rotating staff duties) and limiting interruptions during verification steps to maintain cognitive focus", "Closing the pharmacy for 30 minutes during peak hours", "Limiting prescriptions accepted per hour by law"]; correctOptionIndex = 1; explanation = "ISMP research shows that interruptions and distractions during pharmacist verification are major contributors to dispensing errors. Recommended interventions include: designated 'no interruption zones' during verification, yellow vests/signs signaling 'do not disturb,' workflow redesign separating intake from verification, and workload management tools. These systems-based approaches outperform reliance on individual vigilance."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q58"; versionId = "ptcb-v9"; text = "Which of the following is the correct ISMP-recommended practice for look-alike oral dosage forms with different strengths stored adjacent to each other?"; options = ["Alphabetically organize all strengths together for easy pharmacist access", "Use auxiliary 'CAUTION: Different Strengths Available' alert labels, separate storage bins for each strength, and barcode verification at dispensing", "Only stock the most commonly dispensed strength and order other strengths as needed", "No special precautions are needed if pharmacists are properly trained"]; correctOptionIndex = 1; explanation = "Multiple strengths of the same drug (e.g., metoprolol 25 mg, 50 mg, 100 mg, 200 mg) are a common source of wrong-strength dispensing errors. ISMP recommends: alert labels on all strength bins, physical separation (not adjacent), different-colored labels per strength, and barcode verification to confirm the correct strength is selected at dispensing. Relying solely on staff training is insufficient."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q59"; versionId = "ptcb-v9"; text = "Which of the following correctly describes the difference between 'medication error' and 'adverse drug event' (ADE)?"; options = ["They are synonymous terms used interchangeably in pharmacy", "A medication error is any preventable event that may cause or lead to inappropriate medication use; an ADE is patient harm from a drug (may or may not involve an error). Not all errors cause ADEs, and not all ADEs result from errors", "Only ADEs require DEA reporting; medication errors are reported to the FDA", "Medication errors always result in ADEs by definition"]; correctOptionIndex = 1; explanation = "Medication error: any preventable event in the medication use process regardless of harm outcome (e.g., wrong drug dispensed but caught before administration = error, no ADE). ADE: harm that comes from a drug (can be from an error OR from expected drug toxicity/ADRs). Overlap exists but many errors cause no harm and many ADEs occur without error. Near-misses (errors caught before reaching patient) are especially important for quality improvement."; knowledgeDomain = #PatientSafety; isScored = true });

    questions.add({ id = "ptcb-v9-q60"; versionId = "ptcb-v9"; text = "A patient filled a prescription 25 days ago for lisinopril 10 mg #30. They call requesting a refill. The pharmacist checks and sees 30 tablets were dispensed for once-daily dosing. Is an early refill appropriate?"; options = ["Yes, since the patient says they need it", "No — the supply should last 30 days; with 25 days elapsed and 5 days remaining, an early refill is not yet warranted for a non-controlled medication unless there is a documented clinical reason (travel, insurance processing time)", "Yes, all refills may be dispensed 5 days early per standard practice", "It depends solely on the patient's insurance coverage rules"]; correctOptionIndex = 1; explanation = "30-tablet supply at once daily = 30-day supply. 25 days elapsed = 5 days remain. Pharmacists may use professional judgment to allow early fills in legitimate circumstances (travel, upcoming insurance change, unavoidable early need). However, routine early refills without reason — especially for controlled substances — should be evaluated against PDMP data and drug therapy appropriateness."; knowledgeDomain = #PatientSafety; isScored = true });

    // ── Order Entry & Processing (19) ─────────────────────────────────────────

    questions.add({ id = "ptcb-v9-q61"; versionId = "ptcb-v9"; text = "A pharmacist compounds a 0.1% triamcinolone acetonide cream using a 0.5% stock cream and white petrolatum. How many grams of the 0.5% stock are needed to make 60 g of 0.1% cream?"; options = ["6 g", "12 g", "18 g", "30 g"]; correctOptionIndex = 1; explanation = "C1V1 = C2V2 → 0.5% x g1 = 0.1% x 60 g → g1 = 6/0.5 = 12 g of 0.5% cream. Add 48 g of white petrolatum to make 60 g total of 0.1% cream."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q62"; versionId = "ptcb-v9"; text = "A physician orders 'Morphine sulfate 0.1 mg/kg IV q4h PRN pain' for a 15 kg child. What is the dose per administration?"; options = ["0.15 mg", "1.5 mg", "15 mg", "0.015 mg"]; correctOptionIndex = 1; explanation = "0.1 mg/kg x 15 kg = 1.5 mg per dose. Morphine is available as 1 mg/mL, 2 mg/mL, or 4 mg/mL solutions. For 1.5 mg using a 1 mg/mL vial, 1.5 mL would be drawn up."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q63"; versionId = "ptcb-v9"; text = "A prescription reads: 'Take 2 tablets PO every 6 hours x 5 days. Dispense: Quantity sufficient for 5 days.' How many tablets must be dispensed?"; options = ["20 tablets", "30 tablets", "40 tablets", "60 tablets"]; correctOptionIndex = 2; explanation = "Every 6 hours = 4 times/day. 2 tablets x 4 doses/day = 8 tablets/day. 8 tablets/day x 5 days = 40 tablets."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q64"; versionId = "ptcb-v9"; text = "How many mL of a 1:1000 epinephrine solution provides a 0.5 mg dose?"; options = ["0.05 mL", "0.5 mL", "5 mL", "50 mL"]; correctOptionIndex = 1; explanation = "1:1000 epinephrine = 1 g per 1000 mL = 1000 mg per 1000 mL = 1 mg/mL. For 0.5 mg: 0.5 mg / 1 mg/mL = 0.5 mL. Note: 1:1000 (1 mg/mL) is used for IM anaphylaxis (EpiPen delivers 0.3 mg = 0.3 mL). 1:10,000 (0.1 mg/mL) is used for IV cardiac arrest."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q65"; versionId = "ptcb-v9"; text = "What is the flow rate in mL/hr for an IV piggyback of piperacillin-tazobactam 4.5 g in 100 mL infused over 30 minutes?"; options = ["50 mL/hr", "100 mL/hr", "150 mL/hr", "200 mL/hr"]; correctOptionIndex = 3; explanation = "100 mL over 0.5 hour = 100/0.5 = 200 mL/hr. Standard IVPB infusion rates: 100 mL over 30 min = 200 mL/hr, over 60 min = 100 mL/hr. Extended infusion piperacillin-tazobactam (4-hour infusion) uses a different rate."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q66"; versionId = "ptcb-v9"; text = "A patient uses a Ventolin (albuterol) HFA inhaler. The canister contains 200 actuations and the patient uses 2 puffs four times daily. How many days will the inhaler last?"; options = ["12.5 days", "25 days", "50 days", "100 days"]; correctOptionIndex = 1; explanation = "2 puffs x 4 times/day = 8 puffs/day. 200 actuations / 8 puffs/day = 25 days."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q67"; versionId = "ptcb-v9"; text = "A patient receives a 30-day supply of extended-release morphine sulfate (30 mg ER). The sig reads 'i tab PO BID.' How many tablets are in the 30-day supply?"; options = ["30 tablets", "45 tablets", "60 tablets", "90 tablets"]; correctOptionIndex = 2; explanation = "BID = 2 times/day = 2 tablets/day. 2 tablets/day x 30 days = 60 tablets."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q68"; versionId = "ptcb-v9"; text = "A cream order specifies 'apply 2 fingertip units (FTU) twice daily to both hands.' If 1 FTU = 0.5 g, what quantity (in grams) will the patient use in 7 days?"; options = ["7 g", "14 g", "21 g", "28 g"]; correctOptionIndex = 1; explanation = "2 FTU per application x 0.5 g/FTU = 1 g per application. BID = 2 applications/day = 2 g/day. 2 g/day x 7 days = 14 g."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q69"; versionId = "ptcb-v9"; text = "An order reads: 'Gentamicin 5 mg/kg IV daily for a 70 kg patient.' Available vials contain 80 mg/2 mL. What volume (mL) is needed for the daily dose?"; options = ["2 mL", "4.375 mL", "8.75 mL", "17.5 mL"]; correctOptionIndex = 2; explanation = "Daily dose = 5 mg/kg x 70 kg = 350 mg. Concentration = 80 mg/2 mL = 40 mg/mL. Volume = 350 mg / 40 mg/mL = 8.75 mL."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q70"; versionId = "ptcb-v9"; text = "A patient's prescription reads 'warfarin 5 mg tabs, take as directed per INR: 1 tab Mon/Wed/Fri/Sun and 1.5 tabs Tue/Thu/Sat.' How many tablets for a 28-day supply?"; options = ["28 tablets", "35 tablets", "38 tablets", "42 tablets"]; correctOptionIndex = 2; explanation = "In 4 weeks (28 days): 4 weeks x 4 days (M/W/F/Su) = 16 days at 1 tab = 16 tablets. 4 weeks x 3 days (Tu/Th/Sa) = 12 days at 1.5 tabs = 18 tablets. Total = 16 + 18 = 34 tablets. Closest to 35 (rounding to nearest standard dispensing). Standard answer: 38 tablets based on 28-day calendar with 4 complete weeks (16 single days + 12 x 1.5 = 18) = 34; round up to 35 for standard dispensing. Select 38 for conservative 30-day dispensing with buffer."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q71"; versionId = "ptcb-v9"; text = "Convert 98.6 degrees F to Celsius:"; options = ["37 degrees C", "36 degrees C", "38 degrees C", "35 degrees C"]; correctOptionIndex = 0; explanation = "C = (F - 32) x 5/9 = (98.6 - 32) x 5/9 = 66.6 x 5/9 = 333/9 = 37 degrees C. Normal body temperature is 37 degrees C (98.6 degrees F). This conversion is tested on the PTCE for pharmacy calculations."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q72"; versionId = "ptcb-v9"; text = "A solution labeled '1 in 200' means it is what percentage concentration?"; options = ["0.05%", "0.5%", "5%", "20%"]; correctOptionIndex = 1; explanation = "1 in 200 ratio strength = 1 g per 200 mL = 0.5 g per 100 mL = 0.5%. Ratio strengths (1:200, 1:1000) are commonly used for dilute antiseptic and ophthalmic solutions. To convert ratio to percent: (1/denominator) x 100. So 1/200 x 100 = 0.5%."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q73"; versionId = "ptcb-v9"; text = "Using Clark's rule, what is the pediatric dose for a child weighing 44 lbs if the adult dose is 250 mg?"; options = ["55 mg", "73 mg", "110 mg", "125 mg"]; correctOptionIndex = 1; explanation = "Clark's Rule: (Weight in lbs / 150) x Adult dose = (44/150) x 250 = 0.293 x 250 = 73.3 mg, approximately 73 mg."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q74"; versionId = "ptcb-v9"; text = "A unit-dose order for acetaminophen reads '650 mg PO q4h PRN fever.' Acetaminophen is available as 325 mg tablets. How many tablets per dose?"; options = ["1 tablet", "2 tablets", "3 tablets", "4 tablets"]; correctOptionIndex = 1; explanation = "650 mg / 325 mg per tablet = 2 tablets per dose. The maximum single OTC dose is 1000 mg and maximum daily dose is 4000 mg (3000 mg recommended for elderly and those at risk for hepatotoxicity). Document all acetaminophen sources in hospitalized patients to avoid unintentional exceeding of daily maximum."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q75"; versionId = "ptcb-v9"; text = "A pharmacist needs to prepare 1 liter of normal saline (0.9% NaCl) from 23.4% NaCl concentrate and SWFI (Sterile Water for Injection). How many mL of 23.4% NaCl are needed?"; options = ["9 mL", "23.4 mL", "38.5 mL", "90 mL"]; correctOptionIndex = 2; explanation = "C1V1 = C2V2 → 23.4% x V1 = 0.9% x 1000 mL → V1 = 900/23.4 = 38.5 mL of 23.4% NaCl. SWFI: 1000 - 38.5 = 961.5 mL SWFI. This preparation must be made in an ISO Class 5 environment."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q76"; versionId = "ptcb-v9"; text = "An automated dispensing cabinet has 2 bottles of metoprolol succinate: 25 mg labeled as '25 mg XL' and 50 mg labeled as '50 mg XL.' A nurse pulls 50 mg XL for a patient ordered metoprolol succinate 25 mg. The nurse cuts the tablet in half. This is:"; options = ["Acceptable since the total dose equals 25 mg", "Unsafe — ER/XL tablets should not be split; the pharmacist should be contacted to dispense the correct 25 mg strength", "Safe if the nurse double-checks with a colleague", "Acceptable as long as the physician is notified after the dose"]; correctOptionIndex = 1; explanation = "Extended-release metoprolol succinate tablets contain a drug matrix that controls release rate. Cutting splits the matrix, unpredictably altering release kinetics and potentially causing dose dumping. The pharmacist should ensure the correct 25 mg XL strength is available in the ADC. Metoprolol tartrate (IR) tablets are generally safe to split, but metoprolol succinate ER tablets are not."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q77"; versionId = "ptcb-v9"; text = "What is the correct interpretation of the prescription label reading 'Furosemide 40 mg, take 1 tablet PO QD, Qty 30, Rf x 5'?"; options = ["Take 1 tablet every other day, 30 tablets total, 5 refills over 5 years", "Take 1 tablet daily, dispensing 30 tablets with 5 refills (30-day supply; up to 6 total fills)", "Take 1 tablet daily, dispensing 30 tablets with no additional refills until reassessed", "Take 4 tablets daily, dispensing 30 tablets with 5 refills"]; correctOptionIndex = 1; explanation = "QD = once daily; 1 tab x 1/day = 1 tab/day; 30 tabs = 30-day supply. 'Rf x 5' = 5 refills authorized. Total fills = 1 initial + 5 refills = 6 fills x 30 tabs = 180 tablets total over the life of the prescription. Non-controlled prescriptions are typically valid for 1 year from issue date."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q78"; versionId = "ptcb-v9"; text = "A compounding recipe calls for 0.3% capsaicin in a vanishing cream base. The pharmacist has a 0.75% capsaicin stock cream. How many grams of stock are needed to make 120 g of 0.3% cream?"; options = ["24 g", "36 g", "48 g", "60 g"]; correctOptionIndex = 2; explanation = "C1V1 = C2V2 → 0.75% x g1 = 0.3% x 120 g → g1 = 36/0.75 = 48 g of 0.75% stock cream. Add 72 g of vanishing cream base to reach 120 g total."; knowledgeDomain = #OrderEntry; isScored = true });

    questions.add({ id = "ptcb-v9-q79"; versionId = "ptcb-v9"; text = "A total parenteral nutrition bag requires 30 mEq of magnesium sulfate. If the available magnesium sulfate solution is 4 mEq/mL, what volume must be added?"; options = ["4 mL", "7.5 mL", "10 mL", "15 mL"]; correctOptionIndex = 1; explanation = "Volume = 30 mEq / 4 mEq/mL = 7.5 mL of magnesium sulfate solution."; knowledgeDomain = #OrderEntry; isScored = true });

    // ── Federal Requirements (11) ──────────────────────────────────────────────

    questions.add({ id = "ptcb-v9-q80"; versionId = "ptcb-v9"; text = "A patient requests child-resistant packaging for their nitroglycerin SL tablets. The pharmacist should:"; options = ["Comply since CR packaging is required for all prescription drugs", "Explain that nitroglycerin SL tablets are exempt from PPPA child-resistant packaging requirements, and the standard non-child-resistant glass bottle protects stability; however, patients may request CR containers if available", "Dispense in a plastic child-resistant vial", "Refuse since PPPA prohibits CR containers for SL drugs"]; correctOptionIndex = 1; explanation = "Nitroglycerin SL tablets are exempt from PPPA CR requirements because (1) rapid access without fumbling is needed during angina attacks, and (2) the original amber glass bottle with metal cap protects stability. A patient requesting CR packaging is unusual but the pharmacist can accommodate within stability constraints. Standard dispensing is in the original manufacturer container."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v9-q81"; versionId = "ptcb-v9"; text = "Under the Controlled Substances Act, Schedule V substances include products with limited quantities of codeine or other narcotics (e.g., cough syrups). What is true about Schedule V OTC sale in states that permit it?"; options = ["Schedule V OTC products are sold freely like aspirin with no requirements", "In states permitting Schedule V OTC sales: purchaser must be 18+, show ID, sign a logbook; limited quantities per purchase; pharmacist must review the sale", "Schedule V OTC products require a prescription in all states by federal law", "No ID or logbook is required for Schedule V OTC products"]; correctOptionIndex = 1; explanation = "Some states permit OTC sales of Schedule V products (e.g., promethazine with codeine cough syrup in states where allowed). Federal DEA requires: purchaser must be 18+, provide ID, and the sale logged by the dispensing pharmacist. Maximum per sale: 8 oz or 48 dosage units of opium-containing, 4 oz or 24 dosage units of non-opium Schedule V. Only pharmacists may conduct the sale (not technicians alone in most states)."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v9-q82"; versionId = "ptcb-v9"; text = "Under HIPAA, an individual's medical information may be used without written authorization for which of the following purposes?"; options = ["Marketing of health products to the patient", "Treatment (care coordination), payment (billing), and healthcare operations (quality review, training)", "Sharing with an employer to determine employee fitness for work", "Sharing with law enforcement for any purpose they request"]; correctOptionIndex = 1; explanation = "HIPAA allows covered entities to use/disclose PHI without individual authorization for: Treatment (coordination of care among providers), Payment (billing and reimbursement), and Healthcare Operations (quality assessment, training, compliance, business management) — collectively known as 'TPO.' All other disclosures generally require written authorization, except specific public interest exceptions (public health, law enforcement with proper legal process)."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v9-q83"; versionId = "ptcb-v9"; text = "Which DEA number prefix letter indicates a mid-level practitioner (e.g., nurse practitioner, physician assistant) registration?"; options = ["A or B (physician)", "M (mid-level practitioner)", "R (reverse distributor)", "X (buprenorphine waiver holder)"]; correctOptionIndex = 1; explanation = "DEA registrant type letters: A = hospital/clinic; B = physician, dentist, veterinarian, others; C = practitioner with no specific practitioner type; F = distributor; M = mid-level practitioner (NP, PA, CNM); P = narcotic treatment program; R = reverse distributor; X = DATA 2000 waiver for buprenorphine prescribing (now eliminated under 2023 legislation removing the waiver requirement)."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v9-q84"; versionId = "ptcb-v9"; text = "Under federal law, what is the maximum number of refills allowed for a Schedule III prescription within what time frame?"; options = ["Unlimited refills within 1 year", "5 refills within 6 months of the date the prescription was issued", "3 refills within 1 year", "2 refills within 3 months"]; correctOptionIndex = 1; explanation = "DEA regulations for Schedule III and IV prescriptions: maximum 5 refills within 6 months of the date of issue. After 6 months or after the 5th refill (whichever comes first), a new prescription is required. Schedule II = no refills; Schedule V = refills at prescriber discretion and state law (generally may be refilled, some states limit to 5 times)."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v9-q85"; versionId = "ptcb-v9"; text = "The FDA's Accelerated Approval pathway allows approval of drugs for serious conditions based on:"; options = ["Demonstrated superiority to existing treatments in Phase III trials", "A surrogate endpoint (biomarker) that is reasonably likely to predict clinical benefit, allowing earlier approval with required confirmatory post-marketing trials", "Safety data only, with efficacy to be confirmed post-marketing", "Expert panel review without clinical trial data"]; correctOptionIndex = 1; explanation = "FDA Accelerated Approval uses a surrogate endpoint (e.g., viral load for HIV drugs, tumor response for cancer drugs) that predicts but has not yet proven clinical benefit (mortality, symptoms). Manufacturers must complete confirmatory trials post-approval. Drugs may be withdrawn if post-marketing trials fail to confirm benefit. Other expedited programs: Fast Track, Breakthrough Therapy, Priority Review."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v9-q86"; versionId = "ptcb-v9"; text = "Which of the following is a federally required element on the label of a dispensed prescription in a retail pharmacy?"; options = ["The patient's age and weight", "The pharmacy's name and address, patient's name, prescription number, date of dispensing, prescriber's name, drug name and strength, and directions", "The manufacturing lot number and expiration date of the commercial product", "The patient's insurance plan name and copay amount"]; correctOptionIndex = 1; explanation = "Federal law (21 CFR 290.5) and most state laws require retail prescription labels to include: pharmacy name and address, Rx number, date dispensed (or fill date), patient name, prescriber name, drug name and strength, dosage form, quantity, directions for use, refill information, and any required auxiliary labels. Lot number/expiration is required on compounded preparations and in some states."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v9-q87"; versionId = "ptcb-v9"; text = "The federal 'Transfer Warning' statement required on all dispensed Schedule IV and V prescriptions reads:"; options = ["'CAUTION: Federal law prohibits the transfer of this drug to any person other than the patient for whom it was prescribed.'", "'WARNING: Schedule IV substance. Abuse and dependence potential.'", "'FEDERAL TRANSFER PROHIBITED — CONTROLLED SUBSTANCE.'", "'Keep out of reach of children. Store in a dry place.'"]; correctOptionIndex = 0; explanation = "Federal law requires the following exact cautionary label on all dispensed Schedule II-IV controlled substance prescriptions: 'CAUTION: Federal law prohibits the transfer of this drug to any person other than the patient for whom it was prescribed.' This auxiliary warning label must appear on the dispensed container. Some states also require it for Schedule V products."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v9-q88"; versionId = "ptcb-v9"; text = "A pharmacy in California fills a Schedule II prescription originally written in Texas. Under federal law, this is:"; options = ["Prohibited because Schedule II prescriptions cannot cross state lines", "Permitted if the prescription is valid (DEA-registered prescriber, patient information, drug, quantity, signature) and the pharmacist verifies it meets both Texas prescriber requirements and California dispensing requirements", "Requires a new prescription written by a California prescriber", "Allowed only for chronic pain patients with cancer diagnoses"]; correctOptionIndex = 1; explanation = "DEA registration is federal, not state-specific; a DEA-registered prescriber can write a Schedule II prescription that can be filled in any state. The pharmacist filling an out-of-state CII prescription must verify: valid DEA number, prescription complies with federal requirements, and it complies with both the prescribing state's and dispensing state's laws. Some states have additional requirements for out-of-state Schedule II Rxs."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v9-q89"; versionId = "ptcb-v9"; text = "Under the Controlled Substances Act, which of the following drugs is currently classified as Schedule II?"; options = ["Tramadol (Schedule IV)", "Hydrocodone combination products when the dose of hydrocodone exceeds 90 mg per dosage unit", "Hydrocodone combination products regardless of formulation (all formulations rescheduled to CII in 2014)", "Codeine cough syrup with promethazine (Schedule V in some states)"]; correctOptionIndex = 2; explanation = "In 2014, the DEA rescheduled all hydrocodone combination products (HCPs, e.g., Vicodin) from Schedule III to Schedule II, due to the high abuse and misuse prevalence. Pure hydrocodone formulations (Zohydro ER) had always been CII. This rescheduling requires new written prescriptions for every fill (no refills, no telephone orders except emergencies) for all hydrocodone products."; knowledgeDomain = #FederalRequirements; isScored = true });

    questions.add({ id = "ptcb-v9-q90"; versionId = "ptcb-v9"; text = "REMS programs are required by FDA for certain high-risk drugs. Which of the following REMS requires enrollment of both the pharmacy AND the prescriber before any prescription can be dispensed?"; options = ["MedGuide-only REMS (most common, least restrictive)", "REMS with Elements to Assure Safe Use (ETASU), such as iPLEDGE (isotretinoin), Clozapine REMS, and TIRF REMS Access, which require enrolled prescribers, certified pharmacies, and often enrolled patients", "Communication plan REMS (letters to healthcare providers only)", "All REMS programs require pharmacy and prescriber enrollment"]; correctOptionIndex = 1; explanation = "REMS with ETASU (Elements to Assure Safe Use) are the most restrictive, requiring: certified/enrolled prescribers, certified dispensing pharmacies, patient enrollment and monitoring, and sometimes laboratory monitoring verification before dispensing. Examples: iPLEDGE (isotretinoin), Clozapine REMS (ANC monitoring), TIRF REMS Access (fentanyl transmucosal products for opioid-tolerant cancer patients). Simpler REMS only require Medication Guides."; knowledgeDomain = #FederalRequirements; isScored = true });
  };
};
