import Types "../types/exams";

module {
  public func embeddedPtcbPayload() : [Types.Question] {
    return [
      { id = "ptcb-org-0001"; versionId = "ptcb-org-v1"; text = "The puncture-resistant container that is used for needle disposal is referred to as a:"; options = ["waste container.", "trash container.", "sharps container.", "needle container."]; correctOptionIndex = 2; explanation = "Sharps containers are rigid, puncture-resistant medical disposal units constructed safely for discarding needles, active syringes, and lancets."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0002"; versionId = "ptcb-org-v1"; text = "Under the Combat Methamphetamine Epidemic Act of 2005, patients must sign a log and provide valid photo identification in order to purchase OTC products that contain:"; options = ["guaifenesin.", "pseudoephedrine.", "phenylephrine.", "dextromethorphan."]; correctOptionIndex = 1; explanation = "Pseudoephedrine is a precursor chemical used in the illicit synthesis of methamphetamine. Federal rules restrict sales with identification checks. "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0003"; versionId = "ptcb-org-v1"; text = "According to federal law, a complete inventory of the controlled substances on hand in a pharmacy must be made every:"; options = ["month.", "6 months.", "year.", "2 years."]; correctOptionIndex = 3; explanation = "The Controlled Substances Act mandates that DEA-registered pharmacies perform a comprehensive physical inventory count of all controlled items biennially (every 2 years)."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0004"; versionId = "ptcb-org-v1"; text = "The Food and Drug Administration (FDA) may require a Medication Guide to be dispensed as part of a(n);"; options = ["market withdrawal.", "failure modes and effects analysis.", "REMS program.", "investigational new drug application."]; correctOptionIndex = 2; explanation = "Risk Evaluation and Mitigation Strategies (REMS) are comprehensive drug safety protocols mandated by the FDA to ensure benefits outweigh serious risks. "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0005"; versionId = "ptcb-org-v1"; text = "Which of the following elements is a unique identifier assigned by the manufacturer to look up a single production batch?"; options = ["National Drug Code", "Lot number", "Expiration date", "Package size."]; correctOptionIndex = 1; explanation = "A lot number identifies a specific batch or production run of a drug from a manufacturer, critical for tracking quality control and recalls."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0006"; versionId = "ptcb-org-v1"; text = "Which of the following auxiliary labels is most crucial for a prescription of a suspension antibiotic?"; options = ["Avoid long exposure to sunlight", "Take with a full glass of milk", "Shake well before using", "May cause drowsiness."]; correctOptionIndex = 2; explanation = "Suspensions contain undissolved solid particles that settle over time. Shaking ensures uniform distribution of the active ingredient before each dose. "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0008"; versionId = "ptcb-org-v1"; text = "If the expiration date of a drug product is May 2027, the drug should no longer be used by patients after:"; options = ["April 30, 2027", "May 1, 2027", "May 31, 2027", "June 1, 2027."]; correctOptionIndex = 2; explanation = "When a manufacturer's expiration date specifies only a month and a year, the product remains safe and fully potent until the final day of that month. "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0010"; versionId = "ptcb-org-v1"; text = "Which of the following is the procedure for proper disposal of legend drugs that have passed the expiration date printed on the container?"; options = ["Place it behind newer stock until an intern can throw it away.", "Put it in a trash bag mixed with liquid soap and discard.", "Return it to the FDA directly via certified mail.", "Isolate and label the expired medication until it can be processed by an approved reverse distribution"]; correctOptionIndex = 3; explanation = "Expired legend drugs must be quarantined from regular inventory and safely transferred to an authorized reverse distributor for legal destruction and credit. "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0011"; versionId = "ptcb-org-v1"; text = "If a drug has the expiration date December 2025, it actually expires at midnight on:"; options = ["November 30, 2025.", "December 1, 2026.", "December 15, 2026.", "December 31, 2025."]; correctOptionIndex = 3; explanation = "Potency parameters extend up to midnight of the very last day of the calendar month printed on the commercial package."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0013"; versionId = "ptcb-org-v1"; text = "According to federal law, which of the following drug products must bear two sets of expiration information in its labeling?"; options = ["A homeopathic product treating serious chronic conditions", "An allergenic extract labeled 'No U.S. Standard of Potency'", "An OTC product stable for at least three years", "A prescription medication intended for reconstitution prior to dispensing."]; correctOptionIndex = 3; explanation = "Dry-powder antibiotics requiring reconstitution must specify the dry shelf life expiration as well as the short-term active limit once liquid is introduced. "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0015"; versionId = "ptcb-org-v1"; text = "An expiration date of 7/2025 on a vial of mumps virus live vaccine means that the vial contents expire:"; options = ["on 6/30 of 2025.", "on 7/1 of 2025.", "on 7/31 of 2025.", "6 months past this date."]; correctOptionIndex = 2; explanation = "Standard FDA manufacturing policy validates the active potency of biological vaccine vials until the absolute final calendar day of July. "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0016"; versionId = "ptcb-org-v1"; text = "In order to ensure that the appropriate product was selected from the shelf, a pharmacy technician should verify the medication's:"; options = ["expiration date.", "lot number.", "package size.", "National Drug Code."]; correctOptionIndex = 3; explanation = "The National Drug Code (NDC) acts as a universal identifier confirming drug identity, manufacturer, and exact package size, preventing pick errors."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0017"; versionId = "ptcb-org-v1"; text = "Pen needles would be most appropriate for a patient with a prescription for which of the following injectable medications?"; options = ["Lovenox", "Depo-Provera", "Enbrel", "Byetta."]; correctOptionIndex = 3; explanation = "Byetta (Exenatide) is an injectable medication provided in a multi-dose pen delivery device that requires an attachable external pen needle. "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0018"; versionId = "ptcb-org-v1"; text = "Which two items on a manufacturer's bottle are typically used to identify recalled drugs?"; options = ["DEA number and medication schedule", "NDC number and expiration date", "Lot number and expiration date", "NDC number and lot number."]; correctOptionIndex = 3; explanation = "Drug product recalls target specific batches. The NDC establishes the product profile line, and the Lot Number points to the affected facility batch."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0019"; versionId = "ptcb-org-v1"; text = "The abbreviation 'b.i.d.' is an example of a medication:"; options = ["quantity.", "strength.", "dosage form.", "frequency."]; correctOptionIndex = 3; explanation = "'b.i.d.' represents bis in die, translating directly to 'twice a day', defining the daily frequency parameter."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0020"; versionId = "ptcb-org-v1"; text = "Which of the following abbreviations represents 'under the tongue'?"; options = ["PO", "SL", "SQ", "PR"]; correctOptionIndex = 1; explanation = "'SL ' stands for sublingual, meaning to place or administer a fast-dissolving tablet beneath the tongue. "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0021"; versionId = "ptcb-org-v1"; text = "Which of the following statements regarding specific patient medication returns in the hospital setting is correct?"; options = ["Unlabeled medications may be dispensed by the nurse at discharge", "Unopened units-of-use returned from outpatients may be redispensed", "Unopened units-of-use returned from inpatients may be redispensed", "Crediting of used doses should be completed prior to dispensing."]; correctOptionIndex = 2; explanation = "In an internal hospital environment, unopened unit-dose packages returned from floor stock are acceptable to return to active inventory."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0022"; versionId = "ptcb-org-v1"; text = "A physician writes the following prescription: Carafate oral suspension 1 g/10 mL. Sig: 10 mL q.i.d. a.c. & h.s., Disp: 14 oz. This prescription label should read:"; options = ["Take 1 tablespoonful 4 times a day after meals and at bedtime", "Take 2 teaspoonfuls 4 times a day before meals and at bedtime", "Take 2 teaspoonfuls 4 times a day after meals and at bedtime", "Take 1 tablespoonful 4 times a day before meals and at bedtime."]; correctOptionIndex = 1; explanation = "1 teaspoonful (tsp) is 5 mL, so 10 mL equals 2 teaspoonfuls. 'q.i.d.' is four times daily, 'a.c.' means before meals, and 'h.s.' means at bedtime. "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0024"; versionId = "ptcb-org-v1"; text = "A reverse distributor for pharmaceuticals:"; options = ["distributes pharmaceuticals to hospitals.", "removes and disposes of pharmaceutical waste.", "transports medications from the manufacturer to the wholesaler.", "transports medications in an emergency."]; correctOptionIndex = 1; explanation = "Reverse distributors operate to coordinate legal compliance destruction, verification logging, and credits for expired commercial pharmaceuticals."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0025"; versionId = "ptcb-org-v1"; text = "Humalog 5 units SQ t.i.d. 5 min p.c. and 2 units SQ q.h.s. UD means the patient is instructed to inject 5 units three times a day:"; options = ["5 minutes after meals and 2 units every hour as directed.", "5 minutes after meals and 2 units at bedtime as directed.", "5 minutes before meals and 2 units every hour as directed.", "5 minutes before meals and 2 units at bedtime as directed."]; correctOptionIndex = 1; explanation = "'t.i.d.' means three times daily, 'p.c.' means after meals (post cibum), and 'q.h.s.' signifies at bedtime (hora somni). "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0026"; versionId = "ptcb-org-v1"; text = "Medications' lot numbers are assigned by the:"; options = ["Food and Drug Administration (FDA).", "Drug Enforcement Administration (DEA).", "wholesaler.", "manufacturer."]; correctOptionIndex = 3; explanation = "Lot identification sequences are strictly designated internally by the manufacturer during batch production to track chemical synthesis lines."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0027"; versionId = "ptcb-org-v1"; text = "The pharmacy receives the following prescription: Levofloxacin 0.5% solution, #1 bottle. Sig: 2 gtts OD q2h while awake on days 1-2 then 2 gtts OD q4h while awake on days 3-7. Where is the patient instructed to use the medication?"; options = ["Left eye", "Left ear", "Right eye", "Right ear"]; correctOptionIndex = 2; explanation = "The abbreviation 'OD' stands for oculus dexter, which is the standard abbreviation designating the patient's right eye. "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0028"; versionId = "ptcb-org-v1"; text = "Which of the following medications should be pulled from inventory due to incorrect storage?"; options = ["Boostrix that was stored in a refrigerator", "Havrix that was stored in a refrigerator", "Shingrix that was stored in a freezer", "Varivax that was stored in a freezer."]; correctOptionIndex = 2; explanation = "Shingrix (recombinant shingles vaccine) must be refrigerated between 2°C and 8°C. Freezing it permanently degrades the active viral protein structure."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0029"; versionId = "ptcb-org-v1"; text = "A vial of medication shows the manufacturer's expiration date as November 2026. The last date on which this medication may be used is:"; options = ["October 31, 2026.", "November 1, 2026.", "November 30, 2026.", "6 months after the stated date."]; correctOptionIndex = 2; explanation = "When the manufacturer label specifies only the month, the item remains fully potent until the final calendar day of that month (November 30, 2026). "; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0030"; versionId = "ptcb-org-v1"; text = "Which part of the meniscus should the pharmacy technician use to measure water in a graduated cylinder?"; options = ["The top", "The bottom", "The left", "The right"]; correctOptionIndex = 1; explanation = "Due to capillary action and surface tension, clear liquids form a downward curve in glass containers. Measurements must always be verified at the lowest point, or bottom, of the meniscus curve."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0037"; versionId = "ptcb-org-v1"; text = "A vial containing a hazardous material breaks in the pharmacy cleanroom. Which of the following items must be on hand immediately?"; options = ["Paper towels and bleach", "A spill kit with usage policy", "Alcohol-free surface cleaner", "Bactericidal scrub soap."]; correctOptionIndex = 1; explanation = "OSHA and USP Chapter 800 mandate that specialized toxic containment spill kits be instantly accessible in spaces handling hazardous agents."; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0038"; versionId = "ptcb-org-v1"; text = "Handling hazardous cytotoxic or antineoplastic drugs should always be completed:"; options = ["inside a common chemical laminar flow hood.", "while wearing double chemotherapy-approved personal protective equipment.", "using disposable kitchen gloves washed out between operations.", "inside a positive-pressure room configuration."]; correctOptionIndex = 1; explanation = "USP Chapter 800 sets absolute safety parameters specifying protective personal equipment barriers including appropriate specialized chemotherapy gloves.  SECTION 2: CONTROLLED SUBSTANCES ACT & FEDERAL LEGAL FRAMEWORKS"; knowledgeDomain = #Other("imported"); isScored = false; },
      { id = "ptcb-org-0039"; versionId = "ptcb-org-v1"; text = "Which of the following medications is a hazardous drug that requires special handling?"; options = ["Atorvastatin", "Lovastatin", "Cisplatin", "Gabapentin"]; correctOptionIndex = 2; explanation = "Cisplatin is an antineoplastic (chemotherapy) agent classified as a Group 1 hazardous drug by NIOSH, carrying carcinogenicity and reproductive toxicity risks."; knowledgeDomain = #Other("imported"); isScored = false; },

      { id = "ptcb-org-0336"; versionId = "ptcb-org-v1"; text = "An order for a 1 mg atropine injection is filled using a vial labeled 0.4 mg/mL. What volume of the solution, in mL, should be administered?"; options = ["0.4", "1.5", "2", "2.5"]; correctOptionIndex = 3; explanation = "Divide required target mass by solution concentration: 1 mg / 0.4 mg/mL = 2.5 mL. "; knowledgeDomain = #Other("imported"); isScored = false; }
    ];
  }
}
