/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CertificationExam = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const KnowledgeDomain = IDL.Variant({
  'Medications' : IDL.Null,
  'FederalRequirements' : IDL.Null,
  'OrderEntry' : IDL.Null,
  'Other' : IDL.Text,
  'PatientSafety' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'versionId' : IDL.Text,
  'knowledgeDomain' : KnowledgeDomain,
  'explanation' : IDL.Text,
  'text' : IDL.Text,
  'isScored' : IDL.Bool,
  'correctOptionIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const ExamVersion = IDL.Record({
  'id' : IDL.Text,
  'scoredQuestions' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timeLimitMinutes' : IDL.Nat,
  'examId' : IDL.Text,
  'versionName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addExam' : IDL.Func([CertificationExam], [], []),
  'getExamDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CertificationExam)],
      ['query'],
    ),
  'getExamQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getExamVersions' : IDL.Func([IDL.Text], [IDL.Vec(ExamVersion)], ['query']),
  'getExams' : IDL.Func([], [IDL.Vec(CertificationExam)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CertificationExam = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const KnowledgeDomain = IDL.Variant({
    'Medications' : IDL.Null,
    'FederalRequirements' : IDL.Null,
    'OrderEntry' : IDL.Null,
    'Other' : IDL.Text,
    'PatientSafety' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'versionId' : IDL.Text,
    'knowledgeDomain' : KnowledgeDomain,
    'explanation' : IDL.Text,
    'text' : IDL.Text,
    'isScored' : IDL.Bool,
    'correctOptionIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const ExamVersion = IDL.Record({
    'id' : IDL.Text,
    'scoredQuestions' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timeLimitMinutes' : IDL.Nat,
    'examId' : IDL.Text,
    'versionName' : IDL.Text,
  });
  
  return IDL.Service({
    'addExam' : IDL.Func([CertificationExam], [], []),
    'getExamDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CertificationExam)],
        ['query'],
      ),
    'getExamQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
    'getExamVersions' : IDL.Func([IDL.Text], [IDL.Vec(ExamVersion)], ['query']),
    'getExams' : IDL.Func([], [IDL.Vec(CertificationExam)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };