/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CertificationExam {
  'id' : string,
  'name' : string,
  'description' : string,
}
export interface ExamVersion {
  'id' : string,
  'scoredQuestions' : bigint,
  'totalQuestions' : bigint,
  'timeLimitMinutes' : bigint,
  'examId' : string,
  'versionName' : string,
}
export type KnowledgeDomain = { 'Medications' : null } |
  { 'FederalRequirements' : null } |
  { 'OrderEntry' : null } |
  { 'Other' : string } |
  { 'PatientSafety' : null };
export interface Question {
  'id' : string,
  'versionId' : string,
  'knowledgeDomain' : KnowledgeDomain,
  'explanation' : string,
  'text' : string,
  'isScored' : boolean,
  'correctOptionIndex' : bigint,
  'options' : Array<string>,
}
export interface _SERVICE {
  'addExam' : ActorMethod<[CertificationExam], undefined>,
  'getExamDetails' : ActorMethod<[string], [] | [CertificationExam]>,
  'getExamQuestions' : ActorMethod<[string], Array<Question>>,
  'getExamVersions' : ActorMethod<[string], Array<ExamVersion>>,
  'getExams' : ActorMethod<[], Array<CertificationExam>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];