/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Question {
    id: string;
    versionId: string;
    knowledgeDomain: KnowledgeDomain;
    explanation: string;
    text: string;
    isScored: boolean;
    correctOptionIndex: bigint;
    options: Array<string>;
}
export interface CertificationExam {
    id: string;
    name: string;
    description: string;
}
export type KnowledgeDomain = {
    __kind__: "Medications";
    Medications: null;
} | {
    __kind__: "FederalRequirements";
    FederalRequirements: null;
} | {
    __kind__: "OrderEntry";
    OrderEntry: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "PatientSafety";
    PatientSafety: null;
};
export interface ExamVersion {
    id: string;
    scoredQuestions: bigint;
    totalQuestions: bigint;
    timeLimitMinutes: bigint;
    examId: string;
    versionName: string;
}
export interface backendInterface {
    addExam(exam: CertificationExam): Promise<void>;
    getExamDetails(examId: string): Promise<CertificationExam | null>;
    getExamQuestions(versionId: string): Promise<Array<Question>>;
    getExamVersions(examId: string): Promise<Array<ExamVersion>>;
    getExams(): Promise<Array<CertificationExam>>;
}
import type { CertificationExam as _CertificationExam, KnowledgeDomain as _KnowledgeDomain, Question as _Question } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addExam(arg0: CertificationExam): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExam(arg0);
            return result;
        }
    }
    async getExamDetails(arg0: string): Promise<CertificationExam | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamDetails(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamDetails(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExamQuestions(arg0: string): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamQuestions(arg0);
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamQuestions(arg0);
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExamVersions(arg0: string): Promise<Array<ExamVersion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamVersions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamVersions(arg0);
            return result;
        }
    }
    async getExams(): Promise<Array<CertificationExam>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExams();
            return result;
        }
    }
}
function from_candid_KnowledgeDomain_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KnowledgeDomain): KnowledgeDomain {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CertificationExam]): CertificationExam | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    versionId: string;
    knowledgeDomain: _KnowledgeDomain;
    explanation: string;
    text: string;
    isScored: boolean;
    correctOptionIndex: bigint;
    options: Array<string>;
}): {
    id: string;
    versionId: string;
    knowledgeDomain: KnowledgeDomain;
    explanation: string;
    text: string;
    isScored: boolean;
    correctOptionIndex: bigint;
    options: Array<string>;
} {
    return {
        id: value.id,
        versionId: value.versionId,
        knowledgeDomain: from_candid_KnowledgeDomain_n5(_uploadFile, _downloadFile, value.knowledgeDomain),
        explanation: value.explanation,
        text: value.text,
        isScored: value.isScored,
        correctOptionIndex: value.correctOptionIndex,
        options: value.options
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Medications: null;
} | {
    FederalRequirements: null;
} | {
    OrderEntry: null;
} | {
    Other: string;
} | {
    PatientSafety: null;
}): {
    __kind__: "Medications";
    Medications: null;
} | {
    __kind__: "FederalRequirements";
    FederalRequirements: null;
} | {
    __kind__: "OrderEntry";
    OrderEntry: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "PatientSafety";
    PatientSafety: null;
} {
    return "Medications" in value ? {
        __kind__: "Medications",
        Medications: value.Medications
    } : "FederalRequirements" in value ? {
        __kind__: "FederalRequirements",
        FederalRequirements: value.FederalRequirements
    } : "OrderEntry" in value ? {
        __kind__: "OrderEntry",
        OrderEntry: value.OrderEntry
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : "PatientSafety" in value ? {
        __kind__: "PatientSafety",
        PatientSafety: value.PatientSafety
    } : value;
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
